### ISSUE TITLE
Stage Lock indicator always on

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#1]
Original issue at Cilph/RemoteTech2#56.

jonathan-ng wrote:

> Whenever a probe core is on a ship, the stage indicator is always purple. This is possibly related to Issue #52, which seems to affect all decouplers, including stock.

Cilph wrote: 

> Intended behaviour is for the staging lock to work entirely client-side, without time delay. It would prevent transmission of a staging control signal. However the intercepting of the staging signal might cause the stage indicator to light up. I'll have a look at that.

**Comment by rough93** [comment]
is this resolved?

**Comment by gnivler** [comment]
I'm having this issue with develop 497... I haven't troubleshooted but am happy to provide logs etc.

**Comment by rough93** [comment]
I have noticed it as well, I'll take a look at the UI but logs may also be useful.

**Comment by gnivler** [comment]
Thanks for working on it!

I just ran a quick test to contain the log data, by:

Going stock 1215 + RT 497
Clearing techtree cache
Load a copy of my career save
Launch ComSat Alpha vessel successfully via staging, then cut throttle and let it fall/explode

I'm almost certain that in earlier recent builds, the lock was light but I couldn't activate staging.  Staging works now despite the pink light being on.

[KSP.log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/224939/KSP.log.txt)

I'm available for further testing :)

**Comment by rough93** [comment]
From what I can see from some background research, it looks like the following is causing the problem:

RTLockStaging
RTLockSAS
RTLockRCS
RTLockActions

I can't find this within your log specifically, would you double check the debug for your situation?

**Comment by gnivler** [comment]
I'm pretty new at this... I have the Alt-F2 and F12 debug windows but can't find a log file.  It's rolling off the top unfortunately (I set a comment then loaded the launchpad and the comment was scrolled off).

FWIW I did a manually review and don't see the strings you mentioned.

Glad to provide the info if you could point me in the right direction/documentation.

Thank you

**Comment by rough93** [comment]
That's fine, what I provided came from an older source, but seemed to still be the cause, I'll trawl through some of the code to see if I can find these refs

**Comment by rough93** [comment]
I made a change to the files, but I have yet to test it, I've gotten rather busy but I'll try to test it today.
