### ISSUE TITLE
Errors in flight computer commands (after time warp?)

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#10]
Original issue at Cilph/RemoteTech2#163.

HoneyFox wrote: 
> I made a maneuver of circularization at the estimated Ap position after the aero-brake with delay of 356h00m00s, time to the aero-braking Pe is about 355h30m00s. I assumed that the period of the orbit after aero-brake would be around 60 minutes so I added 30min.
> I fast-forwarded and then started the aero-brake, and after that, time-to-Ap is roughly 30 minutes, but I checked the flight computer, only to find there's still 90 minutes left there.

HoneyFox wrote: 
> And I also encountered similar issue in other situations: one of them was a probe orbiting Minmus and I planned a burn with delay of around 9 minutes but the delay got an error of more than 1 minute, there was no SOI change in this case nor was there power supply issue because solar panels have been extended and the orbit plane's normal was pointing towards the sun.

**Comment by Peppie23** [comment]
old Bug, i'll close this
