### ISSUE TITLE
Relay Network only connects to 3 satellites at once

### ISSUE THREAD

**Issue by skiingrules88** [RemoteTechnologiesGroup/RemoteTech#121]
I've built a relay network of 4 satellites around Kerbin but only 3 of them will ever link up in a relay at once.  They're all within range of eachother and above the horizon, but when I switch to one of them it will only ever relay to the 2 on either side of it, and won't extend the relay from those to the one on the opposite side of Kerbin.  Then if I switch to the 4th one, it connects to the 2 on either side and leaves the first one out.
![screenshot0](https://cloud.githubusercontent.com/assets/8028565/3432403/55205364-0074-11e4-90a1-580d09ed4ae9.png)

**Comment by KSP-TaxiService** [comment]
Closing as there are no update on this issue for long time.
