### ISSUE TITLE
Satellites incorectly unregister when unloading 

### ISSUE THREAD

**Issue by JDPKSP** [RemoteTechnologiesGroup/RemoteTech#128]
When deploying a satellite from a mothership, the satellite will correctly unregister itself when unloading (going beyond 2.5 km from active Vessel). It is however not re-registered from its packed state. This results in the satellite disappearing from the network until a force reset of the network takes place (ie reloading).

**Comment by bchmura** [comment]
I think I can confirm this as an issue in 1.0.2.  I launched a probe core from my mun base... no matter how much I flew around, landed, switch to another vessel and came back it worked.  Then when I actually tried to go somewhere, no matter what direction, when, how fast... its seemed like 2.7km away it would lose its connection.  If I swapped out to another ship and back at that point I would have the connection back.  If i can do anything to help, let me know.  great mod, love what it brings.
