### ISSUE TITLE
Targeting active vessel also targets body it's orbiting

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#13]
Original issues at Cilph/RemoteTech2#173, Cilph/RemoteTech2#183.

May be rendered obsolete by #27.

kaufman-bryce wrote: 
> The feature to target the active vessel is quite nice, but could be made much more powerful if that option caused the dish to aim at the planet the active vessel is orbiting as well. Alternatively, a separate option to target active body.

HoneyFox wrote:
> The idea is simple, i would like to use some pseudo-codes:
if ( activeVessel.MainBody == dishIterated.Vessel.MainBody )
fallback to "ActiveVessel" logic // P2P connection logic
else
dishIterated.setTarget( ActiveVessel.MainBody ) // Cone-angle check logic

**Comment by Peppie23** [comment]
Merged into v1.6
