### ISSUE TITLE
Terrain corruption, satellite duplication

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#18]
Original issues at Cilph/RemoteTech2#187, Cilph/RemoteTech2#189.

This bug was supposed to have been fixed by the community hotfix. Unfortunately, reports of its demise seem to have been exaggerated:

Zardizz wrote: 

> Yeah I am also experiencing this with the updated DLL.

Xiong wrote:

> I, too, have been running the "community hotfix":
> http://www.mediafire.com/download/dncc8qu44t30a90/RemoteTech2_2014.01.08.22.30.zip
> 
> I had not seen the issue described here previously but I just now caught something looking like it: lots of ugly UI issues, Space Center does not show; and when I quit and restarted, my station (with RT2 parts on, of course) had been duplicated -- exact superimposed duplicate leading to instant self-destruct. Resolved this by reloading and simply terminating all but the first duplicate station.

**Comment by KSP-TaxiService** [comment]
Hi,

It seems no further reports on both issues are received nowadays. Given that KSP underwent a great deal of changes and improvements, it is presumed that the issues are no longer replicated now.

Should either issue re-surface, kindly open a new ticket and provide required logs.
