### ISSUE TITLE
kOS Compatibility

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#194]
I can't believe we don't have an official issue for this.

So, for the record: it would be really nice if kOS and RemoteTech could talk to each other, so that kOS checks for RemoteTech comms status when filtering commands and so that players could write e.g. target-selection scripts using kOS.

See also KSP-KOS/KOS#60, KSP-KOS/KOS#103.

**Comment by parachutingturtle** [comment]
so does this work right now, or is it still local control for kOS?

**Comment by tomekpiotrowski** [comment]
This has been working for some time.
