### ISSUE TITLE
Range Indicator, Ship Distance, Satellite distance indicator

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#2]
Original issues at Cilph/RemoteTech2#100, Cilph/RemoteTech2#199, Cilph/RemoteTech2#214.

NathanKell wrote:
> I would also suggest a "last leg: current/max" indicator, as usually what really matters when looking at the range indicator is "how far away can I get from the last relay" not "how long is the path?" IMO that's even more important than total path length.

xldenis wrote: 
> It would be useful to have a quick view of the distance between various ships so that it is easy to establish whether or not you can connect to a ship before accidentally losing connection and losing your ship. This has been happening to me while setting up a geo sync network, I've been setting up the satellites at 120 degree angles to replace my first network, but the 5MM omnis I have been using are just barely out of too far from each other to make the connection. If I could have seen the distance between the ships I could have quickly figured out the problem and solved it.

Cilph wrote: 
> List the distance to a satellite in the target selection menu.

**Comment by Peppie23** [comment]
Merged into 1.6
