### ISSUE TITLE
Targeting planet and active vessel around it causes conflict

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#200]
ArrTeeD2 reported a strange bug where targeting a probe around Duna with both a Duna cone and active vessel caused no connection (http://forum.kerbalspaceprogram.com/threads/83305?p=1447900#post1447900). ~~It's possible that @Ippo343 independently ran into the same problem (http://forum.kerbalspaceprogram.com/threads/95443?p=1456530#post1456530), but that's not yet confirmed.~~

Conditions for reproduction unclear as of yet. I propose waiting for the #13 fix before dealing with this issue, in case the new cone code doesn't have it.

**Comment by tomekpiotrowski** [comment]
Please re-open if anyone encounters this again.
