### ISSUE TITLE
Toggle buttons vs. action buttons

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#212]
At the moment, both the flight computer and the satellite selector in the map view use toggle buttons -- click on them once to get a certain effect, click on them again to revert to default. This behavior can be highly confusing, especially in the case of the flight computer when signal and manual delay come into play.

I propose that this interface be replaced with buttons that always have the same effect when you click on them, with the default state being represented by its own button ("Off" in the case of the flight computer, the active vessel in the case of the satellite selector). I think this will be less confusing than the current interface. Thoughts?

**Comment by Peppie23** [comment]
The biggest problem for the new action buttons are that you can't see which mode is active if you have the queue fragment not open. This is why i reopen this issue.

I also created a new draft for the buttons:
![clipboard01](https://cloud.githubusercontent.com/assets/7722222/5712482/1c459ec6-9ab3-11e4-9349-2f58484284de.png)
This are "faked" toggle buttons. They are action buttons but i change the color if the right mode is active.

I think this is a better solution.
