### ISSUE TITLE
FASA Explorer Probe does not animate

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#213]
When both FASA and RemoteTech are installed, the Explorer probe does not extend its antennas in either the VAB or in flight. This bug is cosmetic only; while the animation does not play, the antenna can be switched on and off just like any other.

For reference, the probe extends four antennas from its base when RemoteTech is not installed.

**Comment by Peppie23** [comment]
The problem is that the `mDeployFxModuleIndices` has always one value on it. On the method `FindFxModules()` we'll look for the module for this value, and if the `ModuleAnimateGeneric`  is not the first node on the config file than no animation will be loaded.
