### ISSUE TITLE
Breaking Docking Port Fuel Crossfeed

### ISSUE THREAD

**Issue by assassinacc** [RemoteTechnologiesGroup/RemoteTech#222]
Specs: RT 1.5.1 @ KSP 0.25 x86 @ Win 7 x64

After installing RT all docking ports have fuel crossfeed by default enabled. You can disable it in flight, but it's is'nt presistent (after loading the vessel xfeed is enabled again). NRE: http://pastebin.com/aFGwK36q

Tested Stock against Stock + RT + Modulemanager 2.5.1

**Comment by Peppie23** [comment]
@assassinacc any new feedback for this issue?

**Comment by assassinacc** [comment]
had no more issues like that with the latest version for .90

**Comment by Peppie23** [comment]
thanks
