### ISSUE TITLE
Make KR-7 and KR-14 more distinct

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#227]
A number of players have reported using the KR-7 when they meant to use the KR-14, with predictably disastrous results. For my part, I can't tell the difference without using mouseover/rightclick in the VAB. It might be helpful to make these two dishes more visually distinct, so players always pick the right one for the job.

**Comment by KSP-TaxiService** [comment]
Seem this issue is resolved already as both dishes are different in part size and texture.
