### ISSUE TITLE
Ground base loses Remote Guidance status on unload

### ISSUE THREAD

**Issue by wisq** [RemoteTechnologiesGroup/RemoteTech#232]
Posted in the forum (http://wee.sk/1wL2UL6), reposting here by request:

--

I'm having an issue with the Remote Guidance Unit. It seems to work fine whenever the base is within loading distance, but then the base stops being a viable command post once I'm high in orbit.

I set up a base on Minmus: Ten Kerbals in four ships interlinked by (docked) KAS winches. One of those ships has the guidance unit, as well as omnis and dishes. I've been launching comsats from that base (using Extraplanetary Launchpads) and they've been operating fine. During takeoff, they maintain line-of-sight with the base, and the base is considered a command post, with the red dot on the orbital map view.

But at some point while I was doing corrections with my satellite in a 2,000,000m orbit around Minmus, I realised that I was losing connection every time Mission Control went around the other side of Kerbin — I haven't set up satellites around Kerbin yet. The red dot was gone, and even though I confirmed I had an omni link to Minmus base, I wasn't getting control. Switched to the base, red dot back. Switched to the satellite, red dot gone.

--

More testing: I waited until KSC went behind Kerbin and we lost contact, then launched a super simple probe.  Octo2, radioisotope generator, communotron 32 (active), engine.  Lost control very quickly during ascent, i.e. as soon as the base fell outside 3km and was unloaded.  Interestingly, I also lost omni connectivity with the ground base (all satellites did), but only temporarily; going back to the space center, then coming back to the satellite, I see everyone (including my test craft) has contact with Minmus Base, yet I still don't have control, and the red dot is still gone.

KSP.log just after launching a second test craft and losing contact: https://dl.dropboxusercontent.com/u/32378574/remotetech-guidance-bug.log

Of particular note is that the Chatterer RemoteTech integration throws exceptions at the moment of unload:

```
[EXC 21:26:32.827] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
        System.Collections.Generic.List`1[RemoteTech.ISignalProcessor].get_Item (Int32 index)
        RemoteTech.VesselSatellite.get_SignalProcessor ()
        RemoteTech.VesselSatellite.get_Guid ()
        RemoteTech.API.<HasConnectionToKSC>m__0 (RemoteTech.NetworkRoute`1 r)
        System.Linq.Enumerable.Any[NetworkRoute`1] (IEnumerable`1 source, System.Func`2 predicate)
        RemoteTech.API.HasConnectionToKSC (Guid id)
        Chatterer.chatterer.updateRemoteTechData ()
        Chatterer.chatterer.Update ()
```

However, disabling Chatterer integration doesn't fix it.

Savefile: https://dl.dropboxusercontent.com/u/32378574/remotetech-guidance-bug.sfs

My modlist (bold = I know my save uses parts from this):
* Asteroid Recycling Technologies 0.5.3
* Better Atmospheres 5.0
  * Custom Asteroids 1.1.0
  * DistantObject 1.3.1
  * EnvironmentalVisualEnhancements 7.4-LR
  * TextureReplacer 1.7.3
  * KittopiaTech Planetary Editing Tools 0.18
* Chatterer 0.7.1
* Contract Plus Window 2.2
* CustomBiomes 1.6.7
* DMagic Orbital Science 0.8.6.1
* Deadly Reentry 6.2.1
* Ferram Aerospace Research (FAR) 0.14.3.2
* Fine Print 0.59
* **Kerbal Attachment System (KAS) 0.4.9**
* **Karbonite 0.4.2**
* **Extraplanetary Launchpads 4.3.1**
  * **Karbonite ExtraPlanetaryLaunchpads conversion 16.7**
  * custom EPL-Karbonite-Conversion.cfg from Nori (http://wee.sk/1000XMA)
* Infernal Robotics 0.19.2
* **MechJeb2 2.4.0.0**
* Precise Node 1.1.1
* Procedural Fairings 3.10
* RealChute Parachute Systems 1.2.5.3
* **RemoteTech 1.5.1**
* Romfarer LazorDockingCam v34
* SCANsat v8
* Soundtrack Editor 2.1a
* Toolbar 1.7.7
* TweakScale 1.44
* Universal Storage
  * US Core 0.9.0.242
  * US KAS 0.9.0.141
* Vanguard Technologies EVA Parachute 1.2
  * VNG Plugin 0.7.2
  * automatic enabling of parachutes for all EVAs (http://wee.sk/1001gH5)
* Active Texture Management

**Comment by ACReeser** [comment]
I found I had a remarkably similar issue, but with a command station in orbit above Duna.
My bug description:
Very large vessel with 6 kerbals and the big probe core. When loaded, it acts as a command station, but when unloaded it does not. 
The vessel entry in the save file is in this [gist](https://gist.githubusercontent.com/ACReeser/0a073178726c9daab61b/raw/811e146c6e486d2ce1344584f1ce2f9a47fc6be2/Kuggernaut.vessel)
I can get the .craft file too, but what's in orbit has had several additions on-orbit.

I believe I've found the issue in ProtoSignalProcessor.cs because I combed the source for all uses of ```IsCommandStation``` and ```HasCommandStation```.  My game's RemoteTech log from ProtoSignalProcessor.cs shows that something in the constructor is throwing an error (I suspect ```ppms.GetInt("RTCommandMinCrew")``` ).

I do not know this codebase well enough to speculate on the true root cause, but I believe a workaround would be to default to a ```RTCommandMinCrew``` of 6 instead of defaulting to setting ```IsCommandStation``` to false.

I will be submitting a pull request with this change shortly.

**Comment by Peppie23** [comment]
thanks for your pr. I'll look into it :+1:

**Comment by Peppie23** [comment]
I can reproduce this issue, or a more similar way:
- Put a small groundstation with at least 7 kerbals on Minmus (low gravity ^^)
- Make EVA with one kerbal and fly away to get over the 2.5km

If you look on the map, the groundstation is no longer registered, even not as a satellite. You can fix that problem by going to the tracking station and back (reload)

I've spend some time with that problem and i think the groundstation will not be re-registered as a ProtoSat. I'll try to test some docking examples.

But i can not see any relation to 'Default min crew #276'.
More related and duplicate to #128 and #3 

:confused:

**Comment by wisq** [comment]
Whew, glad someone else was able to reproduce this, because I've long since moved on from that save + mod combo and wouldn't have been able to boil it down to a simple case like above. :)  Thanks for pursuing this.

**Comment by Norgg** [comment]
Been having the same issue here, small base on Minmus with 6 Kerbals and using Karbonite and EL, I can launch new probes and they're fine until the base unloads and then they lose control.

**Comment by wisq** [comment]
Yeah, I'm actually getting the same issue now on my new save, too.  OKS space station using the OKS Colony Command Center as the controller.  9 Kerbals on board (or 11?  I forget), shows up as a red dot and can control ships in its immediate (loaded) vicinity.  Used to show up as a red dot all the time, but now immediately loses that status when it unloads.

Parts used: Kolonization/OKS, ExtraPlanetaryLaunchpads (OKS orbital shipyard), Infernal Robotics (rotating washers), Hangar (multipurpose tanks, universal adapters), Station Science.
