### ISSUE TITLE
Enable other mods to push custom commands

### ISSUE THREAD

**Issue by JDPKSP** [RemoteTechnologiesGroup/RemoteTech#233]
In order for other mods to more closely interface with RT, it should be possible for them to push custom commands in the flight computer, to then later have an event fired within the mod when the command is popped.

In pseudocode such a Command, inheriting from AbstractCommand, could include the following fields:

string guiName; //What to display in the visual queue
bool guiActive; //Whether to display the command in the visual queue at all
Object (or possibly ConfgNode) data; //the input data whith wich to call the event native to the mod

**Comment by SirDiazo** [comment]
I'd just like to bump this to second it.

I'm looking to integrate Action Groups Extended and with the existing API in 1.6 I can do the delay on directly controlled actions easy enough, but I have no way of adding to the flight computer.

Now, I am stumbling on how exactly to make this general to all mods. Is there some way to hook in a callback? I'm not sure how else to link the commands back.

I'm installing RemoteTech now to test, depending on how things go I'll update this post.

**Comment by JDPKSP** [comment]
I would recommend to use Guid and Confignodes in stead:
RemoteTechAPI.AddFlightComputerCommand(Guid vesselID, ConfigNode command)
Where the flight computer tries to look for GUIdescription field to provide the GUI description.
Using a confignode, it would be much easier to send more complex commands without having to do your own custom serialization of a string.

**Comment by JDPKSP** [comment]
And to add. The absence of a GUIdescription field within the confignode would mean that the command is simply not shown within the flight computer. If your mod is adding a lot of commands continuously, you wouldn't want to spam the command queue with them.

**Comment by SirDiazo** [comment]
That is actually a good point, there are really 3 types of commands I can think of that this would need to support.

1) The other Mod does everything, RemoteTech just tells it when to activate. This is the example my previous post had. The external mod would add a command to the flight computer that when it was up, RemoteTech would tell the mod "Activate now" and the other mod does everything. This type of command would show on the Flight Computer GUI.

2) The other Mod does everything, but does not show on the Flight Computer. Pretty much the same, but this would be used for things that should not show on the Flight Computer, but should still be subject to signal delay. This would require adding a "remove command from Flight Comptuer" method to the API as well.

3) Mod enters the command, but RemoteTech executes. For stuff like "face prograde", or "set throttle", this would essentially mimic entering the same command via the flight computer's GUI, just done by a mod through code.

For that, a confignode makes much more sense. If RemoteTech is just bouncing the command back, it does not matter what is in the config node so it is much easier for the other mod to work with, and if it is a command RemoteTech will execute, as long as the confignode is in a format remotetech recognises, that works too.

As for Guid, that works too, any unique identifier works and I think I've seen Guid used elsewhere in Remotetech's code.

**Comment by SirDiazo** [comment]
Okay, i'm writing code for this and I think I have a working setup.

However, if a vessel has multiple potential flight computers, what would be the best way to get a reference to the correct computer so I can add the command? As the command is coming from outside, I don't have the internal reference commands currently use when assigned via the on-screen GUI.

(Also, is there a dev thread on the forums for this mod where I could put questions like this?)

**Comment by Peppie23** [comment]
Hi diazo,

I think it is not possible to have more than one flight computer on a
vessel, because the flight computer is bound to the vessels guid.

We've no dev-thread :/ Should we create one?
Am 20.01.2015 06:37 schrieb "SirDiazo" <notifications@github.com>:

**Comment by SirDiazo** [comment]
Okay, I need to dig into the code some more then, I found the partModule references to the flight comptuer but not where it limits it to one per vessel Guid.

**Comment by Peppie23** [comment]
Hi, i thought it was the guid. :blush: With this code you can get the current flight computer: https://github.com/Peppie23/RemoteTech/blob/master/src/RemoteTech/UI/TimeWarpDecorator.cs#L163

**Comment by SirDiazo** [comment]
Ohh, thank you for that, saves me hunting that down.

Now, just to make sure I'm not short-circuiting something, it looks like this here is how I would add a command to the flight computer by passing it a new ICommand class I'm making for this:

https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/FlightComputer/FlightComputer.cs#L143

However, when I look at the GUI buttons, they are using this () => RTCore... thing that goes straight over my head.

https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/UI/AttitudeFragment.cs#L132

Is it okay if I find the correct flight computer and then use that Enqueue method I linked, or is there other stuff on that code behind the GUI button I need to hook into?

**Comment by Peppie23** [comment]
Yes the `Enqueue` is the method you need.
Here is a more clear example:
https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/UI/AttitudeFragment.cs#L296

And yes, you should create a new ICommand-Class. Maybe `ApiCommand` but this is up to you ;)

**Comment by SirDiazo** [comment]
That is pretty much everything I need I think.

I wrote my first try at the new ICommand class (I called ExternalModCommand, you want me to put API in the name somehwere?) and got stuck on how to correctly add it to the flight computer to test it out.

Those two links you gave me look like exactly what I need so I'll see what progress I can make tonight.

**Comment by Peppie23** [comment]
no its ok with the name of the command.

**Comment by JDPKSP** [comment]
When popping custom commands I'd recommend using a static callback<Guid,ConfigNode>, since custom commands would still be handled persistently and serializing callbacks would become very messy. This does require other mods to have a fair bit of persistence themselves, so it might be prudent to add a PersistenceLoaded flag to the configNode when it is saved to persistence. Just so other mods have the opportunity to ignore commands that have passed through persistence.
I would also like callbacks in the API for events such as OnDisconnected, OnConnected, OnUnpowered, OnPowered. Just so that other mods don't have to constantly check connectivity.

**Comment by SirDiazo** [comment]
@JDPKSP I ended up going with reflection instead of using callbacks for passing commands back and forth

I don't actually know how to setup a callback and will have to ask someone else to look into OnDisconnected events and such.

I made a PR here https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/317 that shows my initial implementation and design, although I have not dealt with any saving issues yet.

**Comment by Peppie23** [comment]
Jo Jo, @SirDiazo i got some time to look into the `ExternalAPICommand`, good job btw but i would like to change some small parts.

I've planned this:
- changing the name of the api call from `ReceiveData` to `QueueCommandToFlightComputer`
- changing the return value from `void` to `bool` to become a response for queueing a command to the flightcomputer
- adding a new value `Executor` to the externalData-Node
- adding an optional second ReflectionMember for our Execute-method to the externalData-Node
- some refactoring

---

###### Point 2 - changing the return value
If we can't find the vessel with the given Guid, or for other incompatibility, we can return false and will not enqueue this command.

###### Point 3 - adding a new value `Executor`
If i use your mod and enqueue a command from it with a delay of some days and leave the vessel, we'll save the externalData with the references to your mod. If i uninstall your mod and switch back to this vessel i'll notify a message to the user that he has uninstalled the Mod {Executor}

###### Point 4 - adding an optional second ReflectionMember for our Execute-method
This is more an idea for other modders. Our execution-method is called if a command is the current active command and we'll trigger this method until we get true from this method back. I also would like to pass the externalData back to this method.

---

What do you think?

btw. for your question about the ShortName. The ShortName-value is the label of the command if its active and moved to the top. (only needed of we use the execute-method) The Description-value is the label for a command on the queue.

**Comment by SirDiazo** [comment]
Alright, sorry about disapearing like that but Real Life happened.

My opinion on this is do what you need to the remotetech code so that it lines up with your expectations.

While I can make code work, I know I did not fully line up with what remotetech expects, notably where you changed the return from void to bool, I couldn't figure that out when I did this originally so it was kind of a big question mark.

I'll tweak AGX to match what you do, it's a single text string where I change the name of the method I'm looking for on the RT side of things.

**Comment by Peppie23** [comment]
np @SirDiazo take your time. But what i've realized is, that you can't push any kind of "custom data" from your side to the command, like "ActionGroup55" that you know what action should be triggered after popping the command on the flight computer :cold_sweat:
You saved the complete `externalData` ConfigNode into the ApiCommand and i removed this because i don't know how to save this object to the persistent file, without doing a ugly foreach over ech value -.- Maybe we should fix that.

**Comment by SirDiazo** [comment]
erm, I thought I had that working, you simply add the confignode as a node object to the save routine.

Here's where the ConfigNode is added to the saving node
https://github.com/SirDiazo/RemoteTech/blob/1.7.0/src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs#L35-L38

and here's the loading of the node
https://github.com/SirDiazo/RemoteTech/blob/1.7.0/src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs#L44

Doing it this way saves it to the persistent file, it attaches to the confignode KSP passes us on the Save that represents the persistent file and therefore when KSP passes us the confignode from the persistent file when Loading, we can read the confignode as it is.

Note that I did make one assumption, that the Save/Load methods exposed in the AbstractCommand class are linked into the Save/Load methods of KSP for read/writing to the persistent file. As my tests of save/loading the confignode this way worked, I believed that was a safe assumption.

**Comment by Peppie23** [comment]
@SirDiazo i don't know why ksp didn't save the ConfigNode object properly yesterday :/ I think ksp is trolling me. But, i fixed that proplem :tada: and you can now pass any data you like with the `externalData` object.

**Comment by JDPKSP** [comment]
@SirDiazo Save/Load for each ICommand is called within the Save/Load methods of the FlightComputer, which in turn is called within the Save/Load methods of ModuleSPU which - as derived from PartModule - is called whenever the game saves or loads any PartModule.
So any persistent data handled by ICommands is ultimately handled on a PartModule level, not vessel or game level.
Now if this has any importance with what you are doing I don't know.

A small note though. From a quick glance, it looks like you aren't invoking your reflected methods with a ConfigNode. This could be a problem for any mod that needs to do anything more complicated than toggling states. Say for example a fictional mod KerbalPartyHat wants to queue up a command, changing the color of Jebs joke pirate hat. They'd need to send and receive a ConfigNode representation of RGB or have a destinct method for each possible color. Passing ConfigNodes back and forth between mods give each mod maker a single easy accesspoint with which to receive data that they can then deserialize into whatever object they need.

I really like the inclusion of an Execute method. It does make passing ConfigNodes back and forth a somewhat more CPU taxing experience; serializing and deserializing for each active ExternalAPICommand for each gametick.
Perhaps the thing to do is to pass a class implementing IConfignode back and forth. It then shouldn't be a big issue for RT to handle persistence by serializing on Save and deserializing on Load. and we are then simply passing an object reference back to the mod.

Why the restriction to active vessel by the way? Since all loaded Vessels with a SPU have a working FlightComputer, any loaded vessel should be subject to commands.
As the code is now, wouldn't it be possible to enqueue a command for one vessel, then switch to another, and have the command act for the other vessel?

And another note. I don't think you should do your empty string checks by creating an empty string and evaluating equality each time. In stead you should use
!string.IsNullOrEmpty(SomeString)
think of the children... I mean; memory. :smile:

**Comment by Peppie23** [comment]
@JDPKSP i think your notes are all addressed to me :relaxed:, because i changed SirDiazo's first version to the current.

> A small note though. From a quick glance, it looks like you aren't invoking your reflected methods with a ConfigNode

I do, with the given ConfigNode from the Api call [ExternalAPICommand.cs#L229](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/1.7.0/src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs#L229)

> Why the restriction to active vessel by the way? Since all loaded Vessels with a SPU have a working FlightComputer, any loaded vessel should be subject to commands.

I restrict this because i'm not sure what this can cause with the "saved" commands for every other flightcomputer. Thats why i limited this function to the current computer.

> In stead you should use !string.IsNullOrEmpty(SomeString)

thanks :sweat_smile:

**Comment by SirDiazo** [comment]
@Peppie23 Good to hear this is cleared up. I was about to grab the latest source and start digging into this myself to double check my previous results.

@JDPKSP Thanks for the Save/Load clarification. I'm not sure what you mean by "From a quick glance, it looks like you aren't invoking your reflected methods with a ConfigNode." though. The entire point of this is to pass a piece of data to remotetech (an external mod telling remotetech that it wants to activate after a delay) and then pass a piece of data back (remotetech telling the external mod the delay has elapsed, activate now).

As a ConfigNode is KSP's method of saving data of choice, that seemed like a logical object to use.

My confusion then increases as a few lines later you say "Passing ConfigNodes back and forth between mods give each mod maker a single easy accesspoint with which to receive data that they can then deserialize into whatever object they need." which is exactly what this is doing.

Or is supposed to be doing anyway, is there something odd you've noticed that is doing something else?

**Comment by JDPKSP** [comment]
@Peppie23 Yeah Just after writing that wall of text I noticed your commit.
Anyways, here's another wall o' text :grinning: 
Regarding limiting ExternalAPICommands to only the active vessel.
I still think it would be nice to other modders to allow them to enqueue commands in other vessels than the current active vessel.
Personally I find a lot of use in the FlightComputer of other vessels. It makes for a good docking assistant. And who knows what use other modders could have for this functionality.

And now looking through your commit, [API.cs#L112](http://github.com/RemoteTechnologiesGroup/RemoteTech/blob/1.7.0/src/RemoteTech/API/API.cs#L112).
I know, nitpicky. But formal logic compels me:smile::
this should either be
```C#
!(externalData.HasValue("GUIDString") && externalData.HasValue("Executor") && externalData.HasValue("ReflectionType"))
```
or
```C#
!externalData.HasValue("GUIDString") || !externalData.HasValue("Executor") || !externalData.HasValue("ReflectionType")
```
Since the original statement is false if at least one of the values are present.
We'd want the statement to be false iff all the values are present.

and regarding [ExternalAPICommand.cs#L101](http://github.com/RemoteTechnologiesGroup/RemoteTech/blob/1.7.0/src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs#L101). This could have some unintended consequences. Since any ExternalAPICommand that has an Execute function would force the FlightComputer into killrot mode when finished, even if the function had nothing to do with orientation. In cases where the player wants to keep a specific relative orientation, this would be very irritating, and possibly disastrous.

A bit related to this. How about including the option to toggle modes in the flight computer directly?
say for example change from [API.cs#L107](http://github.com/RemoteTechnologiesGroup/RemoteTech/blob/1.7.0/src/RemoteTech/API/API.cs#L107):
```C#
//exposed method called by other mods, passing a ConfigNode to RemoteTech
public static bool QueueCommandToFlightComputer(ConfigNode externalData)
{
	//check we were actually passed a config node
	if (externalData == null) return false;
	{
		RTLog.Verbose("No command was passed", RTLogLevel.API);
		return false;
	}
	
	//check our min value
	if (!externalData.HasValue("GUIDString"))
	{
		RTLog.Verbose("Passed command did not contain GUIDString", RTLogLevel.API);
		return false;
	}
			
	var externalVesselId = new Guid(externalData.GetValue("GUIDString"));

	// you can only push a new external command if the vessel guid is the current active vessel
	if (FlightGlobals.ActiveVessel.id != externalVesselId)
	{
		RTLog.Verbose("Passed guid is not the active Vessels guid", RTLogLevel.API);
		return false;
	}

	//get the VesselSatellite
	var sat = RTCore.Instance.Satellites[externalVesselId];
	if (sat == null)
	{
		RTLog.Verbose("Vessel did not have an SPU", RTLogLevel.API);
		return false;
	}

	//get the flightcomputer
	var computer = sat.FlightComputer;
	if (computer == null)
	{
		RTLog.Verbose("Vessel did not have a flight computer", RTLogLevel.API);
		return false;
	}

	//if no Executor or ReflectionType is passed, check if Serialized forms of AbstractCommands are passed
	if (!(externalData.HasValue("Executor") && externalData.HasValue("ReflectionType")))
	{
		bool CommandsCreated = false;
		foreach (ConfigNode n in externalData.nodes)
		{
			var command = FlightComputer.Commands.AbstractCommand.LoadCommand(n, computer);
			if (command != null)
			{
				CommandsCreated = true;
				command.TimeStamp = RTUtil.GameTime;
				computer.Enqueue(command);
			}
		}

		if (!commandsCreated)
		{
			RTLog.Verbose("Executor and or ReflectionType missing and no valid RT commands", RTLogLevel.API);
		}

		return CommandsCreated;
	}

	try
	{
		var extCmd = FlightComputer.Commands.ExternalAPICommand.FromExternal(externalData);

		computer.Enqueue(extCmd);
		return true;
	} catch (Exception ex)
	{
		RTLog.Verbose(ex.Message, RTLogLevel.API);
	}

	return false;
}
```
For example: AGEext could add FlightComputer control to actionGroups.

**Comment by SirDiazo** [comment]
Test log with AGX and current version 1.7.0 (as of "Small Fixes #360" being added.

Note that is this a real-time log, I intend to flesh out my comments below, I just want to note them as I come across them so I don't forget anything.

1) If the current vessel does not have a flight computer, RT throws a null ref when trying to queue the command. (Noticed on stock Kerbal 2).

**Comment by JDPKSP** [comment]
@SirDiazo your receive method should actually return false.
Take a look at [FlightComputer.PopCommand()](http://github.com/RemoteTechnologiesGroup/RemoteTech/blob/1.7.0/src/RemoteTech/FlightComputer/FlightComputer.cs#L254-L282)
The queue behaviour is such:

for each enqueued ICommand where delay(+extra delay) is over, ICommand.Pop(FlightComputer fc) is called. This method is called only once and then the ICommand is removed from the command queue. If the pop method returns true, the ICommand is moved to a prioritized list of active commands.

each tick, each ICommand in the prioritized list of active commands gets its Execute method called. when the Execute method returns true, the command will be deleted.
Note that only one instance of a given priority (represented as an int) can be present within the list of active commands. For example AttitudeCommand has a priority of 0 (meaning it gets the top position of the active commands in the GUI.

the Abort method is called if the ICommand being executed should abort. for most commands, this merely forces the Execute method to return true.

@Peppie23 Given that we aren't passing the FlightCtrlState to the ReflectionExecuteMethod (and please correct me if i'm wrong) maybe we shouldn't give ExternalAPICommands a priority of 0. Perhaps we could expose the priority variable to allow modders to set the priority (or assume something like 255 if they don't).
And another suggestion: How's about we add a GuiActive flag to ExternalAPICommand. Let's say a modder needed to pass a lot of commands. For example some form of control input that cannot be handled by FlightCtrlState. The GUI queue would instantly fill up with possibly hundreds of commands, one being enqueued each tick

**Comment by SirDiazo** [comment]
@JDPKSP Thank you for the explanation. It looks like I fell through a loop hole where I returned True on the Pop method, but as I had no Execute method to move to the priority list, RT just cleared the command so everything looked fine.

So for AGX, as I only need the call back once when it is time to activate the action group, I should use the Pop method, but return False to RT telling it I'm done with this command and it can be deleted.

Also, your explanation about how things work makes me think of a couple things.

1) Because the Execute method runs every frame, that means the reflection callback runs every frame. Back when I was figuring this reflection stuff out, other programmers warned me that reflection is a very expensive process in terms of CPU load and that calling it every frame is not ideal. Having said that, I can't think of another way to allow a command to stay showing on the flight computer GUI while the command is executing so this is more me tossing this out to see if you guys have any ideas for an alternate method then a request for making a change to the code.

2) External mod passing a lot of commands. I'm not sure how far this should be pursued. This comes back to how much time you want to spend hardening the mod against issues in other mods. As this method allows you to pass a config node, the other mod should collate everything into one confignode and only make a single request of RT to queue. If the other mod does not collate and tries to pass 50 string values as 50 individual requests, I'd argue that is the other mod's problem. Perhaps a throttle limit is needed so that one mod does not bring down the entirety of the RT network, but I have no clue how practical it would be to program such a thing.

**Comment by leftler** [comment]
@SirDiazo One way around the "slow reflection" issue is instead of doing reflection every time you create a delegate the first time then use the cached delegate from then on.

        private Dictionary<string, Func<ConfigNode, object>> _delegateCache = new Dictionary<string, Func<ConfigNode>>();

        /// <summary>
        /// Calls the rflection method.
        /// </summary>
        /// <param name="reflectionMember">Name of the reflection method</param>
        /// <returns>Object from the invoked reflection method</returns>
        private object callReflectionMember(string reflectionMember)
        {
            Func<ConfigNode, object> function;
            var key = this.ReflectionType + reflectionMember;
            if (!_delegateCache.TryGetValue(key, out function))
            {
                Type externalType = this.getReflectionType(this.ReflectionType);
                MethodInfo methodInfo = externalType.GetMethod(reflectionMember, BindingFlags.InvokeMethod | BindingFlags.Public | BindingFlags.Static);
                function = (Func<ConfigNode, object>)Delegate.CreateDelegate(typeof(Func<ConfigNode, object>), externalType, methodInfo);
                _delegateCache[key] = function;
            }
            
            return function(this.prepareDataForExternalMod());
        }

**Comment by SirDiazo** [comment]
@leftler I'll look into that when I go into making sure the AGX-RT-kOS triangle play nice with each other.

I'm still playing catch up on a bunch of little things KSP 1.0 broke in my mods.
