### ISSUE TITLE
Weak roll authority when using flight computer.

### ISSUE THREAD

**Issue by PaidLeber** [RemoteTechnologiesGroup/RemoteTech#235]
Pitch and heading work o.k. when using the custom option for the flight computer on a rocket but roll will not stabilize and oscillation amplitude will increase not decrease even with gimballed engines and/or movable fins. Once I disengage the remote tech flight computer and engage SAS, the craft's roll movement will stabilize.

I tried it in stock with just RT, and with FAR. I used procedural fairings with FAR however to ensure it wasn't drag making the craft unstable.

**Comment by KSP-TaxiService** [comment]
Given that this issue is related to the old-version Flight Computer, whose PID controller underwent a major modernisation recently (Issue #674), I presume this issue should not be re-surfaced now.
