### ISSUE TITLE
Network has links that shouldn't be possible

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#236]
Posted by @sick13 on the [forums](http://forum.kerbalspaceprogram.com/threads/83305?p=1527055#post1527055):
> I have One Dish Pointing at EVE form Kerbin one at EVE pointing at Kerbin (a couple of omnis 3 or four) i started noticing while in orbit around K. that the line from the omni was not respecting 500km distance and was going trough kerbin (connecting with the station around K.)
> 
> this started to happen the moment i was approaching the runaway with KSO shuttle
> 
> Using KSP 0.25x32 RT 1.5.1 (aies antennas modified the distance and dish angle only to my liking other than that everything is as downloaded)
> 
> The game did not crash and after the vessel recovery everything went back to normal 
> 
> Logs:  https://www.dropbox.com/s/h9tub95gduvvhpr/KSP_RT151.rar?dl=0

**Comment by Peppie23** [comment]
@sick13 We've a small cheat option to disable the LoS, if you've activated the "infinite EVA". Can you please confirm this issue without the "infinite EVA" option? Otherwise, I would close this issue. :relaxed:
