### ISSUE TITLE
Addon Controller Compatibility

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#237]
Kerbas_ad_astra and Gfurst have suggested that we add support for [Addon Controller](http://forum.kerbalspaceprogram.com/threads/94811), letting players use it to enable/disable RemoteTech. I have no idea what this entails on our end, but it might be the easiest way to implement #23.

**Comment by neitsa** [comment]
Quick follow up: #23 is already closed and AddOn controller hasn't been updated  since almost  2 years  now (still stuck at ksp 0.90), so I'm  closing  this issue.
