### ISSUE TITLE
impossible local control

### ISSUE THREAD

**Issue by stardestroyer** [RemoteTechnologiesGroup/RemoteTech#238]
I've just launched a probe to Duna using a B9 shuttle (not a rocket from launchpad) to save founds. Since I've undocked it from cargo bay it gives me local control instead of green status connection. I've used 2 antennas (Communotron 88-88 and Communotron 16) and I can control the probe even with every antenna deactivated. I also don't have a delay effect. 
I'm wandering if undocking from a shuttle is an improper way to use a probe? Seems it consider the probe as manned like the shuttle. Also a space telescope loaded with a shuttle cargo gives me local control and I can use it without antennas... I can provide a persistent file (but don't know how to upload). Also loaded a list of the mod I use (every mod is the latest version). KSP 0.25 32bit forced in opengl on win 64bit
![mods](https://cloud.githubusercontent.com/assets/9807166/5076281/2536d404-6e9a-11e4-8e47-022b12f1e026.PNG)

**Comment by mrmodji** [comment]
Got the same problem. Reverting to VAB and deleting the DP-10 from the craft fixed the problem.

**Comment by KSP-TaxiService** [comment]
This is pretty old issue and it does seem like a third-party probe core/mod having own command module that misleads RT into thinking this vessel is manned.
