### ISSUE TITLE
Groundstation dot color

### ISSUE THREAD

**Issue by NathanKell** [RemoteTechnologiesGroup/RemoteTech#240]
It would be great to be able to define the color of the dot used to display groundstations on map view. For example, for RSS I would like each launch site to have a small antenna, but I also plan to add the MSFN / STDN (good to 10,000miles), as well as the DSN (good to Pluto+) and it'd be great if those sites could be differentiated visually.

**Comment by Peppie23** [comment]
@leftler i added a small solution to tint the groundstation. If you want you can try to use this new Fineprint-bubbles, but i think this would be to much for RSS user.

@NathanKell i added a new property `MarkColor` for the `STATION` part on our settings. The format is R,G,B,A

I'll merge this for v1.6

**Comment by Peppie23** [comment]
Merged into v1.6
