### ISSUE TITLE
Request: Hide ground stations on map.

### ISSUE THREAD

**Issue by pjf** [RemoteTechnologiesGroup/RemoteTech#241]
If this is already implemented, then my apologies; I've played with all the buttons and missed it!

I'd love a way to be able to hide ground stations, as games that have many of them result in very spotty screen-shots:

![](http://i.imgur.com/izts3zI.png)

A nice-to-have would also be to not display ground stations that are on the other side of the planet (most of the ones on the screenshot). I can open another ticket for that if you'd like.

Many, *many* thanks,

~ Paul

**Comment by Peppie23** [comment]
@pjf i've added a new property `HideGroundStationsBehindBody` to the RTSettings file. This new option is default `false` you've to enable it.

Merged into v1.6

@NathanKell thanks for the code snippet

**Comment by pjf** [comment]
@Peppie23 : Thank you *so* much. My screenshots are going to look amazing! You rock!
