### ISSUE TITLE
M-38 Unoccupied Guidance System

### ISSUE THREAD

**Issue by gatosgit** [RemoteTechnologiesGroup/RemoteTech#242]
Hi, So I've been using Remote Tech and having a lot of fun setting up networks, but I've launched two satellites with the M-38 Unoccupied Guidance System and remote tech detects them as Local control satellites, since it was my first satellites I assumed it was just a occasional bug, but  now that I'm trying to send more satellites with the M-38 UGS remote tech keeps them as local controls even after launch...

Definitively not a big problem, but it's kinda of a bummer to use other parts so I can keep using signal delays and time plan my burns better.

![2014-12-03_00007](https://cloud.githubusercontent.com/assets/5193165/5286272/1661190e-7b23-11e4-9ecc-44f4a03a180e.jpg)

**Comment by Peppie23** [comment]
Hi,
we've added the "M-38 Unoccupied Guidance System" - RemoteTech- part.cfg with v1.6.
