### ISSUE TITLE
Manuever burn delta V off by factor of 2

### ISSUE THREAD

**Issue by NathanKell** [RemoteTechnologiesGroup/RemoteTech#243]
Using RO and Ven's Stock Revamp Skipper configured as RL-10A-1, it appears that RemoteTech flight computer decreases the "delta V remaining" counter twice as fast; when I tell it to burn 1000m/s it burns 500 (but shows the countdown 1000->500).
Note that I have expended solids in my stage (ullage), is it possible it is including their thrust and assuming it counts in (they provide roughly the same thrust as my RL-10).

If that is the case, do check if an engine has fuel before decrementing delta-V remaining by its thrust...

**Comment by Peppie23** [comment]
Merged into 1.6

**Comment by pjf** [comment]
@Peppie23 : You are awesome, thank you so much! :)
