### ISSUE TITLE
Vessel spins out of control when selecting orientation in Flight Computer

### ISSUE THREAD

**Issue by t0chas** [RemoteTechnologiesGroup/RemoteTech#244]
Hi, 

by placing the adapter as the root node and then rotate it 180\* 
any orientation command set in the flight computer will cause the vessel to spin out of control

this vessel will spin
![2014-12-07_00002](https://cloud.githubusercontent.com/assets/4617293/5330438/a872fa6e-7db8-11e4-8ce3-bf444fad4d16.jpg)

this vessel will work fine
![2014-12-07_00003](https://cloud.githubusercontent.com/assets/4617293/5330439/b0646c58-7db8-11e4-8b3d-527f238829bc.jpg)

I have several mods installed
KSP: 0.25 (Win32) - Unity: 4.5.2f1 - OS: Windows 8.1  (6.3.9600) 64bit
USI Tools - 0.2.4
B9 Aerospace - 5.2.6
Community Resource Pack - 0.2.3
Kerbal Engineer Redux - 0.6.2.12
Fine Print - 0.59
Firespitter - 6.3.4
RasterPropMonitor - 0.18.3
Kerbal Construction Time - 1.0.3
KineTechAnimation - 1.1.1
KSP-AVC Plugin - 1.1.5
Neophyte's Elementary Aerodynamics Replacement - 1.3
Final Frontier - 0.5.9.177
ORSX - 0.1.3
Protractor Continued - 2.4.14
RCS Build Aid - 0.5.2
RemoteTech - 1.5.1
ResGen - 0.28.2
StageRecovery - 1.5.1
TextureReplacer - 1.10.2
TAC Life Support - 0.10.1.13
Trajectories - 1.0
USI Survivability Pack - 0.1.3
Universal Storage (Core) - 0.9.3.25

**Comment by jberkman** [comment]
:+1:

i've got a satellite that has a forward-facing (upside-down) heat shield as the root part (so kerbal engineering calculates stage dV correctly) and it spins out of control when setting attitude.

**Comment by sshilovsky** [comment]
I have similar issue when executing maneuver node with the engine attached in wrong direction. Is it possible to consider ship's thrust vector for this too?

**Comment by Peppie23** [comment]
Issue still exists. Probe: https://gist.github.com/Peppie23/0c734603487d13fafcf9
The root part from this probe is the second service bay.

**Comment by charliepryor** [comment]
Definitely still exists, and it's making my game pretty much unplayable. I'm sure it's a conflict with an existing mod, but I have no idea which it is. I have about 7000 patches being applied at startup from 112 mods (most of them are very small, single use or a few parts). All are confirmed compatible with 1.0.5.

Is there a list of known mods which conflict with RT, so I can disable them? The sole reason for me starting a new game with KSP was to make things more realistic and difficult... which I cannot do if RemoteTech's flight computer can't do something as simple as "point that way."

Only one sat in orbit now... don't think I care to play for a second right now.

**Comment by KSP-TaxiService** [comment]
Tested on KSP 1.2.2 with the latest RT develop, the fraction of this bug is reproducible. The rest of the bug is  not reproduced anymore on a flipped root node.

The kill-rotation function is still taking the "direction" of a flipped root node and produces the opposite effect. It works properly on the default-face of a root node.

**Comment by KSP-TaxiService** [comment]
The likely codes are these lines [(1)](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/FlightComputer/Commands/AttitudeCommand.cs#L117) [(2)](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/FlightComputer/Commands/AttitudeCommand.cs#L135).

**However**, the kill-rotation bug is reproducible only within a single play session and after launch (orbit cheat or normal lanuch). If you exit to the main menu and resume the game, this bug vanishes.

**Comment by KSP-TaxiService** [comment]
Discussed with RT members, we decide not to fix this issue as this bug is largely not reproducible in KSP 1.2 and RT's Flight Computer is to be rebuilt completely in RT 2.x
