### ISSUE TITLE
Inaccurate maneuver burns with the flightcomputer

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#255]
We noticed that some engines (only monoprop engines?) are inaccurate by executing a maneuver with the flightcomputer. Here are some infos from issue #243 : 

pjf wrote:
> I don't know if I've encountered this or not. I had RO cut out after 7m/s into a 30m/s burn. I have 
> expended solids, but not in the current stage (they're all in stage 1, which I never activate; it's reserved
> for action groups). However if the stage 1 engines or any active but exhausted engines are countered
> towards the thrust total, then that would explain the behaviour I've seen.
> Images immediately before and after the burn: [before](https://imgur.com/a/eyfor#69), [after](https://imgur.com/a/eyfor#70).

Me wrote: 
> Hi, i can reproduce this bug with the O-10 monoprop engines and a fresh copie of ksp (0.90,0.25).
> ![clipboard01](https://cloud.githubusercontent.com/assets/7722222/5458867/162fccb8-8556-11e4-99bf-03a7cc6c8630.jpg)
> 
> - Download the test Vessel [Test-Vessel](https://www.dropbox.com/s/utkvlcyx2reobrg/Issue243-Testvessel.craft?dl=1)
> - activate infinite rsc/fuel
> - make a orbit
> - add a new maneuver and execute via flightcomputer

tgharold wrote:

> My suspicion is that Remote Tech's Flight Computer does not deal well with the case of burning off > a large fraction of your mass.  For instance, I have a satellite which is about 90% fuel mass and I
> need to burn off 1/4 of that in a single maneuver node with an engine of only 0.25 TWR.  Initial
> acceleration of the vessel starts at around 1.3 m/s/s, and gradually increases to 2.0 m/s/s through
> the 20 minute burn.

> The Flight Computer correctly calculates that it is a 20 minute burn, but instead of using the API
> information it seems to do its own calculation.  As a result, on long burns of > 10 minutes, I have to
> finish up the burn by myself because the FC only performed about 80-90% of it.

I also tried to hunt this issue but without success, for now. I checked the calculated dV for the complete burn and the sum is always the value for this burn. Even my rel. velocity changes for exact these amount of dV. So why is there always a small amount of dV left?

**Comment by ArSn** [comment]
I am starting to look into this issue but can not assign it to me. Please refrain from looking into it yourself so we can avoid double work effort. Merci :)

**Comment by ArSn** [comment]
Please see pull request #327 for my solution. Request for comments and testing here!

**Comment by Peppie23** [comment]
staged into v1.7
