### ISSUE TITLE
v1.6 Current release Notes

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#263]
To keep in mind what we've done.

# Flightcomputer
- added a new button to the manuel delay field to set the manuel delay
- added a new button to every queued command to set the manuel delay right after the queued one
- added tooltips for both new buttons
- Save/Restore Flightcomputer values and commandqueue
- Queued commands now in chronological order
- Flightcomputer will be closed after switching the vessel
- The altitude buttons are no longer toggle buttons. To deactivate the current mode please use the small 'X' on the queue-window by the activated command.

# General
- added a mouse over tooltip to the antenna target window to show distance, status to the target
- added configs for AIES, Lack Luster Labs, Near-Future Spacecraft, and NovaPunch
- Possibility to hide ground stations with the new property `HideGroundStationsBehindBody`
- Hide RT windows/overlays when the GUI is hidden
- Saves the window positions from FlightComputer and AntennaWindow (only for the current ksp instance)

# Contributors
- We removed the dependency to the task extensions

# Modders
*Info* We refactored the namespace definitions of remotetech. The API class is no longer on the `RemoteTech{}` namespace. Please use `RemoteTech.API` for now.

- RTSettings now reads settings from the GameDatabase to tweak settings for specific mods ([new Syntax](https://www.dropbox.com/s/fgpuc7ih3urdl0l/RemoteTech_Settings_NewSyntax.cfg?dl=1))
- Possibility to tint groundstations with the property `MarkColor` `Syntax is R,G,B,A`

# Bugfixes
- Fixed the thrust calculation for flamed out engines
- Dishes will now attempt to connect to all targets within their field of view
- Cones now display for any target
- Some refactoring and small fixes
- Keystrokes will no longer go through if the input is focused (fix for linux user)

**Comment by Peppie23** [comment]
@erendrake i would like to release v1.6 soon, i think we've enough and really good features for this version. So i'll move the tasks: #267, #148, #120, #119, #73 and #31 to the next (v1.7). We'll merge your current pr #278 and than start testing of v1.6

What do you mean?

**Comment by erendrake** [comment]
Release like you vote. early and often. I say lets feature freeze and start testing :)

**Comment by Peppie23** [comment]
ok i think we're almost done with v1.6. The only one thing i've noticed is that the new TargetInfoWindow is a bit sluggish but i'll fix that until tomorrow

**Comment by erendrake** [comment]
I am still trying to reproduce the bug getting config values. I would like
to get it in but we can always release again!
