### ISSUE TITLE
Hide the Flight Computer window when F2 pressed

### ISSUE THREAD

**Issue by madadam** [RemoteTechnologiesGroup/RemoteTech#279]
This is minor, but it would be nice to hide the Flight Computer window when the users presses F2, just like the rest of the GUI.

**Comment by Peppie23** [comment]
Duplicate to #49 and currently merged into v1.6 ([Release Notes](https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/263)) I Need some help to test v1.6 before i can release, if you want https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-1.6.0-196
