### ISSUE TITLE
Allow antennas to be reconfigured when out of signal

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#28]
Original issues at Cilph/RemoteTech2#208 and Cilph/RemoteTech2#220.

macdjord wrote:
> In previous version of RemoteTech, it was possible to activate, deactivate, or retarget an antenna even if you had no connection. This was a very useful feature...
> 
> I therefore propose that this ability be restored. Due to its unrealism, it should be optional, perhaps controlled via an option in the config file like signal delay is.

**Comment by neitsa** [comment]
This was added in 240b085 (#494), more precisely [here](https://github.com/RemoteTechnologiesGroup/RemoteTech/commit/240b0853c572f215dd7839583b733586b3f89bca#diff-bd8501d53e0e63c2f7fc88896ef454dfR450). Closing the issue.
