### ISSUE TITLE
Art License Qutesion

### ISSUE THREAD

**Issue by Pharylon** [RemoteTechnologiesGroup/RemoteTech#280]
> The art assets are not licensed to the general public and may not be redistributed without permission from their original creators.

The above is from the download. So, who are the original creators and what do they have against open source? :) While the rest of RemoteTech is licensed under the GPL, and that's awesome, excluding the art assets from the license functionally makes it MUCH harder to fork or be picked up by future developers if the current ones lose interest or get hit by a train. It's not really free software anymore. 

I ask because I myself am a programmer by trade. I sling C# for The Man 40 hours a week. Now I'm thinking of getting into KSP modding some, but I want to contribute to a truly free project. This is kind of a sticking point for me... so what's up with the non-free art?

**Comment by erendrake** [comment]
This Github Organization has permission to distribute the art, i don believe the art decision was up to  someone who is long gone from the project and we cannot change it or contact that person. If you would like to contribute that is great and we would be happy to add you to the organization.

You are right it is harder to fork and redistribute the art but it has not been a big deal for us so far.

**Comment by erendrake** [comment]
I am not sure what else we can tell you about the art assets, they are not and have never been in the ownership of this organization.
