### ISSUE TITLE
Custom +/- buttons take immediate effect

### ISSUE THREAD

**Issue by madbadger2742** [RemoteTechnologiesGroup/RemoteTech#283]
I would like to request that the + and - buttons on the FC panel take immediate effect in Custom orientation mode.   
I feel that behavior would be more intuitive than the current.

**Comment by jdmj** [comment]
IIRC, was discussed a long time ago, Cilph didn't like it: if there's a long enough signal delay, it would flood the command queue.

**Comment by erendrake** [comment]
@madbadger2742 i assume you are playing with signal delay off? I can see a case for doing this for players with this setting off but i am not sure if we want to start diverging on this setting everywhere in the code. 

@Peppie23 what do you think?

**Comment by Peppie23** [comment]
First, i thought this is a really good idea. I also use the custom-attitude for a nice ascent, but jdmj's example is a main disadvantage for this feature.

If we control this feature with a settings flag (enable signal delay) will cause that if you switch that property you think you can use this feature. (confusing sentence)

My suggestion for this feature would be:
- if you use the mouse wheel over these inputs you can increase or decrease the value (but you've to click on custom to set the new value)
- i'm not sure if you can do this already but, hold the + or - button for constant increase/decrease

What do you think?

**Comment by madbadger2742** [comment]
I play with delay on.  :)  
jdmj is right that it would flood the queue and cause issues for someone setting custom attitude within an appreciable delay.  If the average user actually uses them like that, this suggestion would be counterproductive, and should be ignored.  
  
This idea arose because I never use the +/- buttons .  In a stable situation, I generally have time to calculate and input the numbers I want; and when I would like to be able to use the buttons, e.g. ascent, they're just too clunky and slow to be effective.  
I do like the idea of using the scroll wheel within the text boxes, though I probably wouldn't use it.  :)

**Comment by Peppie23** [comment]
Merged into 1.7
