### ISSUE TITLE
RT Specific contracts

### ISSUE THREAD

**Issue by leftler** [RemoteTechnologiesGroup/RemoteTech#289]
After reading issue #273 I realized there is no item in the backlog for Remote Tech specific contracts, so here it is.

Some thoughts on the types of contracts after pondering about this for a few minutes:

 - We don't need "Go put a satellite in orbit" contracts, .90 does that for us. However we still may want to put our own in so to increase the weight of the contract and make it show up more often or perhaps to add requirements like "Put a satellite in orbit with these parameters with this specific antenna on it"
 - Make a "Remotely control a satellite in the SOI of X" style contract. Fairly simple, it is a contract that checks that a satellite is in a specific SOI and `API.HasConnectionToKSC(satGuid)` returns true.
 - Make a "Create a command station (In orbit of|Landed on) X" contract.

Anyone have any other ideas for types of contracts?

**Comment by leftler** [comment]
Ohh, thought of another. "Remotely land a probe on X". With signal delay this could be quite a challenge without a nearby command station.

**Comment by mmermerkaya** [comment]
This addon adds some great RemoteTech contracts: http://forum.kerbalspaceprogram.com/threads/106580

**Comment by neitsa** [comment]
As @mmermerkaya says. Closing as @jrossignol is doing this better than us in its [contract pack for RT](https://github.com/jrossignol/ContractPack-RemoteTech) (I use this contract mod and it's really great).
