### ISSUE TITLE
Relay not working properly

### ISSUE THREAD

**Issue by diego-XA** [RemoteTechnologiesGroup/RemoteTech#293]
I am having a problem with relay.
I have this satellite orbiting the Mun. It has a dish and an omnidirectional antena. Both active. It is connected through the dish to Kerbin relay network.
![screenshot10](https://cloud.githubusercontent.com/assets/644696/5702475/126be25a-9a5b-11e4-9c10-794e37892852.png)

So this satellite should be available as a relay, but it is not working. I've sent another probe with an omnidirectional antena and, when it is in range, a link is shown (in white) but this probe has no connection.
![screenshot9](https://cloud.githubusercontent.com/assets/644696/5702490/425d926a-9a5b-11e4-8450-e8dd57890c13.png)

My guess is that there is a problem with the relay. I've used remotetech before and if I remember well this configuration used to work. Am I missing anything?

**Comment by Peppie23** [comment]
What are the targets of your sats on kerbin? Maybe `Active Vessel`?

**Comment by diego-XA** [comment]
It is not active vessel as the Satelite on Mun has connection. :(

**Comment by madbadger2742** [comment]
In the second picture, your relay sat has connections to the other two, but does not show a connection to Kerbin.  I am betting that the connection you're getting in the first picture is relying on `Active Vessel` targeting from your Kerbin network.

**Comment by diego-XA** [comment]
Yes, my Kerbin network has dishes with "Active Vessel". So the mun sat is pointing to Kerbin and having connection but it also nas an omnidirection antenna. Why is the relay not working with the otter vessel having an omnidirectional antenna?

**Comment by diego-XA** [comment]
OK, I am sorry, I've jus tested pointing the dish antennas directly and it worked. I think this worked before but anyway, it looks like it is the expected behaviour so it is not a bug. Sorry for the confusion.
