### ISSUE TITLE
Incompatible with RSS

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#298]
Javascap wrote via pm:
> When Remotetech 2 is installed on a RSS modified game, somehow, the image files for RSS do not load, leaving black squares over locations where spaceports are. Bug does not seem to be an issue on the RSS side, and RSS worked fine with an older version of Remotetech 2.

Before i released v1.6 i've tested this release with my RSS (R0 via CKAN) and i got no errors.
@pjf do you get any Errors like that with remotetech on your installation?

**Comment by NathanKell** [comment]
I have never seen this. Sounds like an ATM or DDSLoader issue.

**Comment by Peppie23** [comment]
ok. So i'll close this for now and we can reopen it when someone got an issue related to this. Thanks
