### ISSUE TITLE
Lost connections on undock/decoupling

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#3]
Original issues at Cilph/RemoteTech2#120, Cilph/RemoteTech2#134, Cilph/RemoteTech2#233.

Not to be confused with the [active relay "bug"](https://github.com/Cilph/RemoteTech2/wiki/FAQ#why-do-i-lose-my-connection-when-undocking-two-ships), as this issue also affects omnidirectional antennas.

Vranir wrote: 
> Notice on "untitled" ship and "test2" that not only do the dishes lose connection but also no connection is established on omni antennas between the separated stacks.

Cilph wrote: 
> Definitely seeing something here. My rewrite of the log system definitely shows that both Com Stn I and Test 2 have the correct connection to one another, but there is no link being made despite the distance being more than valid. 

Techjar wrote: 
>  If I go back to the space center then go to the tracking station, it works for a moment then freezes. The freeze does not happen if I don't decouple the rover, however.

Resender wrote: 
> Well the conclusion is when dealing with the dishes,they have to be paired up.
If the pair gets broken up,by one directing to a new target but the other still pointing at the partner the freeze happens if the distance is long enough.

rpayne88 wrote: 
> When I track the booster, it doesn't have a connection, yet the CM a mere 50m away does have a connection to the ground. I've even changed the antenna range to 10Mm and it still doesn't connect.

**Comment by Peppie23** [comment]
I think we can close this issue. I fixed the ksp freeze and the unloading/reregister issue. We'll open a new issue if someone get this again.
