### ISSUE TITLE
Weird dish cones drawing

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#301]
Gaiiden wrote on the forum: ([link](http://forum.kerbalspaceprogram.com/threads/83305-0-90-0-RemoteTech-v1-6-0?p=1666535&viewfull=1#post1666535))

> ... when I view the dish cones this is what I'm getting:
> ![0pwlywg 1](https://cloud.githubusercontent.com/assets/7722222/5788481/7adee7c0-9e38-11e4-93f2-949cc10d820b.png)

And he wrote: ([link](http://forum.kerbalspaceprogram.com/threads/83305-0-90-0-RemoteTech-v1-6-0?p=1668377&viewfull=1#post1668377))

> Edit: Nevermind, I had some spare time so I threw up a satellite in a test save and saw a proper cone so I compared the MODULE properties and found that RTDishRadians has been changed to RTDishCosAngle. A simple Find/Replace All and I'm back in business now.

**Comment by Peppie23** [comment]
I got a save file by orangewarning from the ksp forum: https://www.dropbox.com/s/6n04gqirflpr83g/orangewarning.zip?dl=1

![mukteqn 2](https://cloud.githubusercontent.com/assets/7722222/5944393/e8bb82d4-a726-11e4-81dd-c6fca089f6f4.png)

**Comment by Peppie23** [comment]
ok i got some time to look into orangwarning's save game. The problem here is more a misunderstanding of the interplanetary dishes. Using the 450Gm antenna on kerbins soi will cause that you'll see only a straight line instead of a cone. The problem is the distance. The cone is on the top of the 450Gm and not by a distance like 90Mm (Mun/Minmus)

**Comment by orangewarning** [comment]
Hi. I don't think that is the main problem. As you can see, I have my 88-88 pointed at Mun and Minmus and the Reflectron GX-128 pointed at duna. I didn't provide a screenshot for it but it is the same when I point it at Jool.

**Comment by KSP-TaxiService** [comment]
Closing this issue as Peppie23 was correct on the "straight" dish cone. The dish cone of a longer-range interplanetary dish is shrinking (as low as 0.005 degree of GX-128!)
