### ISSUE TITLE
Adding KAC support

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#304]
Hi,
i would like to have a small button for direct adding a new alarm to kerbal alarm clock. Since we've released v1.6 you have to fly the programmed satellite for a Burn/ManeuverCommand.

I imagine a new button called "options", on every queued command as you can see on my "scribble"
![scribble-1](https://cloud.githubusercontent.com/assets/7722222/5788888/1a8db6fc-9e52-11e4-803b-b52ba5b9503e.png)
By clicking the button we'll open a new window with some options. If you have KAC installed we can display a button for direct adding a new alarm.

We also can use this button for options in the future. The option button should not be displayed if we have no options or, for this example, you have no KAC installed.

What do you think?

Edit: As i can see, jdmj has already mentioned it on #123

**Comment by DaveTSG** [comment]
It's certainly a good idea. :)

**Comment by Peppie23** [comment]
I've implemented this feature a bit off from my scribble. An option list button with only one option is a bit to much. If you plan a Burn/ or ManeuverCommand the flightcomputer will add an alarm to KerbalAlarmClock 3m before the command will be executed.

This option can be toggled via the option Screen.
