### ISSUE TITLE
Bug: When starting an EVA and switching Control the FlightComputer sometimes throws NullReferenceExceptions

### ISSUE THREAD

**Issue by ArSn** [RemoteTechnologiesGroup/RemoteTech#309]
I do have a savegame where I can reproduce the following reliably (please note that I also use Kerbal Engineer Version 1.0.14.1, but this should not be related to that):

1. switch to current target
2. start EVA from that target
3. select vessel from point 1. as new target

After doing this, I can not press any buttons in my interface anymore. The debug console shows the same content over and over again:

![image](https://cloud.githubusercontent.com/assets/2803693/5794707/5963d5fe-9f7a-11e4-8c03-d5009da0e4c3.png)
(some debug output included)

When opening the FlightComputer and closing it again, the issue disappears.

:exclamation: I already found a solution for that and will post a pull request shortly. Hence, this issue is merely for proper documentation.

**Comment by Peppie23** [comment]
I also can reproduce this issue when one command is on the queue and the flightcomputer is closed while the queued command will popped.
