### ISSUE TITLE
Linux: Hang in tracking station after separating craft

### ISSUE THREAD

**Issue by beheh** [RemoteTechnologiesGroup/RemoteTech#312]
After separating a satellite from it's booster in Duna orbit (via Docking Nodes), I switched to the craft using the ingame map view (clicking "Switch to vessel" or similar).
The flight computer then didn't to respond to any input, controls like Toggle RCS or SAS didn't appear in the timeline.

After returning to KSC and opening the tracking station the Game freezes indefinitely after a second or two, but without a crash.

Running on Linux with version 1.6.1 (it also happenend in 1.6.0 previously).
[Here is the persistent.sfs](http://stuff.beheh.de/ksp-hang/persistent.sfs) (this corrupted save always hangs on me when opening the tracking station).

**Comment by Peppie23** [comment]
Hi @beheh ,
thanks for your Report. Can you please share your ksp.log right after you had this issue. Thanks :)

**Comment by beheh** [comment]
Hi there, here is the log file: https://gist.github.com/beheh/393ac16868ce7b97300b.

I've also uploaded the non-corrupted save and detailled steps to reproduce:

1. Load http://stuff.beheh.de/ksp-hang-pre-corrupt/persistent.sfs (different from the one above)
2. Open Tracking Station
3. View vessel "DunaSat I" (last vessel)
4. Decouple coupling node between satellite and booster stage
5. Wait for 40s transmission delay (I fast forwarded it)
6. Switch from satellite focus to booster focus by opening map, clicking on Booster and selecting "Switch to"
7. Observe that inputs like "Toggle RCS" and "Toggle SAS" don't appear in the flight computer after pressign the corresponding button
8. Return to KSC
9. Open Tracking Station
10. Observe infinite hang after roughly 1 second

**Comment by Peppie23** [comment]
Hi @beheh ,

can you please try to reproduce your issue with this version:
https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-master-245

the root cause of this problem is maybe #313

**Comment by beheh** [comment]
Hi, thanks for the quick response. I tried that build but couldn't see any difference. The save from http://stuff.beheh.de/ksp-hang/persistent.sfs still hangs when opening the tracking station and retrying the steps from my previous comment led to the same result (and the mentioned broken Flight Computer).

**Comment by Peppie23** [comment]
Also verified this issue with Version 1.6.0, 1.5.2 and your save http://stuff.beheh.de/ksp-hang-pre-corrupt/persistent.sfs

@beheh Point 7: You don't see the RCS Command because the open flight computer is from the undocked satellite. If you click on the flightcomputer button to open a "new" computer after switching you will see your 40s delay rcs command.

After a while i got this, and i only use a fresh copy with remoteTech:
![clipboard05](https://cloud.githubusercontent.com/assets/7722222/5842748/adf1110c-a1a7-11e4-94d6-c5c6bb9c7cc4.png)

Thats bad :/

**Comment by Peppie23** [comment]
oh now i know where i've seen this issue before. Same like #139

**Comment by Peppie23** [comment]
@beheh i've compiled a new version. Please try to use this version https://www.dropbox.com/s/j0ipf4x328wn6lp/RemoteTech-1.6.2-prereleasev2.zip?dl=1

;)

**Comment by beheh** [comment]
Works for me :+1:

When loading my save, I had an "Unknown target" set for my Mun probe communicating, so it seems to have lost it somehow, but I could reset it to the probe. Thanks for the quick fix!
