### ISSUE TITLE
Contracts vanishing

### ISSUE THREAD

**Issue by radinator** [RemoteTechnologiesGroup/RemoteTech#316]
I did a CKAN update in my current career game, which included RemoteTech (1.60 -> 1.61) and several other packages including Contract Configurator.  Immediately noticed that most of the my contracts disappeared (there were more available, but several active vanished and history went blank). At first I thought it was Contract Configurator, but on that forum thread someone mentioned reverting to RT 1.6.0 and it fixed their problem.  I did the same and problem immediately fixed.
I can't say that RT by itself was the cause of the issue, though (since I don't see many other reports). There my be an interaction between RT 1.6.1 and something else.  All that I know now is that reverting to 1.6.0 fixed the issue.  Since there was no crash, I have no log file to supply.  I just wanted to make you aware of a possible interaction issue.
[Just looked at the CC forum thread, and someone mentioned it may be the CC Remote Tech pack.]

**Comment by jrossignol** [comment]
The problem was with Contract Configurator and was fixed in [0.5.8] (https://github.com/jrossignol/ContractConfigurator/releases/tag/0.5.8) (which would've been released right around the same time you opened up this issue.

**Comment by Peppie23** [comment]
@jrossignol thank you :+1:

**Comment by Peppie23** [comment]
@radinator can you please try to revalidate this issue with Contract Configurator v0.5.8 and RemoteTech https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-master-247

thanks

**Comment by jrossignol** [comment]
Actually, because of the assembly change I made, I expect that combination will fail. :cry: When you guys release 1.6.2 I'll have to re-release Contract Configurator (because the AssemblyVersion changed).  But for all 1.6.x releases after that, I'll only have to re-release if there's a legit change that requires it.

Contract Configurator 0.5.8 and RemoteTech 1.6.1 should work together though.

**Comment by Peppie23** [comment]
I'll close this. Please reopen if you still get this issue.
