### ISSUE TITLE
Save/Restore flight computer plan when jumping between ships

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#32]
Original issue at Cilph/RemoteTech2#216.

mellon85 wrote:
> It would be great if the flight computer would "remember" the action to be taken even when there is a ship change. The actions would then be executed only if the ship is the target at the time they should be executed, and maybe dropped in case the focus arrives too late?

**Comment by Peppie23** [comment]
@JDPKSP can i use your code? I would like to see this feature in 1.6 too :)

**Comment by JDPKSP** [comment]
sure thing @Peppie23, steal away :smiley:

**Comment by Peppie23** [comment]
thanks ;-) i'm almost done with this task, based on your code. Only the 'BaseEvents' are not saved properly but maybe tomorrow i'm done with this

**Comment by Peppie23** [comment]
oh man ... i'm done! Really thanks for your initial job :sparkles: :tada: :tada:

**Comment by Peppie23** [comment]
Merged into v1.6
