### ISSUE TITLE
Command Station Not Transmitting

### ISSUE THREAD

**Issue by folshost** [RemoteTechnologiesGroup/RemoteTech#338]
I have multiple command stations, each with the RC-l01, and at least seven kerbals, and when they are the active vessel, they (most of the time) show themselves to be command stations, with the red dot. However, whenever they are not the active vessel, they register as ordinary vessels, and do not transmit.
In step form:
1. Fly the base or station that should function as a command station.
2. Note the red dot, and yellow lines extending to the tageted probes.
3. Switch to probes.
4. Note the lack of connection, no red dot on command station, and brownish lines connecting the two.

Mods:
Kerbal Attachment System 
NEAR 1.3.1
Near Future Solar
Scansat 8.1
Dmagic Orbital Science .91
RLA stockalike
Procedural Fairings
Engineer 0.6.2.12
Planetshine
Remotetech (obviously) 1.6.2

![image](https://cloud.githubusercontent.com/assets/10580462/5985492/98258f1c-a8a8-11e4-9bb1-d44354744014.png)
![image](https://cloud.githubusercontent.com/assets/10580462/5985499/b09703aa-a8a8-11e4-8645-0405eda6b12d.png)
![image](https://cloud.githubusercontent.com/assets/10580462/5985503/bda07298-a8a8-11e4-9116-66ab57fe1f96.png)

Persistent save file:
file:///C:/Program%20Files%20(x86)/Steam/SteamApps/common/Kerbal%20Space%20Program/saves/Part%201/persistent.sfs

**Comment by Peppie23** [comment]
Hi @folshost,

thanks for your report. :+1: Something is wrong with your savefile. Please upload your savefile to your git.io or to any space like dropbox. I also need your log file. (you can find the log on your ksp root, named: ksp.log)

Btw. Can you also try to reproduce with our current prerelease:
https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-master-272
I fixed a station issue in this.

**Comment by folshost** [comment]
Yeah, one time, I was trying to land on eve, and was time accelerating in atmosphere when my parachutes deployed, which destroyed the probe, and the whole mission that it had been sent inside. My save has done weird things since, like randomly deleting half of my com-sats around kerbin. I have also had weird issues with sats that get launched into solar orbits that, when attempting to fly them from anywhere really, they cause weird graphical issues. But I suppose those may be beside the point. 
Save File
https://www.dropbox.com/sh/h700gmbgq86j02a/AADLyXxO7ZWWrAwj3lQqORf_a?dl=0
Ksp.log
https://www.dropbox.com/s/bx9ubpciho78cp1/KSP.log?dl=0

I did manage to reproduce the issue with that prerelease

**Comment by Peppie23** [comment]
@folshost thanks. I can reproduce your problem. For your "graphical issues" please make a screenshot that i can see your problem and i also need your ksp.log right after this error. 

btw. the ksp log will finally wrote if ksp is closed. Please reproduce your error, make a screenshot, close ksp and than send the ksp.log.

**Comment by Peppie23** [comment]
ok you've the "getInt" problem.

> ProtoSignalProcessor System.ArgumentException: No integer 'RTCommandMinCrew' in ProtoPartModule
Parameter name: value
  at RemoteTech.RTUtil.GetInt (.ProtoPartModuleSnapshot ppms, System.String value) [0x00000] in <filename unknown>:0 
  at RemoteTech.Modules.ProtoSignalProcessor..ctor (.ProtoPartModuleSnapshot ppms, .Vessel v) [0x00000] in <filename unknown>:0

**Comment by Peppie23** [comment]
@erendrake maybe you can help me to find a solution for this issue.

The `getInt` exception occurs if we try to get the `RTCommandMinCrew` value on a `ModuleSpuPassiv` but we have no `RTCommandMinCrew` on these Modules. I guess the problem is here: [SatelliteManager.cs#L223](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/SatelliteManager.cs#L223) we only use the first `SignalProcessor` from the list, but what if the first Module is a dish?

I removed the return line to see what our query will select and there are 7 Modules. 6 ModuleSpuPassives and one ModuleSpu. The `GetSignalProcessor` will only be called on the `RegisterProto` Method. [SatelliteManager.cs#L117](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/SatelliteManager.cs#L117)

Should i try to look for a ModuleSpu and if we've no i'll use the first ModuleSpuPassive?

**Comment by Peppie23** [comment]
It looks good for me if i add a extra condition with `ppms.moduleName == "ModuleSPU"` this also would fix the Depri-Sats on the AntennaFragment if thay have no ModuleSPU

**Comment by folshost** [comment]
I couldn't reproduce the graphical issues. I guess the best I can do is describe them better. I had several satellites on polar orbits as per the contracts given for them, and, as best as I can guess, the Mun launched them into solar orbits. When I first went to look at them there, they were initially rendered, but then vanished, and I think the environment went black, and when I went to ksc, I think there was just the scaled space/skybox rendering of kerbin(all blue, and then black at Kerbin's core).
But when I left, and reloaded the game, it functioned fine. It's only happened like two or three times. It's not a consistent problem.

**Comment by Peppie23** [comment]
hmm ok, the extra condition with `ppms.moduleName == "ModuleSPU"` causes that manned vessels with an antenna will not reregistered after unloading or by the mapview.
> Should i try to look for a ModuleSpu and if we've no i'll use the first ModuleSpuPassive?

Maybe this is the best way. Try looking for an ModuleSPU otherwise we will look for the first ModuleSPUPassiv

**Comment by ACReeser** [comment]
Looks like that's the root issue for issue #232, which lead to #270, which lead to #276.

**Comment by Peppie23** [comment]
@folshost and @ACReeser can you please confirm the fix with our current prerelease:
https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-master-279

thanks

**Comment by ACReeser** [comment]
@Peppie23 I will ASAP

**Comment by folshost** [comment]
It does indeed work. All three of my command stations are functional without having to be operated directly.
![image](https://cloud.githubusercontent.com/assets/10580462/6029175/6224fab0-abb4-11e4-883a-2e743742728f.png)
![image](https://cloud.githubusercontent.com/assets/10580462/6029193/7dbca52a-abb4-11e4-9f2a-7e7ce12aea09.png)
Thanks guys!

**Comment by Peppie23** [comment]
thanks for your detailed report ;-)

**Comment by ACReeser** [comment]
Works beautifully! Thanks @Peppie23 for the fix.
