### ISSUE TITLE
LLL antennas ranges inversed

### ISSUE THREAD

**Issue by DeepSilence** [RemoteTechnologiesGroup/RemoteTech#339]
Hello, 

I have noticed the two LLL communtrons have their ranges inversed, due to a typo in RemoteTech_LLL_Antennas.cfg.
The correct config  is : 

[...]
// Communotron 64
// Same mass as LLL's Communotron 32
@PART[LLLCommPole]:AFTER[LLL]:NEEDS[RemoteTech]
{
[...]

**Comment by erendrake** [comment]
@deepsilence would you mind making this change into a pull request for us
to review?

**Comment by Peppie23** [comment]
I've seen that Lack added his own RemoteTech.cfg to his download package. I suggest to delete our config for LLL.

**Comment by Peppie23** [comment]
I'll close this issue.
