### ISSUE TITLE
Roll shouldn't be fixed during manuever node

### ISSUE THREAD

**Issue by Iamtk421** [RemoteTechnologiesGroup/RemoteTech#340]
This is possibly more of a feature request than a bug report, but it'd be nice if when using the flight computer to adjust attitude towards 'node' it ignores roll and keeps it fixed at whatever it currently is.

As it stands I keep running into issues with my solar panels being oriented incorrectly and unable to get any sunlight as the craft insists on rolling back to some default orientation rather than the one I've set to. I can't see any reason why roll should be fixed when set to orient to 'node'.

Obviously if I'd stuck the panels on 90 degrees from where I happen to put them it'd be fine, but that's not really helpful once a craft is already in orbit.

**Comment by ArSn** [comment]
I can not see any reason why the roll is currently corrected at all either. Hence, I second the move to change this behaviour as requested by @Iamtk421

**Comment by Gaiiden** [comment]
thirded. I've been annoyed by the exact same scenario

**Comment by parachutingturtle** [comment]
I agree, this can be really annoying if your craft relies on solar power.
