### ISSUE TITLE
Yet another "station stops transmitting on unload" issue

### ISSUE THREAD

**Issue by wisq** [RemoteTechnologiesGroup/RemoteTech#345]
Okay, so I don't know if this is related to #338, and/or my previous report #232, but this one seems to be more severe than either of those — it involves the unloaded ship losing all RemoteTech capabilties altogether, not just the status as a command base.

Sequence of events:

1. Fire up KSP, load savegame, tracking station, open my space station
2. Build and launch a new unmanned ship using ExtraPlanetaryLaunchpads
3. Pilot that ship until I get far enough from the station for it to unload
4. Station is *no longer transmitting whatsoever* — no red dot, no communications lines

Other notes:

* RemoteTech 1.6.3 from CKAN (verified in logfile), which, to my understanding, includes fixes for both the above issues
* doesn't happen if I load the station and then switch to another ship
* doesn't happen if I load the station, build a new ship, and then switch to another ship
* log is being spammed with "-1" over and over, but I have no idea what mod is doing that
* no mention of "GetInt" in the log

Files:

* KSP.log: https://dl.dropboxusercontent.com/u/32378574/remotetech-unload-KSP-log.zip
* Savefile after testing: https://dl.dropboxusercontent.com/u/32378574/remotetech-unload-KSP-sfs.zip
* Video of reproducing bug (producing files above): http://youtu.be/I0jiufszGsI (sorry, my voice is very quiet and ShadowPlay was being stupid with the push-to-talk)
* Craft I was testing with: https://dl.dropboxusercontent.com/u/32378574/remotetech-unload-KSP-crafts.zip

Let me know if you need anything else.  It's not a huge problem for me right now since I can just switch back to the station and back to my ship again if necessary.

**Comment by SirDiazo** [comment]
Note I have not actually loaded this issue to look at it, but I would suspect how EL spawns ships is the culprit.

When you build an EL ship, the ship spawns as a standalone vessel that once initialized immediately docks to the launch pad that spawned it.

My first guess would be because the vessel exists for such a short time (I'm not sure even a full update has time to happen) that the RT stuff never has time to create it's stuff on the vessel before it docks to the launch pad and becomes part of the launch pad vessel.

**Comment by wisq** [comment]
Interesting.  But if that were the case, wouldn't it be that the launched ship's communications would be what fails, rather than the station's?  Unless the error shifts from the launched ship to the station because of the docking.

Or maybe the EPL "release" system doesn't properly separate the two — I don't know enough about modding to know if this makes sense, but if there are hooks tied to a vessel / info stored on a vessel record, and there's something that needs to happen when one vessel becomes two (e.g. add a hook to both vessels / recalculate what antennae they have / etc.), and the EPL release system does it in an unexpected way, then RT wouldn't have the hooks / info it needs.

**Comment by SirDiazo** [comment]
As far as I can tell, the EPL release is a standard undock.

Which is why I suspect the initial "load" of the vessel does not complete when it is spawned.

Having said that, I have no clue what the "-1" in the log is, this does nothing to explain that.

**Comment by Peppie23** [comment]
Hi @wisq 
thanks for your report and your detailed video report :+1: Is the mod list from #338 your current mod list?

**Comment by wisq** [comment]
My mod list should still be broadly similar to the one in #232, plus or minus a couple at most.  I made sure to open up CKAN in the video to get the most up-to-date list.

Most recent addition would be Fusebox (http://forum.kerbalspaceprogram.com/threads/50077).

**Comment by Peppie23** [comment]
oh sorry, i skiped the first few seconds of the video. ok, hmm, it looks like that you play with "all" ksp mods :sweat_smile:

I'll try to reproduce ;)

**Comment by wisq** [comment]
Haha, yeah, sorry, I run quite a few. :)  If there's any code you want me to run, or mods you want me to try removing, let me know.

**Comment by Peppie23** [comment]
@wisq how can i fix the high power drain?
![drain](https://cloud.githubusercontent.com/assets/7722222/6202686/108d9f2e-b4f9-11e4-85ea-2ba9e5e64f30.png)

**Comment by Peppie23** [comment]
ok i disabled the RT consumption. But now, after building your 'Inner Planets Probe' i can't move this probe :( do i something wrong? Even if i throttle up the ion engine, i can see that the engine is fireing but the probe doesn't move :(

![screenshot60](https://cloud.githubusercontent.com/assets/7722222/6202820/5a16a5a4-b4ff-11e4-982b-e36441f00851.png)

**Comment by wisq** [comment]
Make sure to use "release" in the ExtraPlanetaryLaunchpads window, otherwise it's still docked to the station.

**Comment by Peppie23** [comment]
jep, i clicked the release button on the EL window. but maybe is this another rt bug ... i'll look closer
