### ISSUE TITLE
All RT satellites disappearing after a load game

### ISSUE THREAD

**Issue by makos** [RemoteTechnologiesGroup/RemoteTech#354]
I had about 10 satellites with RT antennae set up around Kerbin. Loaded that save game today, and the whole network is gone, except other satellites. Other satellites also used RT parts, so it's really weird. I did not install any new mods, remove anything, just started the game as usual. I don't know how to reproduce this bug, since it seems it occured randomly. The last time I played, the game quit without any problems, so I doubt the save got corrupted by that.
The mods I have installed:
AIES Aerospace
Deadly Reentry
FAR
Alarm Clock
Engineer Redux
Joint Reinforcement
Module Manager
Precise Node
Procedural Fairings & Parts (and textures for proc tanks)
SCANSat
TACL
TweakScale
Universal Storage
and of course RT

Anyone else encountered this bug?

**Comment by Peppie23** [comment]
Hi @makos ,
are your satellites disappeared? or only the connection? Do you have a ksp.log after you got this issue?

**Comment by tomekpiotrowski** [comment]
Please re-open if anyone else encounters this.
