### ISSUE TITLE
Is it wrong that it does "Throttling back time warp..." from phys warp too?

### ISSUE THREAD

**Issue by Dunbaratu** [RemoteTechnologiesGroup/RemoteTech#357]
I get the need to do this:

  "[Flight Computer]: Throttling back time warp..."

When you hit a control keypress like "space" for staging and you are currently undergoing (5x, 10x, 50x, 100x and so on) time warp, but what about physics warp (1x,2x,3x,4x) mode?  Is it right that it pops me back out of THOSE too?

Sometimes I like to launch under 2x, 3x, or 4x  phys warp (assuming the rocket is a simple enough design to deal with it without getting buggy physics) for the initial first stage or so, to get past the boring early "go straight up for a bit before tipping over" part.  But I noticed that with remotetech installed if I do that with an unmanned probe, I can't hit spacebar to stage.  Hitting spacebar knocks me out of physics warp instead of staging.  So I have to fall down to 1x, then stage, then I can ALT-> to 4x again, then drop back to 1x for the next stage, and so on.

**Comment by Dunbaratu** [comment]
I know there's a setting to turn this feature off, but that's not what this issue is about.  It's about this: when the feature IS enabled - should it be changed to only apply to "rails" time warp and not physics warp?

**Comment by Peppie23** [comment]
I agree with you. There is no need to cancel the timewarp on phys warp.
