### ISSUE TITLE
[Linux] RCS completely ignores signal delay

### ISSUE THREAD

**Issue by pjf** [RemoteTechnologiesGroup/RemoteTech#362]
I suspect this may be a Linux-specific issue, but it appears that RCS controls (including rotation and translation) completely ignore signal delay. The result is:
1. I can fine-control my craft that's six light-seconds away.
2. I can't schedule my RCS to do ullage just before a manoeuvre node.

I suspect I've seen this reported before, but the closest I can find is #38 , which isn't quite the same.

Many thanks!

~ pjf

**Comment by parachutingturtle** [comment]
from what I noticed, attitude control with even just reaction wheels will work without signal delay. Not sure if this is a known bug or not, but it would be great to have this fixed.

**Comment by pjf** [comment]
@parachutingturtle: On which platform? I assumed this was Linux-only, but if it's all operating systems then the bug's likely hiding in a different part of the code than I expect.

**Comment by parachutingturtle** [comment]
@pjf I'm on Win7 x64 (KSP is 32bit of course), RemoteTech 1.6.3.0 and I just checked and even the throttle controls totally ignore signal delay. Turning SAS/RCS on/off or doing anything on part right click menus works properly with the appropriate delay, it's just the attitude and throttle controls that don't. Is this the same for you?

**Comment by Pharylon** [comment]
This is happening to me, but I've got a bunch of mods and I couldn't reproduce it with a new game. Win7 x65 (KSP in 32 bit mode) here as well.

**Comment by KSP-TaxiService** [comment]
Closing this issue as there are no new Linux-specific report received and the fixes on signal-delay issues were developed and pushed into the codebase.
