### ISSUE TITLE
Queuing spacecraft orientation commands

### ISSUE THREAD

**Issue by DaveTSG** [RemoteTechnologiesGroup/RemoteTech#364]
Hi glorious devs; I have a suggestion. :)

Is it possible to please implement a queue for different spacecraft orientations? At the moment, it seems impossible using the flight computer.

What I specifically want to do is to have the flight computer point to surface prograde during re-entry of a lander, and then I want to queue at (time to periapse plus 2 minutes, via a delayed command) a command to kill rotation.

e.g. I want to have the spacecraft set to SRF prograde during re-entry, then at a time I've guesstimated (which coincides with parachute deployment), it should then switch to kill rotation, rather than prograde. This is so the spacecraft can land autonomously without having control at the time (due to landing when relay satellites are out of range). The problem is, it needs to be on kill rotation otherwise it'll topple itself over when it lands on its legs.

What I'm currently doing:
1. SRF GRD+ (no command delay).
2. Set command delay to roughly 15mins (to have enough time for parachute deployment).
3. Click KILL button to kill rotation.

At this point, instead of creating a new KILL command with a 15 minute delay, it just immediately deletes the SRF GRD+ command and applies the kill rotation command.

I have a separate idea, too, please:

At the moment, when you click the X next to a command to delete it, the deletion happens immediately. Is it possible for the deletion to occur based on the command delay time as well?

So, if I do...

1. SRF GRD+ (no command delay).
2. Set command delay to roughly 15mins (to have enough time for parachute deployment after re-entry).
3. Click the X button to delete the SRF GRD+ command.

Then this should delete the command 15 minutes later, so that the flight computer Mode = Off. (that way, "steering" is controlled by the parachutes and the lander doesn't topple itself over upon landing)

Are these two ideas possible, please?

Thanks in advance.

**Comment by DaveTSG** [comment]
(By the way, the spacecraft I'm controlling is the same one I mentioned in issue #311. :)

**Comment by Peppie23** [comment]
Hi @DaveTSG ,

with task #481 i'm planning a flight computer overhaul. I'll make the "X Button" on the active command also with delay.
