### ISSUE TITLE
Orbit calculation errors causes unstable relay network

### ISSUE THREAD

**Issue by howkong** [RemoteTechnologiesGroup/RemoteTech#367]
There is a serious problem that when I tried to build a relay network around planets other than Kerbin (e.g. Duna, Mun or Minimus) , I found that the orbit period of a satelite wiggles, due to some small errors of the orbit calculation of KSP.
Those small errors prevented me from knowing the exact period of the orbit, causing the relative position of the satelites unstable.
So when I took a trip to Duna, I found that my relay networks around Mun and Minimus have completely become a mess.
The following images are a part of MechJeb's orbit info window. The time between taking the two snapshots is about 1s.
![qq 20150410232558](https://cloud.githubusercontent.com/assets/11898456/7101004/a63c848c-e072-11e4-8d9d-2556313497b3.jpg)
![qq 20150410232605](https://cloud.githubusercontent.com/assets/11898456/7101005/a641b43e-e072-11e4-902b-632d1c8e318d.jpg)
The following is the current status of my mun network. The three marked polar satelites used to be in a perfect regular triangle.
![3h7a3525](https://cloud.githubusercontent.com/assets/11898456/7101018/573635da-e073-11e4-8c4a-acf591e72405.JPG)

**Comment by futrtrubl** [comment]
This is not something that RT can fix as it is a problem with stock KSP. Get it as close as you can and then periodically do maintenance burns like in real life. Or use hyperedit to lock them in to exactly the same orbit when they are on rails.
