### ISSUE TITLE
Antenna field persistence

### ISSUE THREAD

**Issue by futrtrubl** [RemoteTechnologiesGroup/RemoteTech#369]
I've been thinking of making a procedural antenna mod to allow us to modify antennas to our needs using tweakables.
I was going to use my own module to have the tweakables and then use my plugin to modify the fields in ModuleRTAntenna in the editor scene. That way my module wouldn't have to do anything in the flight scene.
Unfortunately for me it looks like the fields I would change (Mode0OmniRange, Mode1OmniRange, Mode0DishRange, Mode1DishRange and EnergyCost) are not persistent.

Am I seeing that correctly? Does that mean your plugin looks for the those fields in the part definition when it needs them and not from the instance of the part?

**Comment by Peppie23** [comment]
Hi @futrtrubl 
thats right. We use the `Mode...Range` values to calculate the range * `RangeMultiplier` from our settings.

We've a value on the `ModuleRTAntenna` module called `RTOmniRange` or `RTDishRange`, these values are persistent BUT on every `FrameUpdate` it will be re assigned with our calculation from above.

Maybe with #272 you can change the distance or with reflections :smiling_imp:

**Comment by futrtrubl** [comment]
My coding knowledge isn't really enough to how to deal with reflections but I will look into it. I was hoping I could just set the relevant fields in the VAB and let RT do the heavy lifting ;']
Though I was also thinking of making an even more realistic gain/received power mode for RT, but I need to check how much root mode deviates from that to see if it is justified.

**Comment by KSP-TaxiService** [comment]
It doesn't seem there is any interest or activity on the tweakables of a RT antenna since 2015. This issue can be re-opened later should there sufficient interest or information provided to move forwards
