### ISSUE TITLE
Add RCS translation controls to the flight computer

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#38]
Original issue at Cilph/RemoteTech2#226.

Grunf911 wrote:
> Could it be possible to add some sort of RCS translation controls (the ones that are keybinded to I,J,K,L, H, and N respectively) to Flight computer
(so we could queue them as regular burns - whether to use sec for duration or m/s is less important)

**Comment by Peppie23** [comment]
I've created a collection of todo's here: #481 and i'll close this one
