### ISSUE TITLE
Reflectron KR-7 dish's attachment point seems upside down.

### ISSUE THREAD

**Issue by Dunbaratu** [RemoteTechnologiesGroup/RemoteTech#390]
(In KSP 1.0.2, using RT pre-release build 325)

I can't get the KR-7 dish to attach so the pointy bit sticks out *away* from the vessel.  It won't attach it, Instead I have to first attach it with the dish pointing inward, clipped inside the vessel, and then use the rotation tool to spin it 180 so it sticks out again.

**Comment by Peppie23** [comment]
The `node_stack_bottom` is defined as 
> node_stack_bottom = 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0

for all dishes/antennas, but it should be:
> node_stack_bottom = 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0
