### ISSUE TITLE
Lab Research Data

### ISSUE THREAD

**Issue by Druaga71** [RemoteTechnologiesGroup/RemoteTech#391]
I am unable to send completed research science from a Lab back to Kerbin.  I am trying to do it from the Mun through one other satellite.  It seems to send the data, counts all the way to 100%, but then it never says it is done nor the science was received.  However, if I remove RT (except for the parts) I'm able to transmit the completed science from the Mun base.

**Comment by Peppie23** [comment]
Remotetech throws an exception while trasmitting data from the lab:

> [EXC 12:32:19.205] NullReferenceException: Object reference not set to an instance of an object
	ResearchAndDevelopment.GetScienceValue (Single dataAmount, .ScienceSubject subject, Single xmitScalar)
	ResearchAndDevelopment.SubmitScienceData (Single dataAmount, .ScienceSubject subject, Single xmitScalar, .ProtoVessel source, Boolean reverseEngineered)
	RnDCommsStream.submitStreamData (.ProtoVessel source)
	RnDCommsStream.StreamData (Single dataAmount, .ProtoVessel source)
	RemoteTech.Modules.ModuleRTDataTransmitter+<Transmit>d__3.MoveNext ()

**Comment by Peppie23** [comment]
The problem is that the `ResearchAndDevelopment.GetSubjectByID(scienceData.subjectID);` on ModuleRTDataTransmitter.cs#L85 returns null on a Lab-transmission, but we need a `ScienceSubject` object on the `RnDCommsStream`.

**Comment by Peppie23** [comment]
It also seems to be that the new callback parameter, who is set for the lab-transmission, injects the complete ScienceData at the end of the transmission. The Callback method is: 
> Callback.Method: OnTransmissionComplete

**Comment by Peppie23** [comment]
btw same with the SurveyScanner
> Callback.Method: CompleteSurvey
