### ISSUE TITLE
90Gm Antenna

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#40]
Original issue at Cilph/RemoteTech2#231.

Starstrider42 wrote:

> It might be worth considering making a 90-100Gm antenna, which would work for Jool but not Eeloo, but which could be used as a cone at closer ranges than either of the current giga-dishes

**Comment by KSP-TaxiService** [comment]
Conveniently, KSP's CommNet has a stock [100Gm dish antenna](http://remotetechnologiesgroup.github.io/RemoteTech/guide/parts/#ra-100-relay-antenna) now. This baby can reach Jool at all times but Eeloo at its periapsis only.

For its cone angle, we can rebalance along with the other antennas during RT 2.x development.
