### ISSUE TITLE
ArgumentOutOfRangeException while loading a cancel command

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#408]
I'm not sure what i've done, but i'll try to reproduce. Only what i can see from the logs is:
> ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[RemoteTech.FlightComputer.Commands.ICommand].get_Item (Int32 index)
	System.Linq.Enumerable.ElementAt[ICommand] (IEnumerable`1 source, Int32 index)
	RemoteTech.FlightComputer.Commands.CancelCommand.Load (.ConfigNode n, RemoteTech.FlightComputer.FlightComputer fc)
	RemoteTech.FlightComputer.Commands.AbstractCommand.LoadCommand (.ConfigNode n, RemoteTech.FlightComputer.FlightComputer fc)
	RemoteTech.FlightComputer.FlightComputer.load (.ConfigNode n)
	RemoteTech.FlightComputer.FlightComputer.OnFixedUpdate ()
	RemoteTech.Modules.ModuleSPU.FixedUpdate ()

Maybe i saved a cancel command while the aborted command is not longer on the queue - because it was the active command.

**Comment by JDPKSP** [comment]
Maybe, just to be safe, it would be a good idea to issue each command a unique Guid ID on enqueue. This way we could make sure that cancel commands will always point to the relevant command across queue reordering, command activation and persistence save/load. We could of course just use the timestamp to identify which command to cancel, but if ever there's a way added to issue multiple commands simultaneusly this would fail (we, for one, cannot predict if any mods using the API could do this)

**Comment by Peppie23** [comment]
thx @JDPKSP for the idea with the guid :+1:
