### ISSUE TITLE
Allow renaming pods and probes without having connection.

### ISSUE THREAD

**Issue by enceos** [RemoteTechnologiesGroup/RemoteTech#409]
There are many occasions when a probe is not needed anymore and a capsule was abandoned behind. Without RemoteTech we could right-click them, push the Rename Vessel button and set as debris. RemoteTech removes that feature when there's no connection.
In reality all these names an types are given by the mission control, and it doesn't matter if there's no connection to that thing.

![Drifting pod](http://i.imgur.com/nfkXSr1.png)

**Comment by Peppie23** [comment]
Hi @enceos ,
this isn't controlled by us. I deleted remotetech and i can't change the name as well.
![clipboard01](https://cloud.githubusercontent.com/assets/7722222/7549396/fc7c6954-f632-11e4-9f1a-f09440d0183e.png)

**Comment by enceos** [comment]
People have told me on forums that this can be done from the tracking station anytime this way:

!(Renaming Vessels)[http://i.imgur.com/2etaJmP.png]

**Comment by Peppie23** [comment]
Also with RemoteTech?

**Comment by enceos** [comment]
Yep, just checked.
