### ISSUE TITLE
Flightcomputer + Hullcam VDS bug

### ISSUE THREAD

**Issue by Rubachabra** [RemoteTechnologiesGroup/RemoteTech#412]
Hello

A satellite i launched has ceased to function after i disabled a camera (Hullcam mod). It is constantly switching the camera between enable/disable and is blocking any other action trough the flightcomputer. The result is that any action is impossible and nothing happens when i try to activate a  part or disable a part, i am roleplaying that the satellite has had a software malfunction, which i guess is not that far from the truth :)

Attached a screenshot, i am using the current version of Remote Tech 2 and the latest version of Hullcam

https://kerbalstuff.com/mod/450/Hullcam%20VDS

![untitled](https://cloud.githubusercontent.com/assets/12386210/7556779/c5d40904-f77f-11e4-8ef3-d05411f56780.jpg)

**Comment by Peppie23** [comment]
I can reproduce this error. Seems to be that we've a problem while executing this event.

> [Exception]: TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
MuMechModuleHullCamera.EnableCamera ()
BaseEvent.Invoke ()
RemoteTech.FlightComputer.EventCommand.Pop (RemoteTech.FlightComputer.FlightComputer f)
RemoteTech.FlightComputer.FlightComputer.PopCommand ()
RemoteTech.FlightComputer.FlightComputer.OnUpdate ()
RemoteTech.Modules.ModuleSPU.Update ()

**Comment by Rubachabra** [comment]
Damn, thanks for the quick response! Hope it's fixable and happy to be able to contrubite (in my small way) by reporting this bug. Love the mod by the way :)

On a side note, is it possible to clear out the flight computer in any way? Just so i am able to save my beloved satellite :) Any help would be apreciated!

**Comment by Peppie23** [comment]
@Rubachabra i also get this issue without RemoteTech, just a fresh copie of ksp, HullCam VDS v0.40 and MM v2.6.3

GameData folder:
![clipboard02](https://cloud.githubusercontent.com/assets/7722222/7594404/b13f1030-f8e0-11e4-840d-f1c1cae8154c.png)

My vessel on the launch pad:
![clipboard03](https://cloud.githubusercontent.com/assets/7722222/7594411/bb8a34b6-f8e0-11e4-8d9b-ec480d106263.png)

This red message always appears if i click on "Disable cam" or "Enable cam". Can someone please confirm this issue _without_ RemoteTech. My log output: https://gist.github.com/Peppie23/f77af78c83e39c7c307d

**Comment by Peppie23** [comment]
Hi @Rubachabra 
i've seen on the Hullcam thread that this is an issue of the hullcam. [Thread...](http://forum.kerbalspaceprogram.com/threads/46365-1-0-2-Hullcam-VDS-Wide-Angle-Camera-Female-Kerbal-EVA-view-Updated-8-May?p=1670654&viewfull=1#post1670654) What i can do is to catch this "exception" that the flight computer will not invoke this Event over and over. So if you use the next dev-build you can switch to your vessel without problems.

**Comment by Rubachabra** [comment]
Thanks :)
