### ISSUE TITLE
RT probes forget queued instructions when you switch away from them

### ISSUE THREAD

**Issue by ToxicFrog** [RemoteTechnologiesGroup/RemoteTech#426]
Title is pretty self-explanatory.

Repro:
- set a maneuver node
- enter NODE and EXEC in the flight computer; observe that the queue now reads "hold maneuver prograde" and "execuet planned maneuver"
- switch to KSC and then back to the probe
- observe that the queue now reads "hold maneuver prograde" only, and "execute planned maneuver" is empty.

**Comment by Peppie23** [comment]
Hi @ToxicFrog , thanks for your report. But sorry if i only copie my answer from issue #424

> yep thats an issue on our current release. So i'll mark this as an duplicate of #403 because we've already fixed that issue.

> Btw. v1.6.5 will be released tomorrow, if you don't want to wait, you can use our current dev-build 378
