### ISSUE TITLE
Store Science Transmissions for later Retransmission

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#43]
Original issue at Cilph/RemoteTech2#243.

AJMansfield wrote:

> Could you add the ability for a command stations (or probes) that are out-of-range of KSC to receive science transmissions and re-transmit them once KSC is back in range?

**Comment by KSP-TaxiService** [comment]
Closed as this functionality is now supported by the new science part, Experiment Storage Unit, introduced in KSP 1.2
