### ISSUE TITLE
EVA radio

### ISSUE THREAD

**Issue by Sigma88** [RemoteTechnologiesGroup/RemoteTech#438]
This is a feature request but I'm not sure how to flag it as such (sorry I'm still new to github)

Sorry also for the long post, I didn't plan on it being so big

- Feature:
Adding an omni antenna to a kerbal during EVA and making it balanced with RemoteTech

if balanced correctly I think it could be a cool addition, some experiments can be done multiple times and will give you 100% science when transmitted. In that case you won't need to go back and forth to the ship but you can send the science from your kerbal (if you have a network connection).

as for balancing I think this points should be taken into account:

- TechLevel
- Range
- ElectricCharge

This is an example of what I think could work:

First Upgrade:
              TechLevel = Space Exploration
              Range = 300 m
              ElectricCharge = 50 units

Second Upgrade:
              TechLevel = Advanced Exploration
              Range = 1000 m
              ElectricCharge = 75 units

Third Upgrade:
              TechLevel = Science Tech
              Range = 3000 m
              ElectricCharge = 100 units

The last upgrade is on the same tech tier than the probe core upgrade and has the same antenna, I feel this is important for balancing to avoid people going EVA just to get a better antenna.

I am not sure about science/electricity ratio.

Finally: I'm aware there are other mods that allow this feature to be added to remote tech, but I feel like the solutions those mods give are not balanced.
Using EVA_manager from toadicus I already managed to get an antenna module into an EVA kerbal and it works nice, but that doesn't allow for a techtree integration.

**Comment by Peppie23** [comment]
Hi @Sigma88 ,

thanks for your post but it's duplicate :smiling_imp: #5

**Comment by Sigma88** [comment]
derp! my bad, I probably didn't find it in my search since it's closed

btw I did know about the science container but I thought it wasn't really balanced with RT, maybe I should write this to them then

**Comment by Peppie23** [comment]
so we can close this issue here?

**Comment by Sigma88** [comment]
yeah sorry I didn't know I could have closed it myself :)
