### ISSUE TITLE
Unable to transmit experiment data

### ISSUE THREAD

**Issue by phwoelfel** [RemoteTechnologiesGroup/RemoteTech#439]
I've seen it happening on thursday on KSPTV (Convieo's In-Con-ceivable Catastrophes) and now it happend to myself. Sometimes I'm unable to transmit the science data from an experiment. The data is removed from the experiment but nothing is transmitted. I got following error in the output_log.txt:
```
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.MonoBehaviour:StartCoroutine_Auto (System.Collections.IEnumerator)
  at UnityEngine.MonoBehaviour.StartCoroutine (IEnumerator routine) [0x00000] in <filename unknown>:0 
  at RemoteTech.Modules.ModuleRTDataTransmitter.IScienceDataTransmitter.TransmitData (System.Collections.Generic.List`1 dataQueue) [0x00000] in <filename unknown>:0 
  at ScienceAlert.MagicDataTransmitter.BeginTransmissionWithRealTransmitter (IScienceDataTransmitter transmitter, System.Collections.Generic.List`1 science, .Callback callback) [0x00000] in <filename unknown>:0 
  at ScienceAlert.MagicDataTransmitter.Update () [0x00000] in <filename unknown>:0 
```
This is probably related to Science Alert (http://forum.kerbalspaceprogram.com/threads/76793) as seen in the error. I've also posted in the Science Alert thread.
output_log.txt: https://www.dropbox.com/s/zhjkwyjvmvy0kvi/output_log.txt?dl=0

**Comment by Peppie23** [comment]
Hi @phwoelfel do you have a way how i can reproduce this error to 100% ? I use Version 1.8.7 of ScienceAlert ... what version do you use?

**Comment by phwoelfel** [comment]
I wasn't able to reproduce it 100% and switching to the spacecenter and back usually fixes it. I will try to reproduce it again!
I think I'm also using 1.8.7, will check when I'm at home again.

**Comment by Peppie23** [comment]
Also no luck to reproduce with @rootfuchs save :/

**Comment by Peppie23** [comment]
Maybe this is how we can reproduce this error ([thx Speadge from the forum](http://forum.kerbalspaceprogram.com/threads/76793-1-0-2-ScienceAlert-1-8-7-Experiment-availability-feedback-%28May-4%29?p=2026968&viewfull=1#post2026968))

#### Needed mods
- RT
- ScienceAlert v1.8.7

#### How to
- Use our KSP1.0_Testbed ([link](https://github.com/RemoteTechnologiesGroup/RemoteTech/tree/develop/saves/RemoteTech%20KSP1_0%20Testbed))
- go to the vessel `Kerbal 2` via TrackingCenter
- make an eva report and store it into the vessel
- Warp to PE
- right click on the vessel and transmit the data (will throw an exception)

**Comment by phwoelfel** [comment]
Good to hear it's reproduceable now. I'm sorry I didn't have time to try it out myself.

**Comment by xEvilReeperx** [comment]
Hurray! Thanks for the reproduction steps. It's just what I suspected. ScienceAlert is keeping references to transmitters that no longer exist because RT adds and removes them. 

Could I talk you into firing GameEvent.OnVesselWasModified when you add or remove your transmitters? This will keep SA up to date with your changes.

In the meantime, I've got a bandaid fix in place that will prevent the data from being lost immediately. It's not a perfect fix without those events though

**Comment by Peppie23** [comment]
Hi @xEvilReeperx yes i can trigger the `OnVesselWasModified`, but do you think this is the best way? You will get the same errors again if another mod does the same.

What about to refresh your transmitter list before you transmit the data?

**Comment by xEvilReeperx** [comment]
Just refreshing is no good. MagicDataTransmitter acts differently than yours in that it doesn't actually have any transmission capability. It pretends to have an impossibly good score to fool KSP into sending all outgoing science data to it and then delegates that data out to the real transmitters.

My patch will prevent it from erroneously sending to a nonexistent transmitter, but if it refreshes and discovers there **aren't** any real transmitters onboard, now it's too late and it's stuck with data it can't transmit and can't store (currently). Even if it did store it, there's still the problem of only knowing the current state of the vessel's transmitter capability immediately on load. If it was disconnected from the RT network when loaded in, that data would keep floating around invisibly even after the vessel could transmit

So Re: best way? Yes, definitely. If there's some kind of problem with it, I'd settle for an event RemoteTech fires itself that I could hook into instead. I'll be looking into reprogramming the transmit button itself in the next version but for now this is the easiest solution

**Comment by Peppie23** [comment]
ok, i understand. I'll make a build for you with the `OnVesselWasModified` trigger.

**Comment by Peppie23** [comment]
@xEvilReeperx if you want to cross check my change you can use [build-develop-404](https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-develop-404)

btw. thanks

**Comment by xEvilReeperx** [comment]
Looks good over here. Thanks!
