### ISSUE TITLE
KMP Compatibility

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#44]
Original issue at Cilph/RemoteTech2#244.

Pezmc wrote:

> Mainly dishes often loose the vessel they are focussing on "unknown vessel" and "active ship" targeting doesn't work.

**Comment by KSP-TaxiService** [comment]
Hi,

KMP mod is no longer under active development since KSP 0.23 according to this [thread](http://forum.kerbalspaceprogram.com/index.php?/topic/51076-kmp-v0151-023-alpha-inactive/).

As such, this ticket will be closed with no further action required on our side.
