### ISSUE TITLE
resource other than electriccharge?

### ISSUE THREAD

**Issue by anxcon** [RemoteTechnologiesGroup/RemoteTech#456]
ModuleRTAntenna, line 386
            float resourceAmount = part.RequestResource("ElectricCharge", resourceRequest);

if that was changed to use a KSPField defaulting as "ElectricCharge" then this would work with the other mods that change how power works in ksp :) and not effect/break anything as default is still electric charge

**Comment by Peppie23** [comment]
Hi @anxcon 
> ... work with the other mods that change how power works ...

do you have an example for me?

**Comment by neitsa** [comment]
@anxcon 
I couldn't find a single mod, [using google](https://www.google.com/search?q="KspField"+"ElectricCharge"), that use `ElectricCharge` as a `KSPField`.

Is there any example out there on how to implement this request?

**Comment by ShotgunNinja** [comment]
To clarify what he meant: add a field to your antenna module.
Default it to "ElectricCharge" to not require changes in existing configs.
`
[KSPField] public string resource_used = "ElectricCharge";
`


Then use it in place of the hard-coded "ElectricCharge":
`
float resourceAmount = part.RequestResource(resource_used, resourceRequest);
`

**Comment by YamoriYuki** [comment]
@ShotgunNinja Thanks for your input.
I missed this issue for 1.8.3 so it'll be fixed for the next bugfix release

**Comment by YamoriYuki** [comment]
I just found out that I already fixed this while fixing #707 so already done in 1.8.2
Enjoy.
