### ISSUE TITLE
Add RCS Translation for RealFuels Ullage

### ISSUE THREAD

**Issue by svm420** [RemoteTechnologiesGroup/RemoteTech#461]
Please add an option for a timed/ delta v forward translation to settle propellants when using ullage simulation with RealFuels. I am currently having an almost impossible time trying to figure out how to get my second Comsat in the correct orbit without being able to manually translate for ullage since I can not tell the flight computer to do so. Please please please make this a priority! Thanks!

**Comment by Peppie23** [comment]
I've created a collection of todo's here: #481 and i'll close this one
