### ISSUE TITLE
Add antenna option to be non-retractable

### ISSUE THREAD

**Issue by JDPKSP** [RemoteTechnologiesGroup/RemoteTech#463]
I would request adding something akin to the "retractable" field in ModuleDeployableSolarPanel.
I'm currently mucking about with designing a spring loaded "tape measure" style antenna. Since it is spring loaded it shouldn't be able to be retracted. Also, the animation would look somewhat goofy in reverse.

**Comment by Peppie23** [comment]
:+1: I like this idea. I'll add this functionality to v1.7.0
