### ISSUE TITLE
Losing control of manned vessel when switching ground station

### ISSUE THREAD

**Issue by Schnobs** [RemoteTechnologiesGroup/RemoteTech#464]
I'm playing RSS/RO/RP-0 and am not 100% sure that this is a bug with RT, but it seems the most likely candidate.

During my first manned mission I lose control of the vessel late during the ascent. During a few retries, I found that it happens at the precise moment when the comms link switches from KSC to some fireship in the atlantic. At the same time, the display below the clock changes from "local control" to a few millisenconds of signal delay.

The kerbal on board is alive and well and can go on EVA. However, the vessel won't take any control input and the staging is locked. 

Clicking "Control from here" on the pod brings "no connection to send command on" even though there is an active link and the interface reports me to be online with only a few ms delay. No other messages whatsoever, neither on the screen nor in F3 nor in the log. 

There is plenty of juice in the batteries.

Control is restored when I re-enter the atmosphere.

**Comment by KSP-TaxiService** [comment]
Closing as we are not aware of any new forum or github report on this issue since. Please let us know if this issue is still happening in KSP 1.3 or 1.4
