### ISSUE TITLE
RLA Stockalike config

### ISSUE THREAD

**Issue by marosciacchitano** [RemoteTechnologiesGroup/RemoteTech#469]
Created RLA Stockalike V13 config. Instead of filing a pull request I figured I could just post a link to it here: 

https://www.dropbox.com/s/6tfbo253zbmp02i/RemoteTech_RLA_Probes.cfg?dl=0

**Comment by olekopyto** [comment]
Dandy!
BTW, you need to put it in RemoteTech folder for it to work!

**Comment by kitoma** [comment]
```
@PART[RLA_*]:HAS[@MODULE[ModuleCommand]]:!HAS[@MODULE[ModuleSPU]]:FOR[RemoteTech]
{
	%MODULE[ModuleSPU] {
	}
	
	%MODULE[ModuleRTAntennaPassive]	{
		%TechRequired = unmannedTech
		%OmniRange = 3000
		
		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 15.0
		}
	}
}
```

Might be easier / more generic, in case hoojiwana adds more parts :)
Also didn't need to be in the RemoteTech folder at all.
