### ISSUE TITLE
Flight Computers claims Out of Power with plenty ElectricCharge available

### ISSUE THREAD

**Issue by jonseverinsson** [RemoteTechnologiesGroup/RemoteTech#470]
In my Realism Overhaul game ( [modlist] (https://gist.githubusercontent.com/jonseverinsson/39237fe7b2aa5e8101a2/raw/4f87a8e0f4d32933c48bc6ad7ffeb78d0493bbcc/Modlist.ckan), [savefile] (https://gist.githubusercontent.com/jonseverinsson/39237fe7b2aa5e8101a2/raw/26e58a171cd8beabf5b1bdf6365010ba1b72d34b/persistent.sfs) ) my current rocket ( [craftfile] (https://gist.github.com/jonseverinsson/39237fe7b2aa5e8101a2/raw/26e58a171cd8beabf5b1bdf6365010ba1b72d34b/Rocket%252012.craft), [screenshot] (https://gist.github.com/jonseverinsson/39237fe7b2aa5e8101a2/raw/26e58a171cd8beabf5b1bdf6365010ba1b72d34b/screenshot0.png) ) becomes uncontrollable when the ElectricCharge in the probe body are depleted, despite there still being plenty power in the service module just beneath it.

**Comment by Peppie23** [comment]
Hi @jonseverinsson,

thanks for your report. This is a really weird problem. I can reproduce your issue with RemoteTech v1.6.6, 1.6.7 and 1.7.0.

When i remove part by part, it seems that the solar panel causes this problem. On my Screenshot1 you can see the disconnected RemoteTech status, but on Screenshot2 (without a solar panel) everything works fine. When i add a "real" procedural battery to the tank, everything works well too. (Screenshot3).

And i **can't** reproduce this error with a minimal RO installation ([modlist](https://gist.github.com/Peppie23/2cd49aa50a526f998412)). We've to find the mod who causes this problem.

btw. [chingham](http://forum.kerbalspaceprogram.com/threads/83305-1-0-4-RemoteTech-v1-6-8-2015-09-12?p=2211161&viewfull=1#post2211161) from the forum also posted that issue

@NathanKell have you ever heard of it?

##### Screenshot1
![screenshot1](https://cloud.githubusercontent.com/assets/7722222/10116470/c7fd9050-6436-11e5-9797-02897bed025a.png)

##### Screenshot2
![screenshot6](https://cloud.githubusercontent.com/assets/7722222/10116471/ce690154-6436-11e5-9153-1fb2b1a83fda.png)

##### Screenshot3
![screenshot7](https://cloud.githubusercontent.com/assets/7722222/10116602/c5795006-6438-11e5-9989-7e30d49faaad.png)

**Comment by Peppie23** [comment]
It looks that RP-0 causes this error.

My installation order based on the minimum installation of RO ([modlist](https://gist.github.com/Peppie23/2cd49aa50a526f998412))

- + Ven's Stock Part Revamp (works fine)
- + RealSolarSystem (works fine)
- + Real Progression Zero (the issue occurs)
