### ISSUE TITLE
Energy Cost /s /m ..

### ISSUE THREAD

**Issue by BevoLJ** [RemoteTechnologiesGroup/RemoteTech#487]
I was wondering if it might be possible to have the RT module show the ec cost for the longAntenna in /m.  Or the ability to set what it shows myself in the config. In RO it uses .0015 so the tooltip only shows .00/s.  Thanks for your consideration! =)

**Comment by Peppie23** [comment]
Hi @BevoLJ,

I have not noticed that on my RSS(R0) installation :relaxed: thanks for your report. I'll make a small logic like: `if consumption is lower than X than transform to /min`

I've also noticed that we print the label "Energy req." but all stock parts have the label "ElectricCharge", so i'll change that too.

But i'll do this on our next feature branch [v1.7.0](https://github.com/RemoteTechnologiesGroup/RemoteTech/milestones/1.7.0) and not on a bug fix version. Hope thats ok

btw. regards from a loyal viewer :grin:

**Comment by BevoLJ** [comment]
Thank @Peppie23 . That sounds awesome!
