### ISSUE TITLE
PartModule::getInfo() cached from ksp loading ?

### ISSUE THREAD

**Issue by Peppie23** [RemoteTechnologiesGroup/RemoteTech#489]
I think that is the problem why we see the `Technology Perk` on every core without researching the node on the R'n'D. Also with the OptionWindow/Settings for each save (#484) if you change the `ConsumptionRate` to 2. The `ConsumptionRate` on the loading screen is still 1 because you haven't select a save game ...

So is #484 for nothing ?? :angry:

**Comment by NathanKell** [comment]
Yes, it's cached on part compilation (when generating part tooltips).
If you invoke the method yourself, i.e. as RealFuels does to generate its own GUI when a part is selected in action group editor mode, then of course it will be run then with up-to-date info.

You _probably_ could recreate the module tooltips yourself via reflection, if it's a big deal.

**Comment by Peppie23** [comment]
Hi @NathanKell,

thanks for this info. Yesterday, erendrake and i have found that RemoteTech already has this ability to refresh the cached GetInfo's.
https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/Modules/ModuleRTAntennaPassive.cs#L255-L278

We only have to update line 275 from `ap.moduleInfo` to `ap.moduleInfos` (its now a list with module info objects) so i'll fix that today.
