### ISSUE TITLE
Inconsistent Map GUI Behavior

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#49]
The RemoteTech map GUI -- the toolbar at the bottom right, plus the button on the middle right to display a list of vessels, plus the flight computer window -- does not disappear when using F2 to hide all GUI elements. Only a cosmetic bug, but quite annoying if you want clean screenshots.

This bug was found using v1.3.3 + Community Hotfix, and appeared with both KSP 0.23 and 0.23.5.

![connectiondemo1](https://cloud.githubusercontent.com/assets/6760782/3113548/ff4f0d2a-e6da-11e3-819e-782d59250437.jpg)

**Comment by Peppie23** [comment]
Merged into 1.6
