### ISSUE TITLE
Verification: RT settings behavior under MM

### ISSUE THREAD

**Issue by NathanKell** [RemoteTechnologiesGroup/RemoteTech#490]
I looked at the source, and I believe this will work, but I just want to verify:
RO currently ships a RemoteTech_Settings.cfg file. However, it makes the (perhaps incorrect for some RO players) assumption that the user is also using RSS.

What I would like to do is to change the file to do everything except groundstations, and then after the main node, under a @RemoteTechSettings:NEEDS[RealSolarSystem]  node, add the groundstations. I would then have a @RemoteTechSettings:NEEDS[!RealSolarSystem] version that adds Kerbin-positioned ground stations. Will that work?

**Comment by Peppie23** [comment]
Hi @NathanKell,

since we've build the RemoteTechSettings config node you are able to set **only** the groundstations on your settings file. So yea, we should try this, in one file (example):

```
RemoteTechSettings:NEEDS[RealismOverhaul]
{
	RangeModelType = Root
	ThrottleZeroOnNoConnection = False
	MultipleAntennaMultiplier = 1
}
RemoteTechSettings:NEEDS[RealSolarSystem]
{
	GroundStations
	{
		STATION
		{
			Guid = 5105f5a9-d628-41c6-ad4b-21154e8fc482
			Name = AU - Woomera
			Latitude = -30.95875
			Longitude = 136.50366
			Height = 417
			Body = 1
			Antennas
			{
				ANTENNA
				{
					Omni = 7.5E+07
				}
			}
		}
		...
	}
}
```

**Comment by NathanKell** [comment]
Wow: That's awesome!

**Comment by Peppie23** [comment]
Hi @NathanKell,

i've verified that the mentioned feature will work :tada: so i'll close this issue and create two pr's on your side. One for RSS and one for RO

**Comment by NathanKell** [comment]
You're awesome. Thanks so much! :)

**Comment by pjf** [comment]
Wait, we can use MM to alter the RemoteTech settings now? Because I'm *sure* I left a note saying I would throw actual money at whoever did that in a ticket somewhere, and I'm more than willing to make good on my promise.

**Comment by NathanKell** [comment]
@pjf not only did you leave such a note, you bumped it a few months ago and, IIRC Starstrider, said it had already been done. :P

**Comment by pjf** [comment]
@NathanKell : Oh no! Damn my frail human memory and my 11,656 unread KSP-related notifications¹.

@Starstrider42, @NathanKell, @Peppie23 : Where do I send my joyous bounty to (PayPal/Bitcoin/Postcard)?

---

¹ I'm not even making this up.
