### ISSUE TITLE
Add short range EVA radio

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#5]
Original issue at Cilph/RemoteTech2#125.

sarbian wrote:
> Can you add short range radio to EVA Kerbal so we can transmit EVA report and samples without having to get back inside the ship.

tyrope wrote:
> Instead of draining power from the ship, I'd add enough electricity in the EVA suits for a few communications, that way you're more accurately simulating a radio battery.

**Comment by Peppie23** [comment]
Also done with the mod [KIS/EVA Portable Science Container and Transmitter v1.3](http://forum.kerbalspaceprogram.com/threads/106562-1-0-2-KIS-EVA-Portable-Science-Container-and-Transmitter-v1-3)
I'll close this
