### ISSUE TITLE
automatic retract/extend

### ISSUE THREAD

**Issue by Schnobs** [RemoteTechnologiesGroup/RemoteTech#503]
Many antennas will not survive reentry when deployed.

Occasionally I have the problem that I want to do $stuff between parachute deployment and touchdown, like jettison the heat shield and deploy legs.

That would be a lot easier if antennas could determine when the coast is clear und just redeploy as soon as it's safe.

**Comment by jdmj** [comment]
http://forum.kerbalspaceprogram.com/threads/64227

**Comment by Peppie23** [comment]
Will be added with RT v1.8.0 (#498)
