### ISSUE TITLE
Flight computer queue not in chronological order

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#51]
Another display issue I've noticed, but this one has gameplay effects. When you add a sequence of actions to the flight queue, they are not always listed in order of execution. Maneuver node EXEC commands, in particular, are always at the bottom of the queue. This makes it hard for the player to visualize the execution sequence, and allows for possible mistakes.

This bug was found using v1.3.3 + Community Hotfix, and appeared with both KSP 0.23 and 0.23.5. It partially motivates #26.

![Example for a maneuver node and post-maneuver attitude control](https://cloud.githubusercontent.com/assets/6760782/3113533/c180ecb6-e6da-11e3-81bc-540e2d2e5faf.png)

**Comment by Peppie23** [comment]
Implemented in #32
