### ISSUE TITLE
Command Center not working in KSP 1.0.4 or 1.0.5.

### ISSUE THREAD

**Issue by Nictrasavios** [RemoteTechnologiesGroup/RemoteTech#513]
I've got 6 Kerbals, 1 Large probe core and no command center, simple as that.

Steps to replicate:
1: Make simple vessel with hitchhiker command module, mk2 lander can and 2.5 meter probe core.
2: Add 6 kerbals.
3: Launch.

I currently have 2 craft is orbit which should be command centers but are not, and my simple testing craft failed as well. 

Mods installed: http://pastebin.com/hfC4Rse0

**Comment by Varsi** [comment]
Tested this in sandbox mode with KSP 1.0.5 and Remote tech 1.6.8 and those 3 parts and 6 kerbals worked as command center for me. I also remember accidentally making my station a command center in my previous 1.0.4 career game.

**Comment by d4rksh4de** [comment]
Not able to reproduce in KSP 1.1. As command center I used hitchiker module + mk2 lander and 2.5 meter probe core + commutron 16 (omni) antenna. As probe I used probodobodyne HECS core + Reflectron DP-10 (omni) antenna. Both vessels were not in the same physics range.

Installed mods: HyperEdit and RemoteTech (dev)
