### ISSUE TITLE
m700 Survey Scanner stuck after 100%

### ISSUE THREAD

**Issue by kyperioth** [RemoteTechnologiesGroup/RemoteTech#515]
m700 Survey Scanner gets stuck after alleging scan complete, this is tied to incomplete transmission which does not complete scan function. This is needed in order to unlock ore GUI overlay for the celestial body's knowledge base.

**Comment by kyperioth** [comment]
Tested against clean 1.0.5 install.
No other mods.

**Comment by jcarnell** [comment]
Not unique to m700, see #511

**Comment by oectacan** [comment]
.dll from this post: http://forum.kerbalspaceprogram.com/index.php?/topic/75245-105-remotetech-v169-2015-11-10/&do=findComment&comment=2285093 hepling me.

**Comment by spratt** [comment]
With that dll, I get the science but not the resource data.
