### ISSUE TITLE
Fresh install, no joy

### ISSUE THREAD

**Issue by DragonEater** [RemoteTechnologiesGroup/RemoteTech#517]
I do not have the buttons on the map view or the delay clock and flight computer under the ingame flight clock.

Looking in KSP.log I find many like below:

[LOG 20:33:59.121] PartLoader: Compiling Part 'Squad/Parts/Command/probeStackLarge/probeStackLarge/probeStackLarge'
[ERR 20:33:59.143] Cannot find a PartModule of typename 'ModuleSPU'

[ERR 20:33:59.144] Cannot find a PartModule of typename 'ModuleRTAntennaPassive'

Were should I start to track down why its not loading?

**Comment by DragonEater** [comment]
Fixed it, the gitub does not have the dll file included, found it!

**Comment by Nihilivin** [comment]
Which DLL was missing? I've just installed from CKAN and the only changes I saw are new parts available only in sandbox mode, but those are useless...

Thanks
