### ISSUE TITLE
M700 survey dont work

### ISSUE THREAD

**Issue by FourWindBadger** [RemoteTechnologiesGroup/RemoteTech#520]
I am trying to survey the mun, but when i click scan, and it counts from 0 to 100%, and i get the msg that its been send, it doesn't show me the overlay map, as it normally would.

It feels like it diden do the survey, or it did not find its way to wherever the data needs to go, for the game to check up on, what i just did.

 if i go to map mode, and focus on the planet, and go to the little menu on the right side, and select the overlay, it tells me "no resource data available"

and ofc its connected to the satellites that is orbiting the kerbin, and as a last try, i also send a maned probe to survey the mun, but with the same result.

I tried reinstall the game, i tried removing all mods (it worked) and i tried removing just the remotetech mod(and it worked) i also made sure i had the latest version of the mod.

**Comment by thomas15v** [comment]
I got the same issue.

It also throws up this:
```
[EXC 13:46:24.199] NullReferenceException: Object reference not set to an instance of an object
	ResearchAndDevelopment.GetScienceValue (Single dataAmount, .ScienceSubject subject, Single xmitScalar)
	ResearchAndDevelopment.SubmitScienceData (Single dataAmount, .ScienceSubject subject, Single xmitScalar, .ProtoVessel source, Boolean reverseEngineered)
	RnDCommsStream.submitStreamData (.ProtoVessel source)
	RnDCommsStream.StreamData (Single dataAmount, .ProtoVessel source)
	RemoteTech.Modules.ModuleRTDataTransmitter+<Transmit>c__Iterator0.MoveNext ()
```

**Comment by kaptain-kavern** [comment]
For anybody who needs it : here's a link to a quick fix from someone on the KSP Forum

http://forum.kerbalspaceprogram.com/index.php?/topic/75245-105-remotetech-v169-2015-11-10/&do=findComment&comment=2324100

**Comment by lamont-granquist** [comment]
So apparently its a one-line patch to 

https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/Modules/ModuleRTDataTransmitter.cs

To add:

```
GameEvents.OnTriggeredDataTransmission.Fire(scienceData);
```

I just don't know exactly where that line should go...

**Comment by FourWindBadger** [comment]
i tried that dll, and it dosnt work for me, it fucks up my game :/ 
i extracted all of the files ( i think the ModuleRTDataTransmitter.cs that is also included is the fix lamont-granquist is talking about

**Comment by lamont-granquist** [comment]
I looked at the source and I'm just not certain if that goes into the loop where its calculating the % sent (does RT really transfer science in tiny little chunks?) or if it goes at the very end when transmitting is successful.
