### ISSUE TITLE
Antenna Range

### ISSUE THREAD

**Issue by lordmatiz** [RemoteTechnologiesGroup/RemoteTech#521]
Hello.
I'm playing Realism Overhaul (real solar system) with Remote tech, and I guess something is messed up with ranges...
My Communotron 16 has range of 4.00 Mm, which is 4,000,000m. Right now my probe is at over 7,000,000m and still has connection with ground bases.

**Comment by rsparkyc** [comment]
See this:
https://www.reddit.com/r/RealSolarSystem/comments/3hu5bo/is_there_a_guide_to_understanding_remote_tech_in/
