### ISSUE TITLE
Mobile Processing Lab can't transmit science

### ISSUE THREAD

**Issue by lamont-granquist** [RemoteTechnologiesGroup/RemoteTech#523]
- KSP 1.0.5
- RemoteTech 1.6.9
- ScienceAlert *never* installed.

Transmitting science works as expected, except the science stored in an Mobile Processing Lab cannot be transmitted.  When the button is pressed it acts like it is transmitting (counts up to 100%), but the science never appears back at KSC and the science is still present in the MPL.

Cutting this ticket to distinguish between two different bugs being discussed in #511 -- the topic of that one seems to be the ScienceAlert bug where all transmission of science is blocked.  This bug happens without ScienceAlert installed and only affects the MPL.

**Comment by Varsi** [comment]
You are saying "only affects MPL". Does Survey scanner work for you? I assumed it used the same function.

**Comment by lamont-granquist** [comment]
Haven't tried, I've also got SCANsat installed, which might complicate that...  I thought I recovered science earlier in this save...

**Comment by lamont-granquist** [comment]
My M700s don't have any kind of button for sending back science at all, the science recovery from the SCANSat parts works fine.

**Comment by Varsi** [comment]
Yes, the M700 isn't supposed to send any science back. Instead it does orbital survey scan that lets you see ore on for example overlay maps. Remote Tech without a a fix prevents that scan (or rather prevents the data from being sent back).

**Comment by kaptain-kavern** [comment]
If it's the same issue than for the M700, try see [this other issue](https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/520) (fix provide)

**Comment by cdp1337** [comment]
Hey, may http://forum.kerbalspaceprogram.com/index.php?/topic/75245-105-remotetech-v169-2015-11-10/&page=150#comment-2285093 of use here?  FancyMouse reportedly fixed it back in November.

He added 
<code>
GameEvents.OnTriggeredDataTransmission.Fire(scienceData);
</code>
to around line 128 of ModuleRTDataTransmitter.cs.  I have this exact problem and am about to check to see if his patch fixes this issue.

**Comment by lamont-granquist** [comment]
@cdp1337 can you verify that i fixed it correctly in #524?

**Comment by cdp1337** [comment]
Which branch did you commit that file to?  I had to perform:

    git checkout 691835832d01fc6f65eb33eb0655bc094a5e3d96

to get your change.

Additionally, dll.zip was asking for a password when I ran build.remotetech.sh so I wasn't able to compile the library. :/  Any idea about that?

Otherwise, it seems to be correct...

**Comment by lamont-granquist** [comment]
I can't push to this remote, you have to add my forked remote:

```
git remote add lamont-granquist https://github.com/lamont-granquist/RemoteTech
git fetch lamont-granquist
git checkout lcg/fix-1.0.5-sciene
```

(with that typo that i apparently made to the branch name)

If you install the [hub command](github.com/github/hub) and alias it to your git command then you can just do this instead by copy/pasting the URL to the PR:

```
git checkout https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/524
```

No idea about the build problem you hit...   I grok git, I don't grok building kerbal DLLs under mono on a mac...

**Comment by websterhamster** [comment]
Has the fix been added to CKAN as an update? I like using CKAN to manage my mods, so I don't want to manually install the update.

**Comment by lamont-granquist** [comment]
#524 isn't merged, you'd have to check out that branch, build the module and install it right now

**Comment by zmarcantel** [comment]
what is currently in `lcg/fix-1.0.5-sciene` will fail to compile.
the variable `scienceData` is not in scope for this addition.

currently working on a fix, but just commenting as I stumbled on then when trying to build said branch.

**Comment by lamont-granquist** [comment]
yeah clearly wrong...

**Comment by zmarcantel** [comment]
even after fixing scope issues, problem still persists (transmission completes, nothing transferred)

**Comment by lamont-granquist** [comment]
i just pushed a change to #524 is it basically what you just tested?

**Comment by zmarcantel** [comment]
That's the first thing I tried, yes, and did not transfer.
First time digging into a kerbal mod so slow going.... plus I hit this bug while offloading a ton of science so takes a while to repro.

**Comment by zmarcantel** [comment]
Logs: https://gist.github.com/zmarcantel/6993fa6e491a862a728f

**Comment by lamont-granquist** [comment]
that's clearly the NRE but its not obvious to me where the bug lies...

**Comment by zmarcantel** [comment]
never used C# before, but seems like the `scienceData` object is either freed, nulled, or was incorrect to begin with when trying to add the science to the R&D

**Comment by lamont-granquist** [comment]
is it just an off-by-one error?   its emitting "Packets to go: 249 - Files to Go: 0" down to "Packets to go: 0 - Files to Go: 0" and then it blows up on that last one.

give the new hack in #524 a shot?

**Comment by zmarcantel** [comment]
so.... it 'half' works.
basically, it does not send the floating portion of science (I'm 80% sure it used to).

if I have 123.67 science, the 0.67 is not sent... I presume because it was in the last packet.
If fractional science is not meant to be sent, then works for me.

**Comment by lamont-granquist** [comment]
99.8% fixed then?  =)

**Comment by lamont-granquist** [comment]
definitely not the right way to fix it, but at least it converts a game-breaking bug to a bit of lolwut...

**Comment by petersohn** [comment]
I also get asked for a password for the downloaded .zip file when I try to build. Any ideas how to fix this?

**Comment by petersohn** [comment]
Found the solution. The `dll`s that are being downloaded can be found in the KSP game directory. Not that it is documented anywhere.

**Comment by cdp1337** [comment]
@petersohn Sweet!  Do you just copy/symlink them into the source directory?

**Comment by petersohn** [comment]
@cdp1337 I had to copy them. Symlink didn't work.
