### ISSUE TITLE
Standard Probes OKTO and Mk.1 doesn't have any connection without RemoteTech antenna.

### ISSUE THREAD

**Issue by fr33soul** [RemoteTechnologiesGroup/RemoteTech#527]
I used to fly in the atmosphere for tests with standard probes OKTO and Mk.1 and i didn't need any antenna untill now.. 

It seems that the probes don't have connection untill i put a RemoteTech antenna, it's mandatory with the new RemoteTech v1.69?
Probes have no more connection to the Command centre.

KSP 1.0.5

**Comment by Ghoughpteighbteau** [comment]
didn't need any antenna, now you need specifically a remote tech antenna? Stock would not work?

I always thought those probes needed antennas, but any antenna should do.

**Comment by hoylemd** [comment]
Yeah, I thought this was intentional - early probes don't get built-in ommis

**Comment by jcc10** [comment]
This is also a issue on 1.6.11 (The build for KSP 1.1 PR) as they state that they have built-in-omnis (range 3 km) but do not connect on the pad.

This makes launching them un-manned impossible since there is no antenna that will stay on during launch.

**Comment by jcc10** [comment]
Ok, the fix should be to note on all the probes that it requires "Unmanned Tech" Unlock for the core to have a integrated antenna.

This is confusing for new players who misunderstand that the probes get it as a upgrade later on.

**Comment by neitsa** [comment]
I can't recall exactly how RT behaved on older versions, but the fact that you need Unmanned Tech to get the free 3km bonus for probe cores is [written in the doc](http://remotetechnologiesgroup.github.io/RemoteTech/guide/parts/#probe-cores).

If anyone stumble on this issue: launch your vessel with a [DP-10 antenna](http://remotetechnologiesgroup.github.io/RemoteTech/guide/parts/#reflectron-dp-10); you then have a 500 kms Omni antenna that **doesn't break in atmosphere** (must be line of sight to KSC Mission Control, and below 150 km altitude, but at that point you should have already switched to a more capable antenna like the Communotron 16).
