### ISSUE TITLE
Hardcoded links

### ISSUE THREAD

**Issue by quorks** [RemoteTechnologiesGroup/RemoteTech#533]
You use hardcoded links to systemfiles in RemoteTech/src/RemoteTech/RemoteTech.csproj on line 37 to 75. Not every user has steam installed on B:\

**Comment by tomekpiotrowski** [comment]
I see no mention of a B: drive in the file you specify. Are you sure you're looking at the current develop version?

**Comment by quorks** [comment]
pls, close, misstake or i do not find it again :/

**Comment by tomekpiotrowski** [comment]
I've noticed that this PR changes those paths:
https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/531/files

You must have looked at that code somehow.

**Comment by quorks** [comment]
Jep, this is it, very confusing to find things on github again here. That Remote Tech had so many forks make things not easy
