### ISSUE TITLE
ModuleSPUPassive removes control from probe cores

### ISSUE THREAD

**Issue by Y3mo** [RemoteTechnologiesGroup/RemoteTech#558]
Hey,

I would like to make an MM patch which makes probe control independent of the connection, but retains the necessity for a connection when transmitting science.

While that would work by removing the ModuleSPU, that also means that omni antennas integrated into the probe cores do not work anymore (eg the 3km technology perk, which is useful for rovers).

My idea was, to replace the ModuleSPU with a ModuleSPUPassive. That works fine for integrated omni antennas within manned command pod parts. Unfortunately it removes control from probe cores (even when they are connected).

**Would it be possible for you to change that ModuelSPUPassive behaviour so that a probe core with a ModuleSPUPassive allows an integrated omni antenna to work for science transmission, but still gives the player full control as if it does not have a ModuelSPU?**

That would essentially allow a config emulating AntennaRange while retaining the awesome RT flight computer.

Thank you very much!

**Comment by Y3mo** [comment]
I tried to circumvent this issue by giving the ModuleSPU local control:
	%MODULE[ModuleSPU] {
		%IsRTCommandStation = false
		%RTCommandMinCrew = 0
	}

Unfortunately that does not work either, although the RTCommandMinCrew is set to 0, it still does not allow for local control without connection.

**Comment by YamoriYuki** [comment]
Looking at your [SETI-ProbeControlEnabler](https://github.com/Y3mo/SETI-ProbeControlEnabler) repository, you managed to figure this out.
If I'm not mistaken that patch also removes the Flight Computer access but there is no way around it with current Remote Tech.
Sorry for not helping you out.

**Comment by Y3mo** [comment]
SETI-ProbeControlEnabler allows for control of probes without connection by simply removing ModuleSPU. This unfortunately also removes the ability of inbuilt antennas to transmit science.

**Comment by YamoriYuki** [comment]
I understand how this is inconvenient.
Right now, I'm not sure how dofficult this might be but your idea of `ModuleSPU` that gives local control with no crew might be possible.
Please understand that we are already working on new CommNet based RT so if this turns out to be too complex of a change, it won't be implemented

**Comment by YamoriYuki** [comment]
I have something that should help, but I can only test it properly later this evening
I managed to add a `bool` field `AlwaysAllowLocalControl` to `ModuleSPU`, that should allow it to behave like a crewed pod. If it does not break anything (big IF), we could include this in the next bugfix release. I hope RT1.8 is enough fo this patch.

**Comment by YamoriYuki** [comment]
Everything worked out and this change will be included in the next release, whenever that happens to be.
