### ISSUE TITLE
flight computer spins randomly not holding directions

### ISSUE THREAD

**Issue by gnivler** [RemoteTechnologiesGroup/RemoteTech#559]
First bug report, hope I cover most of the bases.

KSP 1203 on Windows, 32 and 64bit tested.  Issue exists with no mods except RemoteTech 1.16.11-492.  I have other mods installed but simplified it to isolate the problem.

I'm a brand new RemoteTech user so I tried searching around to see that I'm just not doing something wrong.  I think it might be a bug, but it's so serious I'm confused why I'd be the first one to say so... maybe it's just me.

I create a basic probe craft, launch it and try to circularize with the flight computer.  Per the tutorial, I click GRD+ then EXEC after I've setup the maneuver.  The craft begins to spin and rotate never settles on a direction.  It doesn't look like it's even trying to find a particular point, it looks very random.  When it executed the burn, the direction is still wrong and the maneuver isn't anywhere nearly correctly executed.

Here is the craft and the save.
https://gist.github.com/gnivler/037d20163d5d68d9af6aefd18540106c

Thank you for your efforts!

**Comment by gnivler** [comment]
Here's a video showing how it behaves in orbit

https://www.youtube.com/watch?v=82LFz4evuJE

**Comment by gnivler** [comment]
More testing to come but I got a degree of success without the heavy torque SAS module, maybe it's chronically overshooting it's intended target?

**Comment by tomekpiotrowski** [comment]
Thank you for the report and for the video. We'll have a look at it.

**Comment by d4rksh4de** [comment]
Confirmed in latest develop branch, seems PID controller issue.

**Comment by gnivler** [comment]
Please let me know if I can help with any testing.  Is this PID controller something in the code?  Quick Google makes me think so but i do have a bunch of peripherals if it's that type of controller.  I did disconnect them or so I thought, during my tests.

Thanks again for doing this mod, looking forward to building it out in-game.

**Comment by adamzl** [comment]
gnivler, you can find an explanation of PID (proportional-integral-derivative) control on the kOS tutorial. it's a control smoothing method.

https://ksp-kos.github.io/KOS/tutorials/pidloops.html

**Comment by Poofey** [comment]
just to keep up, latest pre-release and latest dev build still has this issue, altough it won't spin around like previous builds it is unable to stabilize. a lower Ki might do it, altough i don't know how to access RT's PID.

**Comment by d4rksh4de** [comment]
I was able to update the PID controller and first tests are looking good, craft seems very stable.

**Comment by gnivler** [comment]
Unfortunately still having this with the release for 1.1 build 1230.  It went more like a crazy spin than a tumble this time.

**Comment by RickKerman** [comment]
Hello, i'm having the same issue, let me know if i can do something to help, reports etc.

TY for one of the most have mods for KSP.

**Comment by d4rksh4de** [comment]
I haven't commited my changes yet, I have been busy lately, hopefully I can do this in a couple of days.

**Comment by Milek7** [comment]
Any progress? It is pretty annoying that I cannot use flight computer.

**Comment by gnivler** [comment]
@d4rksh4de fix looks promising, very steady maneuver execution
