### ISSUE TITLE
Framerate drop while opening Comms DTS-M1

### ISSUE THREAD

**Issue by ndng28** [RemoteTechnologiesGroup/RemoteTech#562]
**Version:**
KSP: 1.1 (Win64) - Unity: 5.2.4f1 - OS: Windows 10  (10.0.0) 64bit

**Mods**
USI Tools - 0.7
Community Resource Pack - 0.5
Contract Configurator - 1.10.1
Contract Pack: Clever Sats - 1.0.0.1
Contract Pack: Field Research - 1.1.7
Contract Pack: Bases and Stations - 3.2.1
Contract Pack: Tourism Plus - 1.4.2
DMagic Orbital Science - 1.2.1
Firespitter - 7.2
GCMonitor - 1.4.1
Interstellar Fuel Switch - 1.19
keepfit - 0.10.4.3
Kerbal Engineer Redux - 1.1.0.1
KSP-AVC Plugin - 1.1.5
Lithobrake Exploration Technologies - 0.3.3
RCS Build Aid - 0.8
RemoteTech - 1.6.11
SCANsat - 1.1.5.2
SpaceY Expanded - 1.1.6
SpaceY Lifters - 1.12
ThrottleControlledAvionics - 3.0.1
USI Core - 0.2
Asteroid Recycling Tech - 0.8
USI Exploration Pack - 0.5
Freight Transport Tech - 0.5
Karbonite - 0.7
Karbonite Plus - 0.6
Kolonization Core - 0.2
USI-LS - 0.4
USI Survivability Pack - 0.5
UKS - 0.40
Unmanned before Manned - 1.0.8
Waypoint Manager - 2.5
Wider Contracts App - 1.3

**output_log.txt:
[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/220182/output_log.txt)
**

**Comment by d4rksh4de** [comment]
@ndng28 Does the FPS stay low while the antenna is opened? When I open the DTS-M1 antenna, I get FPS drop from 60 to 50 for a second, then it goes back to 60.

**Comment by ndng28** [comment]
Not when it is opened...only while opening.

**Comment by tomekpiotrowski** [comment]
Can you try reproducing this with only RemoteTech installed? Seems like you have quite a lot of mods installed, one of them could be causing this.

**Comment by ndng28** [comment]
Its working after the latest 1.1 stable release
