### ISSUE TITLE
Error on loading RemoteTech v1.6: "The classes in the module cannot be loaded"

### ISSUE THREAD

**Issue by Nihilivin** [RemoteTechnologiesGroup/RemoteTech#567]
Hello,

I'm having trouble using RemoteTech. The plugin seems to not load successfully... I've looked for many solutions, but I did not find any working one.

Last build (v1.6.10) only loaded parts, but not tech tree nor any UI elems. I've removed the whole plugin and installed v1.6.9, and it worked better (tech tree still not loaded, but some UI elements were there, like the red dot on the KSC, and my probes never lose KSC signal)

This problem seems to be like #457 and #517.

You can find my KSP.log here: http://pastebin.com/LmTNsGbM

So, Yes, I know, I have an error while loading RemoteTech, but I can't understand what goes wrong.

Here are my installed plugins: http://pastebin.com/0XemfYrR
As this problem is recurent on every saves, I won't post any persistence.sfs file.
No screenshot to provide.

Thank you for your time.

**Comment by tomekpiotrowski** [comment]
What is your KSP version?

Last build is 1.6.11, try that. 1.6.10 was not built correctly and might not have worked.

**Comment by Nihilivin** [comment]
Oops yes, KSP version is 1.0.5.

I'm trying with 1.6.11

**Comment by tomekpiotrowski** [comment]
Stick to 1.6.9 then. This is the last 1.0.5 compatible release, anything above that is meant to be used with KSP 1.1.

**Comment by Nihilivin** [comment]
Ok, I've installed 1.6.9 through ckan & removed most of my plugins. The red dot on KSC is glowing, but my probe still receive signal everywhere around kerbin. Moreover, the Tech tree was not modified. Any idea?

**Comment by tomekpiotrowski** [comment]
Try a totally fresh install - new copy of KSP and then install only 1.6.9.

**Comment by Nihilivin** [comment]
Wow, well done, now it works! Haha thank you!
