### ISSUE TITLE
Remote Tech breaks Tracking Station (for my setup)

### ISSUE THREAD

**Issue by Rob-2** [RemoteTechnologiesGroup/RemoteTech#568]
Hello,
I have a modded install, a fresh career and a test satellite in a orbit. When I have Remote Tech installed, loading the game, switching to the tracking station, then to the sat, focussing kerbin, and then go back to the space center and then into the tracking station breaks the tracking station. There is not the test satellite loaded anymore, it only shows a "Space Station One" which is unjoinable.

I have more mods installed, so it could be related. There are some more exceptions in the log, too.
However, as soon as I play withou Remote Tech the issue is gone.

Unfortunately Remote Tech is a must have mod for me.

RT is 1.6.11 from CKAN,
KSP is 1.1.0.1228 (WindowsPlayer)-pre

BR
Rob

[LOG 02:44:31.337] [MessageSystem] Save Messages
[LOG 02:44:31.343] Game State Saved to saves/default/persistent
[LOG 02:44:31.357] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.358] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.358] UIMasterController: HideUI
[WRN 02:44:31.359] [HighLogic]: =========================== Scene Change : From SPACECENTER to TRACKSTATION =====================
[LOG 02:44:31.659] ScaleModList: listSize 246 maxListSize 1473
**[EXC 02:44:31.659] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.UI.FocusOverlay.OnVDestroy (.Vessel v)
	EventData`1[Vessel].Fire (.Vessel data)
	Vessel.OnDestroy ()**
[LOG 02:44:31.660] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.660] [UIApp] OnDestroy: KSPedia
[LOG 02:44:31.660] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.661] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.661] [UIApp] OnDestroy: ContractsApp
[LOG 02:44:31.661] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.700] UICanvasPrefabSpawner TrackingStationSpawner spawning TrackingStation
[LOG 02:44:31.852] SCANsat.SCANsat.SCAN_Platform.CustomAddonLoader: TRACKSTATION was loaded; instantiating addons...
[LOG 02:44:31.853] ImprovedAddonLoader: Creating addon 'SCANtoolbar'
[LOG 02:44:31.853] SCANsat.SCANsat.SCAN_Platform.CustomAddonLoader finished; created 1 addons
[EXC 02:44:31.856] NullReferenceException
	FloatingOrigin.setOffset (Vector3d refPos)
	FloatingOrigin.SetOffset (Vector3d refPos)
	PSystemSetup.SetTrackingStation ()
	PSystemSetup.OnLevelWasLoaded (Int32 level)
[LOG 02:44:31.857] UIMasterController: ShowUI
[LOG 02:44:31.860] [PlanetariumCamera]: Focus: Kerbin
[LOG 02:44:31.868] AddonLoader: Instantiating addon 'QuickMute' from assembly 'QuickMute'
[LOG 02:44:31.869] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 02:44:31.870] AddonLoader: Instantiating addon 'RTCoreTracking' from assembly 'RemoteTech'
[LOG 02:44:31.870] AddonLoader: Instantiating addon 'PersistentEmitterManager' from assembly 'SmokeScreen'
[LOG 02:44:31.871] AddonLoader: Instantiating addon 'TSTMenu' from assembly 'TarsierSpaceTech'
[LOG 02:44:31.871] 4/21/2016 2:44:31 AM,TarsierSpaceTech,TSTMenu awake in TRACKSTATION
[LOG 02:44:31.872] 4/21/2016 2:44:31 AM,TarsierSpaceTech,TSTMenu Not SpaceCenter or Flight Scene, Destroying this instance.
[LOG 02:44:31.872] 4/21/2016 2:44:31 AM,TarsierSpaceTech,Awake complete
[LOG 02:44:31.872] AddonLoader: Instantiating addon 'TSTMstStgs' from assembly 'TarsierSpaceTech'
[LOG 02:44:31.873] 4/21/2016 2:44:31 AM,TarsierSpaceTech,TSTMstStgs Constructor
[LOG 02:44:31.873] 4/21/2016 2:44:31 AM,TarsierSpaceTech,TSTMstStgs globalConfigFilename = D:/Spiele/KSP_win_1.10_Mods/GameData/TarsierSpaceTech/Plugins/Config.cfg
[LOG 02:44:31.874] 4/21/2016 2:44:31 AM,TarsierSpaceTech,TSTMstStgs
[LOG 02:44:31.875] AddonLoader: Instantiating addon 'KolonizationMonitor_TStation' from assembly 'KolonyTools'
[LOG 02:44:31.875] Loading D:\Spiele\KSP_win_1.10_Mods\GameData\UmbraSpaceIndustries\Kolonization\Kolony.png
[LOG 02:44:31.878] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.878] AddonLoader: Instantiating addon 'PlanetaryLogisticsMonitor_TStation' from assembly 'KolonyTools'
[LOG 02:44:31.879] Loading D:\Spiele\KSP_win_1.10_Mods\GameData\UmbraSpaceIndustries\Kolonization\PlanLog.png
[LOG 02:44:31.880] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:31.880] AddonLoader: Instantiating addon 'LifeSupportMonitor_TStation' from assembly 'USILifeSupport'
[LOG 02:44:31.880] Loading D:\Spiele\KSP_win_1.10_Mods\GameData\UmbraSpaceIndustries\LifeSupport\Supplies.png
[LOG 02:44:31.881] ScaleModList: listSize 246 maxListSize 1473
**[EXC 02:44:32.269] NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.SpaceTracking.buildVesselsList ()
	KSP.UI.Screens.SpaceTracking.Start ()**
[LOG 02:44:32.270] QuickMute(1.08): Settings Loaded
[LOG 02:44:32.271] RemoteTech: Connecting with ControlLock ...
[LOG 02:44:32.271] RemoteTech: NetworkManager: SatelliteRegister(Mission Control)
[LOG 02:44:32.273] ScaleModList: listSize 246 maxListSize 1473
[LOG 02:44:32.288] RemoteTech: RTCore v1.6.9 loaded successfully.
[LOG 02:44:32.288] RemoteTech: SatelliteManager: RegisterProto(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816)
[LOG 02:44:32.288] RemoteTech: GetSignalProcessor(Untitled Space Craft): Check
[LOG 02:44:32.290] RemoteTech: ProtoSignalProcessor crew count of Untitled Space Craft is 0
[LOG 02:44:32.291] RemoteTech: HasCommandStation(Untitled Space Craft)
[LOG 02:44:32.292] RemoteTech: HasCommandStation(Untitled Space Craft)
[LOG 02:44:32.293] RemoteTech: ProtoSignalProcessor(Powered: True, HasCommandStation: False, Crew: 0/6)
[LOG 02:44:32.294] RemoteTech: SatelliteManager: OnRegister(VesselSatellite(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816))
[LOG 02:44:32.294] RemoteTech: NetworkManager: SatelliteRegister(VesselSatellite(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816))
[LOG 02:44:32.294] RemoteTech: AntennaManager: RegisterProtos(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816)
[LOG 02:44:32.295] RemoteTech: ProtoAntenna(Name: Probodobodyne OKTO, Guid: aefa230a-aadc-4d94-b2c3-0020a1b30816, Dish: -1, Omni: 3000, Target: 00000000-0000-0000-0000-000000000000, CosAngle: 1)
[LOG 02:44:32.296] RemoteTech: AntennaManager: OnRegister(Probodobodyne OKTO)
[LOG 02:44:32.297] RemoteTech: SatelliteManager: RegisterProto(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816)
[LOG 02:44:32.298] RemoteTech: GetSignalProcessor(Untitled Space Craft): Check
[LOG 02:44:32.299] RemoteTech: ProtoSignalProcessor crew count of Untitled Space Craft is 0
[LOG 02:44:32.299] RemoteTech: HasCommandStation(Untitled Space Craft)
[LOG 02:44:32.300] RemoteTech: HasCommandStation(Untitled Space Craft)
[LOG 02:44:32.302] RemoteTech: ProtoSignalProcessor(Powered: True, HasCommandStation: False, Crew: 0/6)
[LOG 02:44:32.302] RemoteTech: SatelliteManager: OnRegister(VesselSatellite(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816))
[LOG 02:44:32.303] RemoteTech: NetworkManager: SatelliteRegister(VesselSatellite(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816))
[LOG 02:44:32.303] RemoteTech: AntennaManager: RegisterProtos(Untitled Space Craft, aefa230a-aadc-4d94-b2c3-0020a1b30816)
[LOG 02:44:32.304] RemoteTech: ProtoAntenna(Name: Probodobodyne OKTO, Guid: aefa230a-aadc-4d94-b2c3-0020a1b30816, Dish: -1, Omni: 3000, Target: 00000000-0000-0000-0000-000000000000, CosAngle: 1)
[LOG 02:44:32.304] RemoteTech: AntennaManager: OnRegister(Probodobodyne OKTO)
[WRN 02:44:32.629] [UiApp] Awake: ContractsApp
[WRN 02:44:32.630] [UiApp] Awake: KSPedia

Modlist:

Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
ModuleManager.2.6.22 v2.6.22.0
USITools v1.0.0.0
Chatterer v0.9.8.1230
MiniAVC v1.0.3.2
DMagic v1.2.0.3 / vv1.2.3
Firespitter v7.1.5950.29855
InterstellarFuelSwitch v1.21.0.0 / v1.21.0
MiniAVC v1.0.3.1
Scale_Redist v1.0.0.0
JSIAdvTransparentPods v0.1.1.0
KerbalEngineer v1.1.0.2
KerbalEngineer.Unity v1.0.0.0
MiniAVC v1.0.3.2
KerbalJointReinforcement v3.1.5.0
MiniAVC v1.0.3.0
MiniAVC v1.0.3.0
MechJeb2 v2.5.1.0 / v / v2.5.7.0
QuickMute v1.0.8.42913
RasterPropMonitor v0.25.0.36940
RCSBuildAid v0.7.7.34644
RcsSounds v5.0.0.0
RemoteTech v1.6.0.0 / v1.6.9
SafeChute v1.0.5954.35054
SCANsat v1.6.0.0 / vv16.0 / v1.6.0.6
SCANmechjeb v1.6.0.0 / vv16.0
SmokeScreen v2.6.15.0
Stock assembly: KSPSteamCtrlr v0.0.1.33
Stock assembly: SaveUpgradePipeline.Scripts v1.0.0.2 / v1.0.0.21
Stock assembly: Steamworks.NET v8.0.0.0 / v8.0.0
MiniAVC v1.0.3.0
TarsierSpaceTech v6.0.0.0
Scale v2.2.6.1
Scale_Redist v1.0.0.0
KolonyTools v1.0.0.0
USILifeSupport v1.0.0.0
AirbagTools v1.0.0.0
FloaterTools v1.0.0.0
Lifeboat v0.1.2.0
MiniAVC v1.0.2.3
AdvancedAnimator v1.0.5205.2310 / v1.1.0.0

Folders and files in GameData:
000_USITools
Chatterer
CommunityResourcePack
ContractConfigurator
ContractPacks
DMagicOrbitalScience
ETT
Firespitter
InterstellarFuelSwitch
JSI
KerbalEngineer
KerbalJointReinforcement
KWRocketry
LETech
MechJeb2
ModRocketSys
QuickMute
RasterPropMonitor
RCSBuildAid
RcsSounds
RealPlume
RealScaleBoosters
RemoteTech
SafeChute
SCANsat
SmokeScreen
SpaceY-Expanded
SpaceY-Lifters
Stock folder: Squad

TarsierSpaceTech
TweakScale
UmbraSpaceIndustries
UniversalStorage
WaypointManager
ModuleManager.2.6.22.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree

**Comment by Milek7** [comment]
It happened me (empty tracking station and "Space Station One") but it was one time issue gone after restart.

**Comment by Rob-2** [comment]
Unfortunately, that doesnt help, for me. I (re-) startet the game plenty and startet plenty new careers, while figuring out, what causes the problem. This is totally reproducable for me.
If someone want's to take a look, I could upload the used mod-setup.
BR
Rob

**Comment by bradgillap** [comment]
I noticed the issue particularly when using two probe core parts and moving control from one to the other before ejection of the previous.

**Comment by SilentWindOfDoom** [comment]
I have the same issue, I created a fresh install and only installed RemoteTech-1.6.11.

The following steps might require you to cycle between the craft > escape > center > Tracking station more than a dozen times before the error might occur, it can also take as few as one.

Steps to reproduce:

Install KSP 1.1
Copy contents of RemoteTech-1.6.11 folder to Gamedata
Start game, Create and launch default sandbox.
Create simple craft.
![image](https://cloud.githubusercontent.com/assets/18603901/14726086/07b6154a-0820-11e6-83ac-ccf05ac9f976.png)
Launch it (keep it on the launchpad)
Point activated dish at Kerbin (not sure if relevant, ran out of time to test)
Press Escape, return to center, click tracking station.

Problematic result is as follows:

![image](https://cloud.githubusercontent.com/assets/18603901/14726152/76354a0e-0820-11e6-90a7-0831de4055c8.png)

You can clearly see the probe icon on the map but not to the left. All buttons are unresponsive at this point. You can still browse the planet map using the mouse, but you need to alt-F4 out of the game.

I have included the log, I do not know how to read it, but there are some nullpointer issues regarding the tracking station towards the end.

[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/230843/output_log.txt)

save file: 
[persistent.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/230845/persistent.zip)

Note: Before sending this out I attempted to create it using the steps above but.. im 20+ switches in now and it is still working as it should. Hopefully the log will be useful.

**Comment by Rob-2** [comment]
To reproduce the error for me it seems to be important, to open the map and center on kerbin. Then leave te flight and go to the tracking station. In my setup I get this error 100%.

It's always:
[EXC 16:03:08.519] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.UI.FocusOverlay.OnVDestroy (.Vessel v)
	EventData`1[Vessel].Fire (.Vessel data)
	Vessel.OnDestroy ()

**Comment by Rob-2** [comment]
Ok, cleaned out the GameData folder. Installed RT + MM from CKAN.
Steps to reproduce:
Start, New Sandbox, only Stayputnik Core, Fly, Map, Center Kerbin (double click), ESC, Space Center, Tracking Station... bugged.

**Comment by d4rksh4de** [comment]
Thanks @Rob-2 and @SilentWindOfDoom for the steps. I was able to identify and fix the issue.

**Comment by Rob-2** [comment]
Nice! Hope we get it compiled, soon. :)

**Comment by Milek7** [comment]
For those who don't have Mono compiler installed: https://drive.google.com/file/d/0B3sAAofr__HldGJJVjV4dlVhMVU/view?usp=sharing
