### ISSUE TITLE
Maneuver node glyph remains after execution

### ISSUE THREAD

**Issue by symmeclept** [RemoteTechnologiesGroup/RemoteTech#577]
With build 509, having the flight computer remove the node, while in map view, leaves the marker on screen. The marker stays in the same place until you exit the game.

How to reproduce:

1. Create maneuver node.
2. Have flight computer execute node.
3. Finish execution while in map view, when flight computer auto-removes node.

Here's a pretty picture. It's like CRT burn-in.
http://imgur.com/pOfM4o5

Save file:
[RT_nodebug.sfs](https://gist.github.com/symmeclept/cc80985aadc8e258199f04104376b02e)

**Comment by d4rksh4de** [comment]
Same as #576

**Comment by tomekpiotrowski** [comment]
Fixed by #582
