### ISSUE TITLE
Flight Computer doesn't close when going back to Space center view

### ISSUE THREAD

**Issue by d4rksh4de** [RemoteTechnologiesGroup/RemoteTech#578]
Flight Computer doesn't close (if it was open) when going back to Space center view. When another vessel is opened, the flight computer breaks, eg cancel commands queue up and never execute.

**Comment by gnivler** [comment]
I noticed this as well.. to me it seemed kind of like separate instances of the FC.  The 'old' FC GUI is visible and interactive but doesn't queue commands.  You can close it and reopen it and it's working again.  Agreed it's a bug.

**Comment by d4rksh4de** [comment]
Spent a lot of time investigating this issue, the logic that controls showing and hiding the FC window is very messy. For example, `FlightComputer.Dispose()` is called multiple times on the same instance and the instance is being used after that. And the issue does not occur sometimes when debugging, seems the timing is important. To properly fix this, the FC GUI needs to be redesigned.

**Comment by Galenmacil** [comment]
Not sure if this is worth mentioning, but the bug is still present as of this writing... Here is a screenshot showing the broken interface remains at the KSC screen.
![remote tech bug](https://cloud.githubusercontent.com/assets/19394274/15446811/7d017746-1ef9-11e6-991c-3b5039e5c1c2.jpg)

Here an excerpt from the log file showing multiple errors:


[EXC 22:54:22.075] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.FlightComputer.FlightComputer.get_Status ()
	RemoteTech.UI.QueueFragment.get_Status ()
	RemoteTech.UI.QueueFragment.Draw ()
	RemoteTech.UI.FlightComputerWindow.Window (Int32 id)
	RemoteTech.UI.AbstractWindow.WindowPre (Int32 uid)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[EXC 23:03:55.967] NullReferenceException: Object reference not set to an instance of an object
	RemoteTech.RTDebugUnit.DumpSatellites ()
	RemoteTech.RTDebugUnit.Dump ()
	RemoteTech.RTDebugUnit.Update ()
[EXC 02:04:53.410] NullReferenceException: Object reference not set to an instance of an object
	FlightGlobals.get_Vessels ()
	RemoteTech.RTUtil.GetVesselById (Guid vesselid)
	RemoteTech.AntennaManager.Unregister (Guid key, IAntenna antenna)
	RemoteTech.Modules.ModuleRTAntenna.OnDestroy ()
[EXC 02:04:53.429] NullReferenceException
	KSP.UI.UIList`1[KSP.UI.UIListItem].RemoveItem (KSP.UI.UIListData`1 item, Boolean deleteItem)
	KSP.UI.UIList`1[KSP.UI.UIListItem].RemoveItem (KSP.UI.UIListItem item, Boolean deleteItem)
	KSP.UI.UIList.RemoveItem (KSP.UI.UIListItem item, Boolean deleteItem)
	KSP.UI.Screens.ApplicationLauncher.RemoveModApplication (KSP.UI.Screens.ApplicationLauncherButton button)
	RemoteTech.UI.FocusOverlay.Dispose ()
	RemoteTech.RTCore.OnDestroy ()
	RemoteTech.RTCoreFlight.OnDestroy ()

**Comment by neitsa** [comment]
I think I fixed it when I addressed #673 (fix is [here](https://github.com/RemoteTechnologiesGroup/RemoteTech/commit/96bcc8eb387f0ccf63f0a3fc3d68249acbd1519d#diff-7edf5e9a1039fb44c4a365f0ebe73591R121)). 

With this fix the FC is now closed when switching to another vessel or going away from the flight scene. I find it simpler as is (and less confusing), as you don't risk to input commands on the wrong vessel. 

Feel free to reopen or comment on this issue if you feel this fix is not adequate.
