### ISSUE TITLE
Can't connect to mission control in career

### ISSUE THREAD

**Issue by MikkelKidde** [RemoteTechnologiesGroup/RemoteTech#581]
So i've been playing ksp for a while now and wanted to give mods a try, and then i saw remote tech, i then installed it. All the parts are there, and if i play Sandbox, i am able to connect to mission control, but as soon as i play in career mode, i am not able to connect to mission control with the probes.

**Comment by gnivler** [comment]
It sounds like you may have a build problem, try going through the tutorial if you're stuck.  My guess is that you're missing the cheap uni antenna or have used the Communotron as your omni, which works but it has to be deployed.  The RT antenna starts deployed (it's smaller).

**Comment by MikkelKidde** [comment]
@gnivler Correct me if im wrong, but doesnt all the probes have a build in 'antenna' already, because when i was in sandbox and was trying to find out what i was doing wrong, i took the Stayputnik Mk. 1 probe and placed it on the launchpad without an antenna and it said that it was connected. But when i did the exact same thing in career, it said that i wasn't connected.

**Comment by tomekpiotrowski** [comment]
From RemoteTech documentation: `Like in stock KSP, you need to research Flight Control before you can build unmanned probes.`

**Comment by gnivler** [comment]
I'm really not an expert, but reading from http://remotetechnologiesgroup.github.io/RemoteTech/#overview-of-mechanics

The probe core is a signal processor, not an antenna.  I'll have to try this out later, I'm still learning RT too but never used that probe core.

"You will only be able to control a signal processor as long as you have a working connection"

Looks like you got an official answer while I was typing!
