### ISSUE TITLE
Stuck in observatory mode.

### ISSUE THREAD

**Issue by Troblin** [RemoteTechnologiesGroup/RemoteTech#590]
Had many mods, worked okay. Added Remotetech, PreciseNodes and Scansats. Began getting following bug: Entering an observatory I'm not seeing flyable objects in list and can't focus on them or press the exit back to spaceport button, or 'fly this ship' button - so observatory screen is a dead end leading to restarting game app. Also there's a ghost object in the lists 'space station one' that has a debris icon, can't be deleted or activated, has a 99d etc orbit. I'm completely not sure that this mod is to blame, but since the bug involves having installed this mod maybe someone knows what to do or at least how to quit the observatory without restarting.

Just in case a link to screenshot and modlist thanks for viewing.
http://steamcommunity.com/sharedfiles/filedetails/?id=673988576

KSP: 1.1 (Win64) - Unity: 5.2.4f1 - OS: Windows 7  (6.1.7600) 64bit
Filter Extensions - 2.5
USI Tools - 0.7.1
B9 Part Switch - 1.1
Behemoth Aerospace Engineering Large Parts - 1.3.5
Community Resource Pack - 0.5
Final Frontier - 1.0.2.2131
Fuel Tanks Plus - 1.8.1
GPOSpeedFuelPump - 1.8
HeatControl - 0.3
Interstellar Fuel Switch - 1.24
NearFutureConstruction - 0.6
Kerbal Attachment System - 0.5.6.7
Kerbal Engineer Redux - 1.1.0.2
Kerbal Inventory System - 1.2.7.6
KSP-AVC Plugin - 1.1.6.1
Infernal Robots - 0.21.4
MarkIVSystem - 0.2.1
Modular Rocket Systems - 1.12.6
Docking Port Alignment Indicator - 6.3
NearFutureElectrical - 0.7
NearFuturePropulsion - 0.7
NearFutureSolar - 0.6
NearFutureSpacecraft - 0.4.4
Kerbal Planetary Base Systems - 1.0.8
QuickContracts - 1.0.5
QuickSearch - 2.0
RCS Build Aid - 0.7.7
RCS Sounds - 5.0
Regolith - 0.1.2
RemoteTech - 1.6.11
DeepFreeze Continued... - 0.22
SCANsat - 1.1.6
SpaceY Lifters - 1.12.2
TextureReplacer - 2.4.12
Kerbal Alarm Clock - 3.6.1
TweakScale - 2.2.7.2
USI Core - 0.2.1
Asteroid Mining Technologies - 0.1.1
Kolonization Core - 0.2.1
USI-LS - 0.4.2
UKS - 0.40.1.1
KSP Interstellar Extended - 1.8.12

**Comment by d4rksh4de** [comment]
Please try with latest pre-release.

**Comment by Troblin** [comment]
Confirming same bug after installing latest prerelease ksp version via steam betas option. First one or several entries into observatory will likely be okay, but after the very first flight the probability of interface breaking bug becomes about 70%.

Separate question to anyone reading - if I build a communication mast like 100 meters high using KIS, will position of antena on this tower be calculated in regard of signal relaying?

**Comment by d4rksh4de** [comment]
The RemoteTech pre-release build-develop-522: https://github.com/RemoteTechnologiesGroup/RemoteTech/releases

**Comment by Troblin** [comment]
Looks like it fixed it thanks. I'll keep testing it for a day just in case and report here.

**Comment by Troblin** [comment]
Checked with several hours of running time and multiple deployed sattelites - not a single map bug. Issue can be considered resolved. Thanks shade.
