### ISSUE TITLE
Click node in computer display says hold prograde

### ISSUE THREAD

**Issue by DrFish6t9** [RemoteTechnologiesGroup/RemoteTech#592]
This is a new one for me and might not be due to remote but some other mod since the updates.
When I click on node in the computer to start some manoeuvre planning the display says hold manoeuvre prograde and makes the craft just spin to its hearts content.
The only way I have of making un-connected manoeuvres now is to get mechjeb to point at the node, tell the computer to execute node and hope that by the time the node comes around it has not drifted too far.

**Comment by gnivler** [comment]
It sounds like you're using an old version, that was recently fixed.

**Comment by DrFish6t9** [comment]
I'm using 1.6.11 (latest CAKN gives me). Haven't tried it since the 1.1 update so hopefully it'll be resolved.
The semi work around works kind of. there are a few mods that should be integrated into the game as without them the game is not complete, remote tech is a must for me as it adds a level of realism and complexity to the game that makes it so much more.
