### ISSUE TITLE
Customs parts missing from VAB in 1.2

### ISSUE THREAD

**Issue by james3838** [RemoteTechnologiesGroup/RemoteTech#593]
I can see remote tech custom parts in tech tree, but they are not in VAB.  I looked at my log, but didn't see any error.  I'm using build-develop-522.  It was working as expected in 1.1.  Anyone else see this or have ideas how to debug?

**Comment by james3838** [comment]
One note - I see custom parts from ScanSat, so its not just 1.2 breaking all parts.

**Comment by MrCamoga** [comment]
You have to update the module manager to the 2.6.24. Here you have the link https://ksp.sarbian.com/jenkins/job/ModuleManager/113/artifact/ModuleManager.2.6.24.dll :)

**Comment by james3838** [comment]
Confirmed that fixed the issue.
