### ISSUE TITLE
Change dish target from map view and/or tracking station

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#6]
Original issues at Cilph/RemoteTech2#139, Cilph/RemoteTech2#242.

Lexif wrote:
> From a gameplay perspective, it feels like an artificial restriction to me. I'm supposed to imagine I control a probe from mission control, so I should be able to switch the target of dishes on other probes without jumping through hoops, right? Switching vessels works too, but it is quite slow and awkward.

cerebrate wrote:
> Dishes should be retargetable from Tracking Station ...when there's a connection from Mission Control to the satellite, ship, etc., that they're attached to. As mission control guy in charge of communications, I shouldn't have to spend the extra time to switch in and out of complete control of the ship just to retask one antenna.

**Comment by wisq** [comment]
I think this has been complete for a while?  I've been able to change targets from the Tracking Station since at least October 2014.

**Comment by Peppie23** [comment]
Yea, i'll close this.
