### ISSUE TITLE
Range Multiplier set to 0 causes all antennae to have no range

### ISSUE THREAD

**Issue by gnivler** [RemoteTechnologiesGroup/RemoteTech#600]
Granted this might fall into the "obviously" column, it does cripple functionality, vessels uncontrollable from the launch pad

**Comment by tomekpiotrowski** [comment]
Hmm, I think I would not consider this a bug. If you're setting the range multiplier to 0 you know what you're getting into :P

Maybe someone would actually find this useful :)
