### ISSUE TITLE
Manual controls is locked unless there is com16 antenna

### ISSUE THREAD

**Issue by Goury** [RemoteTechnologiesGroup/RemoteTech#606]
KSP 1.1.2, 1.6.11 and 524, delay is set to false.
Unmanned sat just won't let me to control it by hand but react to fly comp commands fine.
But once there is active com16 antenna then it works as it should.
So there is no way to do anything without this exact antenna attached and preactivated.

**Comment by gnivler** [comment]
There were some parts problems with slightly outdated ModuleManager DLLs, maybe check that.  Also the cheap Reflectron DP-10 starts activated, in case it's just a use issue.

**Comment by Goury** [comment]
Tried DP-10, it won't do the thing.
I'm using manager 2.6.24, should I try newer one?

**Comment by gnivler** [comment]
Hmm... that's what I'm using so I'm not sure.  Two ideas for whatever they're worth.. delete the MM ConfigCache / TechTree and/or try stock + RT to rule out a conflict.  I'm not saying it's not a bug because I don't know, but that functionality is OK on my side.

**Comment by Goury** [comment]
Okay, I'll go try this

**Comment by Goury** [comment]
Tested so far:
Cleared MM cache, 88-88 does work too, other antennas does not work as desired.

**Comment by Goury** [comment]
Squeaky-clean 1.1.2 with just fresh mm and 524.
Works just fine.

So it should be related in some way to some other mods.
I will try some hit-and-miss and update this issue as soon as I discover something more useful.

**Comment by gnivler** [comment]
Cool glad you made some progress!

**Comment by Goury** [comment]
It is kerbalism 0.9.9.4
Seems it breaks something related to remote tech

**Comment by ShotgunNinja** [comment]
Kerbalism MM patches replace ModuleDataTransmitter with its own. Likewise, RemoteTech MM patches instead remove ModuleDataTransmitter then add one or more of its own modules. Depending on the order in which these patches are applied, some antennas get the Kerbalism module, some the RemoteTech one and some both.

Meanwhile both mods look for their own antenna modules in the active vessel and disable control when out of range/sight.

What's happening here specifically is that in the vessel there were one of the exclusive RemoteTech antennas. RemoteTech find its own modules, and there is range/sight so it doesn't lock controls. But Kerbalism signal mechanic doesn't find its own module and assume there is no antenna, thus locking the controls.

When you add the communotron-16 (or any other stock antenna) to the vessel, then at that point Kerbalism too find its own module and stop locking controls.

Starting from version 0.9.9.5, Kerbalism disable its own signal mechanic if RemoteTech is detected.

**Comment by lamont-granquist** [comment]
@ShotgunNinja can this be considered fixed then as long as Kerbalism users are at least on 0.9.9.5?

**Comment by ShotgunNinja** [comment]
@lamont-granquist  Absolutely.
