### ISSUE TITLE
Autopilot spins out of control

### ISSUE THREAD

**Issue by FalcoGer** [RemoteTechnologiesGroup/RemoteTech#607]
Related: #244
Putting a menuever and having it executed by a drone, or even just putting the whole thing on kill rotation will make it spin out of control. SAS works fine, although of course it gets disabled when leaving antenna range.
This issue apparently still persists, although since it hasn't been fixed in a year...

Do not use the root part for orientation but rather the part that is selected for 'control from here' and update that part internally whenever a command to rotate is given.

**Comment by hespziron** [comment]
What do you mean by 'update that part internally' ?
I have the exact same bug.

**Comment by d4rksh4de** [comment]
I was able to reproduce this.

**Comment by FalcoGer** [comment]
@hespziron I mean it should be updated whenever the autopilot wants to do a rotation. Or maybe there is a callback function for when using 'control from here'. And 'that part' is the part that is referenced as 'forward'

**Comment by d4rksh4de** [comment]
I was able to make it spin by placing a docking port on the side of the vessel so that it wasn't aligned with the thrust vector. When the FC executed maneuver, the vessel started spinning.

**Comment by d4rksh4de** [comment]
@FalcoGer can you please upload the craft that is spinning when using kill rotation?

**Comment by PiggyWhiskey** [comment]
I've had a very many crafts spin out of control with the FC.
They've all been without Docking Ports, and the Core is at the top and orientated normally.

Any FC command causes rotation regardless of the vessel

**Comment by KSP-TaxiService** [comment]
Closing, as per #244's closure note
