### ISSUE TITLE
Feature request: Remote control by manned craft

### ISSUE THREAD

**Issue by FalcoGer** [RemoteTechnologiesGroup/RemoteTech#608]
It would be nice to be able to control drones not only when they have a comms link with Mission control, but also when there is a manned spacecraft nearby, such as the vessel that has just deployed a satellite.

**Comment by gioGats** [comment]
https://remotetechnologiesgroup.github.io/RemoteTech/#command-stations

**Comment by amedee** [comment]
Agreed, this feature is already available, I'd vote to close this feature request.
