### ISSUE TITLE
The connection indicator does not scale properly

### ISSUE THREAD

**Issue by tomekpiotrowski** [RemoteTechnologiesGroup/RemoteTech#618]
Reported on the forums: http://forum.kerbalspaceprogram.com/index.php?/topic/139167-112-remotetech-v170-2016-05-06/&do=findComment&comment=2566012

The connection indicator and FC button in the upper left corner does not scale properly with the time controls in the flight screen and map screen

![screenshot1](https://cloud.githubusercontent.com/assets/1452213/15088052/38484946-13ef-11e6-8201-9fb79fb23f89.png)

**Comment by neitsa** [comment]
Couldn't repro anymore (after the fix) with the exact same UI configuration. Closing the issue.
