### ISSUE TITLE
Mod not working at all?

### ISSUE THREAD

**Issue by IvanTheEwok** [RemoteTechnologiesGroup/RemoteTech#620]
Greetings,
I recently installed Remotetech , but aside from adding all the new parts and GUI, it hasn't changes anything. There are no connection lines between the satellites and I can steer any unmanned probes without connection.
I installed it manually. I wanted to do it through Ckan but the mod was not listed there, even though it said it would on the Remotetech forum post.
Thanks!

Edit: I just installed Remotetech 1.7 through Ckan which was released earlier this evening and I'm still having the same problem.

-------------------------------------------

This is a reddit post I made, but I guess I should put it here. I have tried to reinstall different versions several times on the same modded version of KSP.

Here's the list of the mods I run:

![screenshot_11](https://cloud.githubusercontent.com/assets/19232156/15088393/355dc95a-13f3-11e6-990c-c27b209b4783.png)

Thanks!

**Comment by tomekpiotrowski** [comment]
This must be some kind of a collision between mods. Try a fresh KSP install.

**Comment by lamont-granquist** [comment]
might try uninstalling in CKAN then making certain to wipe the GameData/RemoteTech folder manually.  if a CKAN uninstall leaves any files behind then it most likely issues related to not being a clean upgrade.

**Comment by nexsius** [comment]
I have the same issue. Clean KSP installation on Mac OS X without any mods, KSP version 1.1.2. Flight computer button is red, DP-10 don't have any menus, also i don't see any links :( I try to use RT ver. 1.6.9 and 1.7, but i don't have any changes. I just got new antennas and red point in map view  where KSC is situated

**Comment by tomekpiotrowski** [comment]
1.6.9 will not work with KSP 1.1.2, use 1.7.

Does anything suspicious pop up in KSP.log?

**Comment by nexsius** [comment]
I wrote that I early tried to use 1.6.9 with KSP 1.0 (or 1.1 i forgot), then i was update KSP to 1.1.2 and install new version of RT - 1.7. But it still not working.

In KSP.log:
[LOG 21:28:50.922] Load(Assembly): RemoteTech/Plugins/RemoteTech
[LOG 21:28:50.923] AssemblyLoader: Loading assembly at /Users/nexsius/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/RemoteTech/Plugins/RemoteTech.dll
....
[LOG 21:29:45.585] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:29:47.914] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:29:47.914] AddonLoader: Instantiating addon 'RTMainMenu' from assembly 'RemoteTech'
[LOG 21:30:15.307] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:30:17.759] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:30:17.759] AddonLoader: Instantiating addon 'RTSpaceCentre' from assembly 'RemoteTech'
[LOG 21:30:18.010] RemoteTech: Load base settings into object with RemoteTechSettings
[LOG 21:31:32.065] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:31:33.553] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:31:33.554] AddonLoader: Instantiating addon 'RTPartInfoReloader' from assembly 'RemoteTech'
[LOG 21:34:55.700] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:34:58.940] AddonLoader: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 21:34:58.940] AddonLoader: Instantiating addon 'RTCoreFlight' from assembly 'RemoteTech'
[LOG 21:35:00.340] RemoteTech: NetworkManager: SatelliteRegister(Mission Control)
[LOG 21:35:00.367] RemoteTech: RTCore v1.7.0 loaded successfully.
[LOG 21:35:00.368] RemoteTech: SatelliteManager: RegisterProto(Ast. HSJ-227, c4aea14d-f05c-40e8-a634-291770c97948)
[LOG 21:35:00.369] RemoteTech: GetSignalProcessor(Ast. HSJ-227): Check
[LOG 21:35:00.371] RemoteTech: AntennaManager: RegisterProtos(Ast. HSJ-227, c4aea14d-f05c-40e8-a634-291770c97948)
[LOG 21:35:00.372] RemoteTech: SatelliteManager: RegisterProto(Untitled Space Craft, 71a4ad63-a497-4b8d-b09b-99db51005734)
[LOG 21:35:00.372] RemoteTech: GetSignalProcessor(Untitled Space Craft): Check
[LOG 21:35:00.373] RemoteTech: AntennaManager: RegisterProtos(Untitled Space Craft, 71a4ad63-a497-4b8d-b09b-99db51005734)
[LOG 21:35:31.332] RemoteTech: SatelliteManager: OnVesselCreate(be64b17a-61e6-4876-89ce-4f45ba5e7c39, Ast. LWY-112)
[LOG 21:36:02.691] RemoteTech: SatelliteManager: OnVesselCreate(00cdd1e6-7b65-4240-a1ff-593a35902c4f, Ast. GYA-886)

**Comment by nexsius** [comment]
Is dll file important for work?

**Comment by neitsa** [comment]
@IvanTheEwok , @nexsius Have you been able to make RemoteTech to work correctly at some point?

**Comment by pfc** [comment]
I can reproduce this same problem with ksp 1.1.3 and latest RT.  GUI is added to game but nothing else changes from stock game.  Tried with RT being the only mod installed.

**Comment by nexsius** [comment]
I fixed it! 
I really can't imagine that for Mac OS X need Windows dll. 

I placed a dll file called "modulemanager.dll"(I guess) into game_data folder and RT start to work!

**Comment by neitsa** [comment]
@nexsius : that's great, thank you for your feedback 👍 Yes, the `ModuleManager.dll` file is needed, otherwise all the .cfg (configuration files) are not parsed at all. The plugin will load but without its configuration file, it will not work at all.

So I'm closing this issue, I'm glad you were able to make RT work! Next time sure you also copy the module manager into the `GameData` KSP folder (this dll is provided in the `RemoteTech` zip release archive). Other mods also rely on it.
