### ISSUE TITLE
Tracking station dish button not working

### ISSUE THREAD

**Issue by tomekpiotrowski** [RemoteTechnologiesGroup/RemoteTech#622]
Reported by multiple users on the forums: http://forum.kerbalspaceprogram.com/index.php?/topic/139167-112-remotetech-v170-2016-05-06/&do=findComment&comment=2566105

**Comment by neitsa** [comment]
couldn't repro anymore on the current dev branch.

In the tracking station:

![screenshot11](https://cloud.githubusercontent.com/assets/4538670/19221128/4e4bc4e8-8e3d-11e6-8b6e-8935fca735d5.png)

Or in map view while in flight:

![screenshot10](https://cloud.githubusercontent.com/assets/4538670/19221131/598775f0-8e3d-11e6-9d43-e75b07386af9.png)

Closing this issue.
