### ISSUE TITLE
Adding Ground Stations in the config file doesn't work

### ISSUE THREAD

**Issue by tomekpiotrowski** [RemoteTechnologiesGroup/RemoteTech#624]
Multiple reports on the forums: http://forum.kerbalspaceprogram.com/index.php?/topic/139167-112-remotetech-v170-2016-05-06/&do=findComment&comment=2569500

**Comment by panarchist** [comment]
When I add ground stations to the Default Settings config file, they appear in RemoteTech.  If I add them on the Game Save RemoteTech config file, it is overwritten on the game save load by the contents of the Default Settings.  Looks like possibly the defaults are always overwriting the local save, which would explain the behavior seen on the forums since the Default Settings file would normally only contain Mission Control at KSC.

**Comment by KSP-TaxiService** [comment]
Tested on stock KSP 1.2.1586

Test case 1.1: 
1) Ensure KSP is not running and Default_Settings.cfg has single KSC station
2) Add a second ground station to Default_Settings.cfg
3) Launch KSP and start a new save
4) Close the RT Option window
5) Inspect RemoteTech_Settings.cfg

Expected result: The extra station appears in RemoteTech_Settings.cfg
Results: The extra station is present in RemoteTech_Settings.cfg

Test case 1.2: 
1) Ensure KSP is not running and Default_Settings.cfg has single KSC station
2) Add a second ground station to Default_Settings.cfg
3) Launch KSP and start a new save
4) DO NOT close the RT Option window
5) Inspect RemoteTech_Settings.cfg

Expected result: The extra station appears in RemoteTech_Settings.cfg
Results: The extra station is missing in RemoteTech_Settings.cfg

Test case 2.1:
1) Ensure KSP is not running and Default_Settings.cfg has single KSC station
2) Launch KSP and arrive at the main menu
1) Add a second ground station to Default_Settings.cfg
2) Start a new save
3) Close the RT Option window
4) Inspect RemoteTech_Settings.cfg

Expected result: The extra station appears in RemoteTech_Settings.cfg
Results: The extra station is missing in RemoteTech_Settings.cfg

Test case 2.2:
1) Ensure KSP is not running and Default_Settings.cfg has single KSC station
2) Launch KSP and arrive at the main menu
1) Add a second ground station to Default_Settings.cfg
2) Start a new save
3) DO NOT close the RT Option window
4) Inspect RemoteTech_Settings.cfg

Expected result: The extra station appears in RemoteTech_Settings.cfg
Results: The extra station is missing in RemoteTech_Settings.cfg

\----------------------------------------------

Comment:
It looks like there are two copies of Default_Settings in KSP's memory - one read from the Default_Settings file and the other is somehow "built up" during RT's initialisation (perhaps from the default values of some classes?)

**Comment by KSP-TaxiService** [comment]
Test on stock KSP 1.2.1586

Test Case 1: 
1) Ensure KSP is not running and Default_Settings.cfg has single KSC station
2) Add a second ground station to RemoteTech_Settings.cfg of an existing save
3) Launch KSP and load the said save
4) Alt+F12 to read the list of ground stations in the RT debug window (GUID-Reader)

Expected results: The second ground station is there and accepts space connections
Results: Same as above

Test Case 2: 
1) Ensure KSP is idle (main menu) and Default_Settings.cfg has single KSC station
2) Rename the second ground station in RemoteTech_Settings.cfg of an existing save
3) Load the said save
4) Alt+F12 to read the list of ground stations in the RT debug window (GUID-Reader)

Expected results: The second ground station's name is matched to the rename.
Results: Same as above

Test case 3:
1) Ensure KSP is not running and Default_Settings.cfg has single KSC station
2) Launch KSP and arrive at the main menu
3) Add a second ground station to Default_Settings.cfg
4) Start a new save
5) Close the RT Option window
6) Inspect RemoteTech_Settings.cfg of the new save

Expected result: The extra station appears in RemoteTech_Settings.cfg
Results: The extra station is missing in RemoteTech_Settings.cfg

\--------------------------------------

I discover why the Default_Settings.cfg file is ignored. It is merely a template, not meant to be read by RT mod. Poor KSP players edit this file without realising this and wonder why.

I am working on a fix for RT to read the default settings when creating a new save OR reverting back to default values in an existing save.
