### ISSUE TITLE
Action Buttons disabled all the time

### ISSUE THREAD

**Issue by WildLynxDev** [RemoteTechnologiesGroup/RemoteTech#629]
Craft is under control, icon green, etc.
But action buttons are disabled and cannot be clicked. Removing RT fixes the problem with other mods still there.
Actions still can be activated with hot keys  U G B
Screen:
http://i.imgur.com/P7B8Jqr.png
KSP 1.1.5, Linux Mageia 5 x64, { RT 1.0.7 || 544 || 546 }

**Comment by tomekpiotrowski** [comment]
The same as #605
