### ISSUE TITLE
can't transmit science from launchpad when using Launch Stability Enhancers

### ISSUE THREAD

**Issue by gnivler** [RemoteTechnologiesGroup/RemoteTech#632]
This craft is setup for Action Button 1 to start the experiment, and when selecting Transmit there is a message that the Launch Stability Enhancer successfully sent the data.  No science is returned and the experiment continues to report the same available science results when retried.  This seems to happen for all experiments and those which can't be reused are consumed by the failure.  Possibly related to #613 

The only output I can find is from the lvl 1 debug, below.  Using KSP 1.1.2 with RT dev 546.

[Auto-Saved Ship.craft.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/265336/Auto-Saved.Ship.craft.txt)

![image](https://cloud.githubusercontent.com/assets/18452645/15277474/e7029c00-1ac2-11e6-8ad4-e22e38fca189.png)

**Comment by neitsa** [comment]
This bug falls under the auto-magically fixed bug category... :)

Tested on **KSP pre-release 1.2.0.1564**

On the launch pad, custom action triggered, `2.4` science points to be recovered after transmission:

![screenshot0](https://cloud.githubusercontent.com/assets/4538670/19136399/af2fc5b2-8b6c-11e6-8d9e-9f5e32eed3d8.png)


Transmitting science (debug windows shows that a transmission is occurring):

![screenshot1](https://cloud.githubusercontent.com/assets/4538670/19136421/d611b4b0-8b6c-11e6-9eb6-4c7fa60ad602.png)

And then, retrying with the same experiment, only `0.1` science to be recovered:

![screenshot2](https://cloud.githubusercontent.com/assets/4538670/19136436/f36b2a14-8b6c-11e6-9ac1-ea981ead33c3.png)

Going to science center after that shows `2.5`  science recovered in total which is correct, and no transmission problem occurred.
