### ISSUE TITLE
Communotron HG-55 is not listed on the RemoteTech wiki

### ISSUE THREAD

**Issue by ttencate** [RemoteTechnologiesGroup/RemoteTech#635]
The [Communotron HG-55](http://wiki.kerbalspaceprogram.com/wiki/Communotron_HG-55) got added to stock KSP in version 1.1. However, it is not listed in the [RemoteTech parts listing](https://remotetechnologiesgroup.github.io/RemoteTech/guide/parts/). Does this antenna even work with RT? What are its characteristics? If somebody could spell them out here, I'd be happy to add them to the wiki.

**Comment by Zhetaan** [comment]
It works, but I don't have the cfg handy at the moment.  Here's what's available right here:

Summary:

Range:  25 Gm
Cone Angle:  0.12 degrees
EC Cost:  1.04 ec/s (62.4 ec/min)
Breakable
Max Dynamic Pressure:  6 kN/m^2

I'm not sure how to translate the transmission numbers, but they are different from the other dishes.  It appears that the dish costs more per packet to send data, but it sends such large packets that the overall effect is that it's cheaper, which fits with its intended behaviour.  I'll flesh this out with the rest of the information when I get to a KSP computer.

From RemoteTech_Squad_Antennas.cfg:

@PART[HighGainAntenna]:FOR[RemoteTech]
{
	!MODULE[ModuleDataTransmitter] {}
	
	@MODULE[ModuleAnimateGeneric]
	{
		%allowManualControl = false
	}
	
	%MODULE[ModuleRTAntenna] {
		%Mode0DishRange = 0
		%Mode1DishRange = 25000000000
		%EnergyCost = 1.04
		%MaxQ = 6000
		%DishAngle = 0.12
		
		%DeployFxModules = 0
		%ProgressFxModules = 1
		
		%TRANSMITTER {
			%PacketInterval = 0.15
			%PacketSize = 3
			%PacketResourceCost = 20.0
		}
	}
	
	%MODULE[ModuleSPUPassive] {}
}

**Comment by KSP-TaxiService** [comment]
There are some balance changes to both stock and RemoteTech antennas since the first post. I revised the whole page of the antennas in both content and styles (simplify unnecessary details, beautify presentation and update pictures).
