### ISSUE TITLE
allow FC to be used with local control?

### ISSUE THREAD

**Issue by TheToric** [RemoteTechnologiesGroup/RemoteTech#636]
currently, the flight  computer is infinity better than the inbuilt SAS at holding heading and such, as well as being a useful ion engine autopilot. however, you loose all of these features as soon as you put a kerbal on your craft. would it be possible to enable it on craft with kerbals aboard? maybe require a probe core or KER (if installed) part in order to do the computations?

**Comment by KSP-TaxiService** [comment]
Hmm.. Currently, a manned vessel has no access to Flight Computer. But if a probe core is attached to the vessel, Kerbals can utilise FC, like this picture below.
![1](https://user-images.githubusercontent.com/22871614/44296245-5f9eed80-a2ed-11e8-963f-bee93ff5efa5.PNG)

I wonder if this is original intention?

**Comment by KSP-TaxiService** [comment]
Closing as this feature already exists since some time ago.
