### ISSUE TITLE
karibou radial probe needs SPU

### ISSUE THREAD

**Issue by toric55** [RemoteTechnologiesGroup/RemoteTech#637]
from karibou rover pack by roverdude.

**Comment by neitsa** [comment]
@BobPalmer has already a [patch available](https://github.com/BobPalmer/Karibou/blob/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/Karibou/Patches/RemoteTech_USI_Karibou_Probe.cfg) for RemoteTech (thanks to him, @Vranir and @Li0n-0 for making this MM config!), so I'm closing this issue.

❤️ Karibou Rover.
