### ISSUE TITLE
Latest DEV build sometimes cannot compute Transfer to other planet

### ISSUE THREAD

**Issue by mario-ragucci-sp** [RemoteTechnologiesGroup/RemoteTech#642]
Hi,
I am using latest DEV build (by this time 550) and the functionality "advanced transfer to another planet" is not working correctly for most of the time (means, I can use this functionality sometimes, but most of the time it does not work). 
Here is the log of what is happening when I try to compute a transfer from Kerbin to Duna, please note that lines like "[LOG 17:44:14.470] E is NaN! tA: 3.14159265358979, e = 728.16389303854
" are spamming my logfile, ultimatively I need to quit the game.

[EXC 17:43:47.655] ArgumentException: Getting control 6's position in a group with only 6 controls when doing Repaint
Aborting
	UnityEngine.GUILayoutGroup.GetNext ()
	UnityEngine.GUILayoutUtility.DoGetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayoutUtility.GetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.DoButton (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.Button (System.String text, UnityEngine.GUILayoutOption[] options)
	MuMech.MechJebModuleManeuverPlanner.WindowGUI (Int32 windowID)
	MuMech.DisplayModule.ProfiledWindowGUI (Int32 windowID)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 17:44:07.716] [SCANsat] Height Map Of [Eve] Completed...
[LOG 17:44:14.448] E is NaN! tA: 3.14159265358979, e = 4504524.20032019
LOG 17:43:10.980] RemoteTech: ProtoAntenna(Name: Commu672934.01592499
[LOG 17:44:14.449] E is NaN! tA: 3.14159265358979, e = 27142.1491000248
[LOG 17:44:14.449] E is NaN! tA: 3.14159265358979, e = 26645.6093504206
[LOG 17:44:14.449] E is NaN! tA: 3.14159265358979, e = 4843453.06533784
[LOG 17:44:14.449] E is NaN! tA: 3.14159265358979, e = 7345.47832439919
[LOG 17:44:14.449] E is NaN! tA: 3.14159265358979, e = 25662.3426251474
[LOG 17:44:14.450] E is NaN! tA: 3.14159265358979, e = 1241.25793572692
[LOG 17:44:14.450] E is NaN! tA: 3.14159265358979, e = 1989.59414340732
[LOG 17:44:14.451] E is NaN! tA: 3.14159265358979, e = 3235.78207175495
[LOG 17:44:14.451] E is NaN! tA: 3.14159265358979, e = 7077.55824324761
[EXC 17:44:14.451] InvalidOperationException: Collection was modified; enumeration operation may not execute.
	System.Collections.Generic.List`1+Enumerator[HighLogic+LogEntry].VerifyState ()
	System.Collections.Generic.List`1+Enumerator[HighLogic+LogEntry].MoveNext ()
	DebugToolbar.WindowDebug ()
	DebugToolbar.Window (Int32 id)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 17:44:14.452] E is NaN! tA: 3.14159265358979, e = 304.730483788437
[LOG 17:44:14.452] E is NaN! tA: 3.14159265358979, e = 8169.34794639538
[LOG 17:44:14.452] E is NaN! tA: 3.14159265358979, e = 5366841.6383965
[LOG 17:44:14.453] E is NaN! tA: 3.14159265358979, e = 620.207232084049
[LOG 17:44:14.453] E is NaN! tA: 3.14159265358979, e = 373.495672421147
[LOG 17:44:14.454] E is NaN! tA: 3.14159265358979, e = 3799.06990297826
[LOG 17:44:14.454] E is NaN! tA: 3.14159265358979, e = 3175.13402428775
[LOG 17:44:14.456] E is NaN! tA: 3.14159265358979, e = 5544992.15725616
[EXC 17:44:14.457] ArgumentException: GUILayout: Mismatched LayoutGroup.Repaint
	UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType)
	UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options)
	UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options)
	MuMech.MechJebModuleManeuverPlanner.WindowGUI (Int32 windowID)
	MuMech.DisplayModule.ProfiledWindowGUI (Int32 windowID)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[LOG 17:44:14.457] E is NaN! tA: 3.14159265358979, e = 253.721252226822
[LOG 17:44:14.457] E is NaN! tA: 3.14159265358979, e = 31223.7990200237
[LOG 17:44:14.458] E is NaN! tA: 3.14159265358979, e = 469.333477234859
[LOG 17:44:14.458] E is NaN! tA: 3.14159265358979, e = 3928.17703183922
[LOG 17:44:14.459] E is NaN! tA: 3.14159265358979, e = 1356.97907661934
[LOG 17:44:14.459] E is NaN! tA: 3.14159265358979, e = 983.586839276813
[LOG 17:44:14.460] E is NaN! tA: 3.14159265358979, e = 8591.78148376695
[LOG 17:44:14.463] E is NaN! tA: 3.14159265358979, e = 9020.66936822898
[ERR 17:44:14.463] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)

[LOG 17:44:14.464] E is NaN! tA: 3.14159265358979, e = 1333.56371065167
[LOG 17:44:14.464] E is NaN! tA: 3.14159265358979, e = 5906400.151337
[LOG 17:44:14.465] E is NaN! tA: 3.14159265358979, e = 967.008008039963
[LOG 17:44:14.465] E is NaN! tA: 3.14159265358979, e = 679.48425299766
[LOG 17:44:14.465] E is NaN! tA: 3.14159265358979, e = 278.205568252983
[LOG 17:44:14.466] E is NaN! tA: 3.14159265358979, e = 3863.45663479187
[LOG 17:44:14.466] E is NaN! tA: 3.14159265358979, e = 4058.59239042885
[LOG 17:44:14.467] E is NaN! tA: 3.14159265358979, e = 917.810940101315
[LOG 17:44:14.467] E is NaN! tA: 3.14159265358979, e = 9165.00093021749
[LOG 17:44:14.468] E is NaN! tA: 3.14159265358979, e = 273.249996757949
[LOG 17:44:14.468] E is NaN! tA: 3.14159265358979, e = 402.30254819761
[LOG 17:44:14.469] E is NaN! tA: 3.14159265358979, e = 124.959218439377
[LOG 17:44:14.469] E is NaN! tA: 3.14159265358979, e = 523.998037486051
[LOG 17:44:14.470] E is NaN! tA: 3.14159265358979, e = 728.16389303854
.......

**Comment by bfrobin446** [comment]
This is the issue tracker for RemoteTech. We aren't able to provide support for MechJeb here.

 MechJeb's issue tracker is at https://github.com/MuMech/MechJeb2/issues. If you're still experiencing this problem with the current development version of MechJeb, you may wish to report it there.
