### ISSUE TITLE
The Yellow Antenna control button in the Tracking station does nothing.

### ISSUE THREAD

**Issue by Zerg-152** [RemoteTechnologiesGroup/RemoteTech#644]
![untitled](https://cloud.githubusercontent.com/assets/19936069/16054465/f320e260-3275-11e6-96ad-f598a9bc1fb3.png)
Not sure if this is a known issue or not, but the button used to work in previous versions, I could assign all the antenna targets without ever switching to all my vessels. Now clicking the yellowish antenna-control button in the Tracking station interface does nothing. Any fix?

**Comment by d4rksh4de** [comment]
This is already fixed in #622 and is available in latest dev build.
