### ISSUE TITLE
Release for 1.1.3

### ISSUE THREAD

**Issue by james3838** [RemoteTechnologiesGroup/RemoteTech#645]
Just need to recompile against 1.1.3 KSP dll's to resolve missing method exceptions:

MissingMethodException: Method not found: 'TimeWarp.SetRate'.
  at RemoteTech.FlightComputer.FlightComputer.OnUpdate () [0x00000] in <filename unknown>:0 

  at RemoteTech.Modules.ModuleSPU.Update () [0x00000] in <filename unknown>:0

**Comment by MrCamoga** [comment]
I can't control any unmanned vessel while the remotetech mod is actived :(:(:(

**Comment by JLLeitschuh** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/139167-112-remotetech-v170-2016-05-06/&do=findComment&comment=2643094

**Comment by james3838** [comment]
BTW - I pulled and built and confirmed all is working with new binaries.  The form code change is unnecessary (3rd param defaults to true).

**Comment by d4rksh4de** [comment]
Fixed by #653. Please try the latest dev build.
