### ISSUE TITLE
Cannot Stage Unmanned Ship

### ISSUE THREAD

**Issue by TheRealCodeCube** [RemoteTechnologiesGroup/RemoteTech#660]
I have created a test vehicle (and uninstalled all other mods except RemoteTech) to test this. It has power, antenna(s), and an unmanned control module. The connection indicator in the top-left says there is a connection, with a 0-second delay. However, the stage light in the bottom-left remains purple, and commands sent to the rocket are remaining in the flight computer queue without being executed. I have attached a screenshot showing this. If I disable remotetech from the menu option, this problem persists, although I can manually activate the engine with the right-click menu. If I uninstall remotetech, everything works fine. I am using the 64-bit version of KSP 1.1.2 on Fedora Linux.
![screenshot from 2016-06-30 12-36-18](https://cloud.githubusercontent.com/assets/9629610/16501762/e4804c22-3ebf-11e6-8780-47660eb2e7e0.png)

**Comment by soberstadt** [comment]
What version of RemoteTech are you using? I had a simular issue because I was using the version listed on the forum instead of the 554 version.

**Comment by TheRealCodeCube** [comment]
I am using the forum version as well. I will try with the latest version.

**Comment by soberstadt** [comment]
Yeah, seems like a number of people have been having these issues: #645

**Comment by TheRealCodeCube** [comment]
The newer version does not have the issue. My apologies for not looking at the other issues.
