### ISSUE TITLE
Reflectron KR-14 Freezes after transmitting science

### ISSUE THREAD

**Issue by KalynnDarcy** [RemoteTechnologiesGroup/RemoteTech#666]
I've got a probe at Jupiter (Using RSS and realism overhaul) with the Reflectron KR-14 on it. Whenever I perform a science experiment and transmit it back, the transmission is successful and the science is added, but the dish status then gets stuck on 'uploading data.' Any attempts to upload more experiments are ignored, and it only resets and lets me transmit again if I go back to the space center and then back to the probe. 

Not sure if this is related to remote tech or RO, as I know it changes some of the configs, but as far as I can work out, it only adjusts range, and packet size/cost details, neither of which I can figure causing thig bug
![220200_screenshots_20160713143031_1](https://cloud.githubusercontent.com/assets/16504935/16792364/f5a6084c-4906-11e6-803d-ac7fe38596d6.jpg)

**Comment by KSP-TaxiService** [comment]
This may be related to the issue #667 of the science data transmission, which didn't really complete, despite the visual completion.

**Comment by KSP-TaxiService** [comment]
@KalynnDarcy Hi, can you check if the new RT 1.8.8, contained few fixes related to science data transmission, resolves this bug on your side?

Thanks!

**Comment by KSP-TaxiService** [comment]
Hi, 

Given that the bug seems to be only reproducible under very narrow set of conditions and few transmission-related fixes were pushed recently, this issue will be set to closed.

You may respond to this, should this bug be still there.
