### ISSUE TITLE
UI Scale Not Configurable

### ISSUE THREAD

**Issue by evan2645** [RemoteTechnologiesGroup/RemoteTech#668]
I have been looking around for how to scale the remotetech in-game UI, with little success. Apologies if this is a duplicate

I have my game configured to render natively on a retina screen, though the high resolution has caused various UI scaling issues. Remotetech is the only piece I have been unable to scale. Mechjeb has a feature to scale its UI, and the rest of the in-game panels are also configurable. It's basically impossible for me to read the signal delay value (amongst others) at its current size.

Am I missing something? Is this available already, or perhaps on the way?

**Comment by neitsa** [comment]
@evan2645 Is this issue still present with the last RemoTech version and KSP 1.1.3. Would it be possible to add a screenshot so I could have an idea of what is wrong?

**Comment by evan2645** [comment]
Just tried with 1.1.3 and what I assume is latest RemoteTech 1.7.1, and the issue is still present. Since I've had to manually scale most other panels (in-game panels typically scale individually through the config file, mechjeb scaled through in-game option in settings), I would assume that the "fix" would be the introduction of a new configurable.

I can send my config and/or screenshots of how to config mechjeb for this UI scaling if that helps. Please find a screenshot here, take note of the RemoteTech panel size in the top left corner of the screen: ![Imgur](http://i.imgur.com/0aVSdOA.jpg)

**Comment by neitsa** [comment]
Hi @evan2645 !

> 1.1.3 and what I assume is latest RemoteTech 1.7.1

Yep, that's the latest official release.

Thank you for the screenshot, I wasn't sure  if the delay indicator was displaced and/or if the the text was not scaled properly. This helps a lot!

I don't think your config is required, I'll take a look to see what's wrong in the code and if I'm stuck I'll ask you to upload your config somewhere, but that shouldn't be required.

I'm thinking about fixing this issue for the upcoming release (targeting KSP 1.2).

Thank you for your report and your time!
