### ISSUE TITLE
Player's Guide contains dead link to Advanced Settings

### ISSUE THREAD

**Issue by HupfderFloh** [RemoteTechnologiesGroup/RemoteTech#669]
In chapter http://remotetechnologiesgroup.github.io/RemoteTech/guide/overview/#range of the player's guide, there is a link pointing to http://remotetechnologiesgroup.github.io/RemoteTech/modders/settings/#alternative-rules that should be updated to http://remotetechnologiesgroup.github.io/RemoteTech/guide/settings/#alternative-rules

**Comment by neitsa** [comment]
@ahmedcharles Thank you for your fix; was merged some days ago, closing the issue.
