### ISSUE TITLE
Cannot use the "Jump to ship" in KAC alarms

### ISSUE THREAD

**Issue by petersohn** [RemoteTechnologiesGroup/RemoteTech#676]
When I click on Execute Node in the Flight Computer, it adds an alarm to KAC. However, I cannot use the "Jump to ship" option for this alarm, as I can for alarms I add manually using KAC.

**Comment by jwolff52** [comment]
This shouldnt be too difficult of a fix. It appears that when an alarm is created a vessel is not set. A cursory glance at the KAC API say this should only take a few lines of code. I'm at work right now, but would gladly create a PR when I get home!

**Comment by jwolff52** [comment]
OK, little more code than I thought it would be, but I think what I have will work. Once I get it tested will create a PR!

**Comment by jwolff52** [comment]
OK maybe someone could help *me* out...

I am running the most recent build of the `feature/kac-jumptoship` branch in [my fork](https://github.com/jwolff52/RemoteTech/tree/feature/kac-jumptoship).

Any changes I have made have been based on the KACWrapper.cs class ([found here](http://triggerau.github.io/KerbalAlarmClock/api.html)).

Currently I am getting the following error when the code on KerbalAlarmClockAPI.cs:169 is ran  
`Cannot cast from source type to destination type.`

When I log `actualAlarmList.GetType()` it reports it as 'System.Reflection.MonoField`

I do not really have a lot of C# experience let alone working on KSP Mods and even after some looking around on google I wasn't able to find anything like this. It really just doesn't make any sense to me as the code is directly copied over except for the reference to `KACType` is `assemblyType` in our code.

**Comment by neitsa** [comment]
@jwolff52 : as KAC is out for 1.2 I'll also check this issue and give you some feedback on what I get (or not) from the code. I'll keep this thread updated.
