### ISSUE TITLE
RT not working

### ISSUE THREAD

**Issue by pfc** [RemoteTechnologiesGroup/RemoteTech#681]
Using stock 1.1.3 KSP the 1.7.1 RT release does seem to get loaded but does nothing other than add the RT GUI, none of the game mechanics are changed.  Using the latest development branch leads to KSP not loading past GigaDish1 part.  I installed the GameData folder as is, the ModuleManager dll that comes with each release was also included.

Not all that familiar with KSP debugging but if there's anything I can do to help narrow down the problem please let me know.

**Comment by neitsa** [comment]
hi @pfc!

could you try to remove the existing RemoteTech folder completely and reinstall the one from the latest release archive for KSP 1.1.3 ([RT 1.7.1 here](https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/1.7.1)).

Also make sure you copy the Module Manager dll with the same exact version (2.6.25) from the archive (as some mods have tendencies to replace it) at the root of the `\GameData` folder.

Try to remove the config `<KSP_INSTALL_ROOT_FOLDER>\saves\<save_name>\RemoteTech_Settings.cfg` (it will be replaced when you restart your game).

If that still doesn't work, complete log files would help:
* Start the game with RT properly (re)installed
* Load your save
* Try to build a simple vessel (or fly an existing one) with RT antennas. 
 * Probe core + DP-10 antenna is enough
 * On the launchpad is enough if you haven't any flying vessel
* check if that work or not
* Quit the game
* Get `KSP.log` in the root KSP installation folder.
* Get output_log file (located in `<KSP_INSTALL_ROOT_FOLDER>\KSP_x64_Data\output_log.txt`)

(for ex. you can paste them on http://pastebin.com/ and give us a link to it, or attach them)


**Note**: the current `develop` branch here targets KSP 1.2 and doesn't work with KSP 1.1.3.

**Comment by pfc** [comment]
Here's what I've tried:

delete RT files from /GameData
delete RemoteTech_Settings.cfg
Install RT 1.7.1 from link
Result: Game loads, RT GUI works, rest of RT doesn't work.
log: http://pasted.co/29b624d1

I'm running KSP on linux through wine.  Tried both win XP and win 7 emulation in case there was a windows incompatibility with the dll, still same results.

**Comment by neitsa** [comment]
@pfc : got it, you're actually playing KSP 1.1.0. From your log file (line 117 and 131):

> [KSP Version]: 1.1.0.1230 (WindowsPlayer) (x64) ==============================
> ******* Log Initiated for Kerbal Space Program - 1.1.0.1230 (WindowsPlayer) *******

Also, check what you see in the bottom right corner on the main menu screen (after the loading screen), to confirm this version, but the log file is clear that you **aren't playing 1.1.3**.

Here's what I have on my KSP 1.1.3:

> [KSP Version]: 1.1.3.1289 (WindowsPlayer) (x64) ==============================
>******* Log Initiated for Kerbal Space Program - 1.1.3.1289 (WindowsPlayer) *******

RT 1.7.1 is for KSP 1.1.3, not 1.1.0.

If you still want to play on 1.1.0 I think you need [RT 1.6.11](https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/1.6.11), otherwise if you want to use RT 1.7.1, you'll need to update to KSP 1.1.3.

**Comment by neitsa** [comment]
@pfc : once you have upgraded to KSP 1.1.3 (or tested RT 1.6.11 with KSP 1.1.0) please tell me if that works or not.

**Comment by neitsa** [comment]
@pfc : I'm closing this issue as you were testing on an older version with mismatched versions of RT and KSP. Please open a new issue when you have upgraded or are using the right RT version that matches your KSP install (and if that still doesn't work).
