### ISSUE TITLE
Satellite have no connection

### ISSUE THREAD

**Issue by sviat9440** [RemoteTechnologiesGroup/RemoteTech#696]
Why my sattelite have no connection?
![image](https://cloud.githubusercontent.com/assets/13107421/20175898/379fdc52-a756-11e6-859c-f119ac7c3c1d.png)

Is CS 4
![image](https://cloud.githubusercontent.com/assets/13107421/20175925/5a59deaa-a756-11e6-959b-bde756c2d4eb.png)

Is CS 3
![image](https://cloud.githubusercontent.com/assets/13107421/20175960/785f12bc-a756-11e6-9e05-7c8f325deeac.png)

**Comment by sviat9440** [comment]
![image](https://cloud.githubusercontent.com/assets/13107421/20175992/a01b6f08-a756-11e6-93a6-8b58271d8b53.png)
From CS 4 to CS 3 exists connection, but from CS 3 to CS 4 not exists.
Sorry for my bad english

**Comment by sviat9440** [comment]
from CS 3 to CS 4 exists connection, but connection unstable
![image](https://cloud.githubusercontent.com/assets/13107421/20176204/c21ac2b0-a757-11e6-9b0f-4c70b9f90b73.png)
![image](https://cloud.githubusercontent.com/assets/13107421/20176211/cf8f63ce-a757-11e6-9f45-18d7c830bb3e.png)

**Comment by KSP-TaxiService** [comment]
Hi sviat9440,

It is difficult to diagnose this issue from your screenshots alone. Please describe your KSP install (1.2.1, x64 etc) and supply Output_log.txt and Persistent Save as this [link](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports).

**Comment by sviat9440** [comment]
Well, then I'll try to use another type of antenna, if something goes wrong, write. Thank you.

**Comment by sviat9440** [comment]
![image](https://cloud.githubusercontent.com/assets/13107421/20187307/d290ad94-a784-11e6-91c8-1e0b883b1abb.png)
No. Problem not solved. In the screenshot, four the same satellites. But the third satellite won't connect to network

**Comment by neitsa** [comment]
Thanks for the report @sviat9440!

Could you send us everything we need to reproduce your problem [as explained in this link](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports)?

Follow carefully what is explained here so we can take a look at your problem (without a full bug report we just can do anything on our side, especially when it comes to connection problems). Thank you!

**Comment by sviat9440** [comment]
O.S: Windows 10 64bit
KSP: 1.2.0.1586 64bit

Problem: I don't know why I have no contact with certain satellites.
Logs: [KSP.log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/584036/KSP.log.txt)
Installed Mods: ![image](https://cloud.githubusercontent.com/assets/13107421/20187906/52c3d0a2-a787-11e6-83d2-86280812f636.png)
Persistent Save: https://yadi.sk/d/4vAsw0HJyMXUz

**Comment by neitsa** [comment]
Thanks a lot @sviat9440 for your full bug report ! We'll take a look ASAP.

**Comment by sviat9440** [comment]
I'm not sure this is a bug, maybe I just don't know how to use mod

**Comment by neitsa** [comment]
No problem at all 😄 We prefer to have a false bug report rather than having a real bug lurking incognito. 

Whether or not it's a bug we'll tell you what's wrong.

**Comment by KSP-TaxiService** [comment]
Tested on the stock KSP 1.2.1604 with RT 1.8.0 release.

@sviat9440 Don't worry, it is not a bug. You are indeed learning how to use RemoteTech 👍. Your problem is all of your antennas (Comms DTS-M1) were targeted at the active vessel. An active vessel is the current vessel you are piloting in flight.

Here's the picture after I reconfigure each satellite's three antennas to target each of the other three satellites.

![magic](https://cloud.githubusercontent.com/assets/22871614/20217700/feaa50f6-a85b-11e6-8bac-f123236fde3f.png)

**Comment by sviat9440** [comment]
can you then add the mode "repeater", which will receive data from connected to kerbin with the satellite, and pass to "Active vessel"?

**Comment by KSP-TaxiService** [comment]
No need to do it. Set one of your idle/ unused antennas of each satellite to point at active vessel.

Remember RemoteTech is meant for hardcore playing. KSP's CommNet is RemoteTech Lite.

**Comment by sviat9440** [comment]
ok, tnx
