### ISSUE TITLE
1.8.2 Antenna Ec usage not displayed in VAB

### ISSUE THREAD

**Issue by muppet9876** [RemoteTechnologiesGroup/RemoteTech#707]
In the VAB the game does not know Antenna patched with RT module uses electricity.

On fresh install with Remote tech and Module manager attach a probe, battery, solar panel and antenna. Check the Engineers Report for issue message that Ec is generated but not used. Attach a light, message goes away.

Install Ampyear mod, antenna are not in list of Ec users. 

To be clear, Ec is used in flight scene when antenna is active. This just seems to be a problem in construction scene.

**Comment by YamoriYuki** [comment]
@muppet9876 Hi and thank you for your report. A patch to implement stock resource consumption behavior and interface is currently being tested. It fixes Engineers Report.
As for AmpYear, the author needs to fix his code. More details in his issue JPLRepo/AmpYear#54
