### ISSUE TITLE
stuck on load

### ISSUE THREAD

**Issue by Commissar0617** [RemoteTechnologiesGroup/RemoteTech#712]
https://www.dropbox.com/s/r3b8sbbx0fgb9cd/KSP.log?dl=0
https://www.dropbox.com/s/uvofhf2do4h0uoa/output_log.txt?dl=0

sticks on every load, at the same medium dish antenna. *just* updated my module manager. worked fine prior, but other mods were broken

**Comment by KSP-TaxiService** [comment]
Thank you for this bug report. It appears that the medium dish antenna (KSP's Communotron DTS-M1) may be corrupted. Can you run Steam's integrity verification of KSP from Properties window, please?

**Comment by PhineasFreak** [comment]
Generally you have a ton of errors from USI, StageRecovery, TestFlight, Community Resource Pack (probably installed twice), Infernal Robotics, StationScience and more.

For the specific error has probably something to do with the VSR antenna models, as it fails to render a drag cube.

**Comment by YamoriYuki** [comment]
There's also this:
```File error:
Out of memory
  at (wrapper managed-to-native) object:__icall_wrapper_mono_array_new_specific (intptr,int)
  at PartReader.ReadAnimation (System.IO.BinaryReader br, UnityEngine.GameObject o) [0x00000] in <filename unknown>:0 
  at PartReader.ReadChild (System.IO.BinaryReader br, UnityEngine.Transform parent) [0x00000] in <filename unknown>:0 
  at PartReader.ReadChild (System.IO.BinaryReader br, UnityEngine.Transform parent) [0x00000] in <filename unknown>:0 
  at PartReader.Read (.UrlFile file) [0x00000] in <filename unknown>:0```
And after the last error about `MediumDishAntenna` there's this
```FileNotFoundException: Could not load file or assembly 'KSPUtil, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.```

Looks like your KSP install is broken is some way.
Could you move all the mods out of KSP, check integrity (or preferably delete an reinstall KSP) and start adding them back one by one?
I would suggest starting with mods adding features, then mods that add parts.

**Comment by KSP-TaxiService** [comment]
@Commissar0617 Have you resolved the multiple problems of mod/installation corruption found in your attached logs?

**Comment by Commissar0617** [comment]
yes. all resolved. though i closed this... lol
 

    On Saturday, January 21, 2017 7:56 AM, TaxiService <notifications@github.com> wrote:
 

 @Commissar0617 Have you resolved the multiple problems of mod/installation corruption found in your attached logs?—
