### ISSUE TITLE
Mission Control Origin Point not Located On Kerbin when using some Kopernicus maps

### ISSUE THREAD

**Issue by mikeloeven** [RemoteTechnologiesGroup/RemoteTech#718]
I was having an issue where my ships had no connection on the launch pad after installing a kopernicus map. when Viewing the tracking center there is no longer a red dot over the tracking station. I am wondering if the fact that some worlds actually alter kerbin's position and orbit, Is it possible that the space center's origin point was not moved with the planet and is now somewhere out in deep space? if so is there any way to fix this? The issue might be something completely different either way I cant launch anything at the moment

Update 
Issue Confirmed: changing ground stations to always visible proved that mission control is on a completely different planet from the space center

**Comment by KSP-TaxiService** [comment]
Hi,

We have one or two bug reports on the missing mission control on Kerbin in past. As these reports eventually discovered, you are spot in the mission control being on a different planet. The mission control's celestial body index is set to 1 (modifiable in `Default_Settings.cfg` or `RemoteTech_Settings.cfg`), which corresponds the Kerbin. However, some Kopernicus maps completely delete/add/modify the planets and thus displace Kerbin from the index 1 (and the mission control would be on the new resident planet).

This is out of our hands because we can't force the map authors to keep Kerbin's index at 1. At best, the authors need to issue a MM patch along with the maps for RemoteTech to change the `Body` of every ground station.

**Comment by mikeloeven** [comment]
Alright I'll try looking up kerbins new index and changing it in the configuration files thanks for the advice hopefully that works

**Comment by mikeloeven** [comment]
I dont see any variables for celestial body index in the kopernicus configs does this correspond to flightGlobalsIndex?

**Comment by KSP-TaxiService** [comment]
Yup, each celestial body uses this `flightGlobalsIndex` variable (this is also KSP's variable too).

**Comment by mikeloeven** [comment]
I am surprised its not possible to just look up where the space center is and automatically set the index or is there something preventing this in the game code ?

**Comment by mikeloeven** [comment]
Just tried setting the Body variable to that value but it didn't work I am stumped how do I determine the new index ?

**Comment by KSP-TaxiService** [comment]
I have some idea of extracting the index of the designated body but I need few names of those incompatible maps so as to check if the idea would work on those maps.

I am afraid you are on own in finding out the new index. I never interact with kopernicus mods before.

**Comment by mikeloeven** [comment]
This is tha map i'm using right now

http://forum.kerbalspaceprogram.com/index.php?/topic/154828-122-kerbol-starsystem-v05/

**Comment by YamoriYuki** [comment]
@KSP-TaxiService
I agree on the MM patch suggestion. Should we push this info to other modders actively somehow?

**Comment by KSP-TaxiService** [comment]
@mikeloeven KSP's KSC does not have any information regarding its resident planet. But it does have FlightGlobals.Homeworld stuff that I take advantage of to add a simple verification on the Mission Control. It will update the Mission Control's body index to the KSP's homeworld index if it detects it is on wrong planet. Thank you for pointing me to the right direction!

By the way, if you are still using Kerbol-System map, the body index for Kerbin is `4`. The body index `1` is the brown gas giant, seen in the main menu scene.

@YamoriYuki With this check added, I will drop a friendly message on map/system modders' threads whenever a new bug report shows up on this. However, the modders will still have to provide MM patches for extra ground stations they added. It is possible that extra ground stations could be placed on other planets but I guarantee the Mission Control will be always on the Kerbin/Earth/Homeworld.
