### ISSUE TITLE
The settings Icon dissapear.

### ISSUE THREAD

**Issue by GonDragon** [RemoteTechnologiesGroup/RemoteTech#720]
OS: Windows 10  (10.0.0) 64bit
Kerbal Space Program - 1.2.2.1622 (WindowsPlayer x64)

**Issue:** After enter the game, the RTsettings icons can't be founded. This happends since the last update (RemoteTech-1.8.5)

I searched trough the log, and maybe this is relevant to this issue:

````
[EXC 00:18:42.328] NullReferenceException: Object reference not set to an instance of an object
    RemoteTech.Settings.Load ()
    RemoteTech.RTSettings.get_Instance ()
    RemoteTech.UI.OptionWindow.get_mSettings ()
    RemoteTech.UI.OptionWindow.initalAssets ()
    RemoteTech.UI.OptionWindow..ctor ()
    RemoteTech.RTSpaceCentre.Start ()
````

This is the entire log:
[https://www.dropbox.com/s/zepif445cpa6r2b/KSP.log?dl=0](url)

weights 20 Mb for the other issue that I submited.

**Comment by YamoriYuki** [comment]
This is a second effect of a bug that also causes #719
