### ISSUE TITLE
1.8.6 Breaks KOS

### ISSUE THREAD

**Issue by ShaunDove** [RemoteTechnologiesGroup/RemoteTech#721]
Launching a vessel with no deployed Omni.  As soon as it leaves range of KSC (3km) it loses control and drops from the sky.  This is a new feature for 1.8.6.

**Comment by ShaunDove** [comment]
In an effort to get clean logs I removed and reinstalled remote tech, and started a new sandbox game.  Can no-longer reproduce in either the new game or an old one.  I'm either mistaken or resetting fixed the issue.  Closing.

**Comment by KSP-TaxiService** [comment]
@ShaunDove 
(I was writing an initial response while downloading kOS mod and simple launch script to check)

Nevertheless, thanks for reporting a potential bug. I ran KSP 1.2.2 with kOS 1.0.3 and RT 1.8.6. I can't reproduce the bug there.

![huh](https://cloud.githubusercontent.com/assets/22871614/23585932/86b74496-01c5-11e7-8ccd-f14a31c1e982.png)

[launch.ks (boost phase)](https://gist.github.com/skaven81/9e980e28958e5c53ed8883f9d9f83702)
```
// Boost phase
{ 
    PRINT "Phase: Pre-launch" AT (0,1).
    LOCK THROTTLE TO 1.0.   // 1.0 is the max, 0.0 is idle.

    WHEN MAXTHRUST = 0 THEN {
        STAGE.
        WAIT UNTIL MAXTHRUST > 0.
        RETURN true.
    }

    LOCAL MYSTEER IS HEADING(90,90).
    LOCK STEERING TO MYSTEER.
    LOCK angle_a TO -3 * SHIP:ALTITUDE / 1000 + 90.
    LOCK angle_b TO -0.55 * SHIP:ALTITUDE / 1000 + 53.
    //LOCK angle_b TO ( 1 / ((SHIP:ALTITUDE / 1000) / 500) ) - 5.
    UNTIL SHIP:APOAPSIS > 100000 {
        //For the initial ascent, we want our steering to be straight up and rolled due east
        IF SHIP:ALTITUDE < 15000 {
            // between 0 and 10,000m, use a linear progression from 90 to 45 degrees pitch
            SET MYSTEER TO HEADING(90,angle_a). // (dir, pitch)
            PRINT "Phase: Pitch-over A" AT (0,1).
            PRINT "Pitch set to " + ROUND(angle_a,0) + " degrees" AT(0,15).
        } ELSE IF SHIP:ALTITUDE > 15000 AND SHIP:ALTITUDE < 50000 {
            SET MYSTEER TO HEADING(90,angle_b).
            PRINT "Phase: Pitch-over B" AT (0,1).
            PRINT "Pitch set to " + ROUND(angle_b,0) + " degrees" AT(0,15).
        } ELSE {
            SET MYSTEER TO SHIP:PROGRADE.
            PRINT "Phase: Push Apoapsis" AT (0,1).
            PRINT "Pitch set to prograde      " AT(0,15).
        }
        PRINT "Altitude: " + ROUND(SHIP:ALTITUDE,0) + " meters" AT (0,16).
        PRINT "Apoapsis: " + ROUND(SHIP:APOAPSIS,0) + " meters" AT (0,17).
        WAIT 0.25.
    }
}
```

I noticed at the start of a new game, I got two kOS choices on connection manager and selected the RT-manager. I haven't seen any problem there.

**Comment by ShaunDove** [comment]
Your choice of options and launch script look appropriate to reproduce what I was seeing.  Possibly a problem with a previous settings, or a ckan update problem, or just something else I did wrong although the remotetech update was the only change between working and not.  Whatever, there's a simple work around (uninstall RT, install RT).  Thanks for the response.
