### ISSUE TITLE
Version 1.2.2 Stuck on loading gigadish1

### ISSUE THREAD

**Issue by Potato-God1** [RemoteTechnologiesGroup/RemoteTech#722]
How do I solve this issue. The short comments continue to flash by but the game does not load past RTgigadish1. I have looked around and cannot find a solution.
![20170313231546_1](https://cloud.githubusercontent.com/assets/26398004/23884465/2ce8aaa2-0843-11e7-9f8f-78170def4c5d.jpg)

**Comment by YamoriYuki** [comment]
Please share your KSP.log and some more details about your installation. Like what you did to get this issue. It does not happen with clean KSP+RT.

**Comment by neitsa** [comment]
It really looks like #712.  @Potato-God1 could you verify your game files? (if you are using steam, check the game integrity and then, if that doesn't fix anything, uninstall + reinstall RemoteTech)

**Comment by YamoriYuki** [comment]
@neitsa  Yeah, forgot about that one :) Still, asking for log seems like the first thing to to when a bug report without it comes in ;)

**Comment by neitsa** [comment]
No probs @YamoriYuki , you're absolutely right :)

**Comment by Potato-God1** [comment]
[KSP.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/841942/KSP.txt)
I am running other mods along with it.
     B9-Aerospace
     Distant Object
     Docking Port Alignment
     Ferram Aerospace
     Kerbal Attachment System
     Kerbal Aircraft Expansion
     Kerbal Engineer
     Kerbal Inventory System
     Kerbal Interstellar Quest extended
     Planet Shine
     Remote Tech
     SpaceY-Lifters
I have checked the integrity of it using steam and everything comes out fine.

**Comment by YamoriYuki** [comment]
@Potato-God1 Your mods are installed wrong:
Loading assembly at G:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\**GameData\GameData**\RemoteTech\Plugins\RemoteTech.dll

Please move everything from \GameData\GameData one level up so yo only have \GameData\{mod_folders} structure.

**Comment by YamoriYuki** [comment]
@neitsa @KSP-TaxiService : It may be a good idea to calculate default settings url from location of RemoteTech.dll (see `AssemblyLoader`) to allow it to work even if located in different directory (just one level up from the dll)

**Comment by Potato-God1** [comment]
Thank you much, I figured that out after trying to find the problem. As I was adding mods it created a second Game Data folder. Thank you for the help!

**Comment by YamoriYuki** [comment]
You're welcome

**Comment by KSP-TaxiService** [comment]
YamoriYuki is right. Have a dynamic directory of a RT mod in a player's GameData is neat so this commit is created for this.

Even the RT mod inside GameData/Squad folder is working well.
