### ISSUE TITLE
Throttle lose when SAS on, on a probe controlled craft

### ISSUE THREAD

**Issue by Eckee** [RemoteTechnologiesGroup/RemoteTech#723]
**O.S:** Win 8.1 x64 
**KSP:** 1.2.2 x64
**RT:** 1.8.6
**Problem:** I lose thrust for an instant moment and gain it back when I try to steer/rotate the craft with pressing or tapping WASDQE keys when SAS is on, also switching SAS off when it's on. It does not happen only on the throttle bar next to navball, I can see the engine fire disapears and sound interruptions.

- It only occurs when the craft doesn't have any manned command module and SAS is on. Having at least one manned command module doesn't cause a problem even controlling the craft from the probe core.
- Happens everywhere, when waiting for the launch with engines off and not staged, ascending, landing on minmus, performing a maneuver etc.
- Happens both in career and sandbox modes.

**I know it's a RT related issue because;**
 - I tried it in a vanilla KSP: no problem
 - I tried it with only RT and MM 2.7.5 installed: problem

**Reproduction steps:**
   1. Launch KSP x64 1.2.2 with RT 1.8.6 and MM 2.7.5 installed
   2. Create a craft that has an unmanned command module, a fuel tank, an engine and proceed to launch
   3. Turn SAS on and off - causes throttle drops or,
   4. Use WASDQE keys when SAS is on - causes throttle drops

It's not dropping to 0 or it doesn't stay there. It only drops for an amount of few CTRL taps and it drops same from any thrust level, (like 85 from 100 or 35 from 50). If I keep pressing any WASDQE keys, it only drops a moment, doesn't stay dropped the whole time I press the key, if I press another key during the time, it drops again.

It's not a very big problem, but it makes little adjustments on landings impossible.

I can't record in game video, sorry.
 
Thanks for the mod and I hope provided info is enough and you can find what's causing this and solve.

**Installed Mods:**
 RT 1.8.6
 MM 2.7.5 

[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/843600/output_log.txt)
**Save File:** https://drive.google.com/open?id=0BywHz-G__Bk2NWNOUlZtd3BZc1U

### (Edit) Further observations:

- RT 1.8.4 has no problems with either MM 2.7.3 *as included* or 2.7.5 installed.
- It's [MechJeb](http://forum.kerbalspaceprogram.com/index.php?/topic/154834-122-anatid-robotics-mumech-mechjeb-autopilot-260-12-dec-2016/) *(2.6.0.0 is the one I have)* that prevents this bug, I don't know why I couldn't notice that before. I guess it "overrides" something to disable one or many features of RT.

**I ran a test on this [with this sandbox save file *(stock parts)*](https://drive.google.com/open?id=0BywHz-G__Bk2TGlVeWt6V0xNa1U), has far too cringy, hence ugly relay network between Kerbin and Minmus to never lose connection;** *(much thanks to [HyperEdit](http://forum.kerbalspaceprogram.com/index.php?/topic/34785-12-hyperedit-v153-sep-14-2016-cheat-teleporter-orbitplanet-editor-more/))*
*(also has an interplanetary capable polar antennas if you want to test it with more obvious signal delays but I don't have any sats around any other planets, because I didn't explore them in my career mode yet, don't want to spoil it lol.)*

- The result is, if you have MechJeb you don't have signal delay. I don't know it's a known bug or not. I don't think it's because of its autopilot. The vehicle without the bug I had had a custom skin for mechjeb, [tomtom by blizzy78](http://forum.kerbalspaceprogram.com/index.php?/topic/70359-small-mechjeb-touchscreen-case/), it doesn't have the autopilot features, only shows information like KER. Having a normal mechjeb part also prevents the bug, obviously. Maybe that would help.

**Comment by KSP-TaxiService** [comment]
Hi! Thank you for the detailed bug report. 

I verify this bug is reproducible in the KSP 1.2.2 and RT 1.8.6 at the launch pad, just like you said. I am almost certain this bug is related to my improvement work to RT's FlightComputer interaction with KSP's Autopilot (SAS) because the WASQE and SAS toggle are influenced by RemoteTech's flight state and delayed signal.

I will see how I can fix this bug.

**Comment by Eckee** [comment]
I'll use FC's KILL instead for now, thanks for the tip and contribution. Really appreciated.

**Comment by docwild** [comment]
Another workaround for this is to map analogue controls for pitch, yaw, roll and throttle. Maybe a key repeat issue?

**Comment by Eckee** [comment]
Hey, today I noticed it won't happen in ALL probe controlled vehicles. I launched a completely different rocket today *(without the launch clamps, different probe core, different engines etc.)* and there was no problem. I don't think it's because I restarted the game, I tried it before.
I'll try different combinations tonight to pinpoint which parts may cause this when I have time. I'll update the original post if I find something.

@docwild if that question's for me, I don't even know what it means, sorry.

**Comment by KSP-TaxiService** [comment]
@Eckee Wow, I didn't expect this. I will look out for this when debugging the cause. Given that you know better how to trigger this bug, can you check if the bug is in RT 1.8.4, that is before I improved the interaction between RT FlightComputer and KSP's SAS.

**Comment by Eckee** [comment]
@KSP-TaxiService Hey, sorry for the late reply, here it is:
- RT 1.8.4 has no problems with either MM 2.7.3 *as included* or 2.7.5 installed, as you expected.
- It's [MechJeb](http://forum.kerbalspaceprogram.com/index.php?/topic/154834-122-anatid-robotics-mumech-mechjeb-autopilot-260-12-dec-2016/) *(2.6.0.0 is the one I have)* that prevents this bug, I don't know why I couldn't notice that before. I guess it "overrides" something to disable one or many features of RT.

I ran a test on this [with this sandbox save file](https://drive.google.com/open?id=0BywHz-G__Bk2TGlVeWt6V0xNa1U), has far too cringy hence that ugly relay network between Kerbin and Minmus to never lose connection; *(much thanks to [HyperEdit](http://forum.kerbalspaceprogram.com/index.php?/topic/34785-12-hyperedit-v153-sep-14-2016-cheat-teleporter-orbitplanet-editor-more/))*
*(also has an interplanetary capable polar antennas if you want to test it with more obvious signal delays but I don't have any sats around any other planets, because I didn't explore them in my career mode yet, don't want to spoil it lol.)*

- The result is, if you have MechJeb you don't have signal delay. I don't know it's a known bug or not. I don't think it's because of its autopilot. The vehicle without the bug I had had a custom skin for mechjeb, [tomtom by blizzy78](http://forum.kerbalspaceprogram.com/index.php?/topic/70359-small-mechjeb-touchscreen-case/), it doesn't have the autopilot features, only shows information like KER. Having a normal mechjeb part also prevents the bug, obviously. Maybe that would help.

Adding those info to the original post.

**Comment by KSP-TaxiService** [comment]
@Eckee Many thanks for the information and files on the bug and circumstances. This gives me more than sufficient information to narrow down the scope of the bug.

Last time I checked, RemoteTech is not compatible with MechJeb because of the input-control conflict over SAS. You are possibly right that MechJeb autopilot never takes in the signal delay.

More I am thinking about this problem, more it seems like KSP's SAS has the other internal areas I didn't look into when improving the RemoteTech's interaction with the SAS last time.

**Comment by Eckee** [comment]
Glad to help, thank you and the team for making this great mod better, cheers
