### ISSUE TITLE
VAB/SPH dish target allocation (feature request)

### ISSUE THREAD

**Issue by Khormin** [RemoteTechnologiesGroup/RemoteTech#725]
Is there a way to have the allocation menu:

a) Functional in the editors, so you can preset say, dish 1 to point at KSC, dish 2 to point to your Mun base, etc?  And;

b) Kept with saving?

Launching a new slew of relays gets rather tedious, otherwise, with having to manually target each dish in turn on every launch.

**Comment by KSP-TaxiService** [comment]
Yup, this feature is in development (pull request #724) but there are unintended consequences such as NullReferenceException spam. We are changing some things there.

**Comment by efalder413** [comment]
+1
