### ISSUE TITLE
Modify the config of the plugin without restarting the game

### ISSUE THREAD

**Issue by Nihilivin** [RemoteTechnologiesGroup/RemoteTech#728]
Hi,
I'm trying to tweak the config of the plugin at runtime, without restarting the game. I have a bunch of mods and I'm trying to do a BD Armory contract that requires another plane auto-piloted. But it has no antenna, so it seems that it can't receive any orders. That's why I'd like to disable RT just for this contract then reenable it. Isn't it possible to re-open the config window you show at the first start of the plugin?
Thank you
Cheers

**Comment by KSP-TaxiService** [comment]
I am sorry but it is not possible to disable/enable RT at runtime. I tested the toggling of `RemoteTech_Settings.cfg`'s two RemoteTechEnabled and CommNetEnabled flags at runtime and it didn't work well (it broke the whole communication).

KSP's modding framework do not offer a way to remove/insert itself from the parts, interfaces and scheduled actions, just like any other mod.

**Comment by KSP-TaxiService** [comment]
Hi,

With your query answered, do you have any further comment about this?

Thanks!
