### ISSUE TITLE
Engine Throttle Control has no Delay

### ISSUE THREAD

**Issue by Domi1993** [RemoteTechnologiesGroup/RemoteTech#734]
When i use the Shift/Ctrl-Keys for controll the Thrust of the Engine, the Engine will Ignite without a Signal delay. This means i can "Cheat" And use the Engine for Braking when i land a Rover on a Planet without a athmosphere.

Is there a Option to set a Delay for Engine Controls? 

When not why not to add this delay?

**Comment by KSP-TaxiService** [comment]
Hi, are you using RT 1.8.7 and KSP 1.3?

I tested RT 1.8.6 and KSP 1.2 and the throttle up/down/Z/X is definitely delayed. But in KSP 1.3 with the develop branch, the delay is not applied to the throttle. Something changed in KSP 1.3 broke it.

**Comment by Domi1993** [comment]
Yes i use the KSP 1.3

I will check the RT Version when i'm at my Computer

**Comment by KSP-TaxiService** [comment]
A loophole was accidentally introduced by my [fix](https://github.com/RemoteTechnologiesGroup/RemoteTech/commit/d71b382fd15c6bf90a59a3f12559850d52d4ff94) on the issue #723. 

I close this in both RT's Flight Computer and KSP's Autopilot.

Thanks for reporting this!

**Comment by Domi1993** [comment]
how i can build the develop Version direct from github?
