### ISSUE TITLE
Power consumption multiplier setting doesn't change usage

### ISSUE THREAD

**Issue by DrTango** [RemoteTechnologiesGroup/RemoteTech#735]
KSP: 1.3.0.1804 (Win64) - Unity: 5.4.0p4 
OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
Problem: Hi might just be me not understanding how the setting works but changing the ConsumptionMultiplier setting up or down makes no difference to actual power used by the antennas. I removed all mods before but remotetech but still had the same problem.

Reproduction steps:
    Change ConsumptionMultiplier setting up or down, create a ship with probe, antenna, battery, solar panel and dish, launch to launch pad and note power usage when planet enters dark zone on dish vs actual usage.
        
Installed Mods: 
Chatterer - 0.9.93.1804
Community Category Kit - 2.0.1
Community Resource Pack - 0.7.1
Contract Configurator - 1.23.2
Contract Pack: Bases and Stations - 3.6
Contract Pack: RemoteTech - 2.1.3
Kerbal Engineer Redux - 1.1.3
KSP-AVC Plugin - 1.1.6.2
RemoteTech - 1.8.7
AmpYear - 1.5
TweakScale - 2.3.6
[x] Science! - 5.9

Persistent save:
[persistent.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1206900/persistent.txt)

**Comment by KSP-TaxiService** [comment]
Our bad! ConsumptionMultiplier is never applied to all antennas' consumption rates.
