### ISSUE TITLE
How to make a Build from the develop in github

### ISSUE THREAD

**Issue by Domi1993** [RemoteTechnologiesGroup/RemoteTech#736]
Hello i want to test the fix for the not delayed throttle (issue #734) but i dont know how to build the Mod with git Bash.
I builded Minecraft mods (Java) directly from Github, using Gradle.
But how i can do this for KSP-Mods?

**Comment by KSP-TaxiService** [comment]
Building a KSP mod from the develop branch by yourself is different. 

1. Download and install free [Visual Studio Community](https://www.visualstudio.com/vs/community/)
2. (Git) Check out the develop branch to your local space
3. Open RemoteTech\src\RemoteTech\RemoteTech.csproj in VS
4. In the Solution Explorer window, right-click 'RemoteTech' and navigate 'Add > Reference..'
![image](https://user-images.githubusercontent.com/22871614/29365080-46dbe0dc-82c8-11e7-8f35-3ab21bcc1edb.png)
5. Add the following DLLs as references
![image](https://user-images.githubusercontent.com/22871614/29365186-a8b82cf2-82c8-11e7-9093-ddb34b0b9043.png)
6. Save the project
7. If you didn't set the .NET Framework earlier, in the Solution Explorer, right-click on MyKSPProject and choose Properties. Change the Target Framework to 3.5 (Visual Studio will default to a newer framework version). Visual Studio will reload the project after you click ok.
8. Build it
![image](https://user-images.githubusercontent.com/22871614/29365295-0c0f6efa-82c9-11e7-9a61-4895f382046c.png)

If it goes well, the newly-build DLL will be in RemoteTech\GameData\RemoteTech\Plugins.

**Comment by Domi1993** [comment]
OK Thanks it work now the Throttle is locked and cannot controlled in Real Time, thanks for your help.
