### ISSUE TITLE
Feature Request: Resource locking control

### ISSUE THREAD

**Issue by AkiraR** [RemoteTechnologiesGroup/RemoteTech#739]
Ability to either lock/unlock resources with out a connection, or be able to schedule the locking/unlocking of resources with the flight computer.

Forum post with more info on why I think it's a good feature: https://forum.kerbalspaceprogram.com/index.php?/topic/139167-13-remotetech-v188-2017-09-03/&do=findComment&comment=3190865

**Comment by KSP-TaxiService** [comment]
From the forum thread

Me:
> Currently, hibernating the probe core will reduce the core's power consumption but its antennas' power drain is not affected. I think extending this hibernation to the antennas' power drain would mean a reduction in communication ranges, something requested for RT2 (https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/272). 

>Akira, two new buttons to put the whole probe to sleep (no communication and probe-core hibernation) and wake it up (like the sleep button of a computer) in Flight Control are doable for the current RT. Obviously, care is required in scheduling these sleep and wakeup commands or say hello to the eternal sleep. Is this correct?

Akira:
> That is in essence what I am looking for yes.

> Just to make sure, you are suggesting to add two buttons to the flight computer, one that shuts down the probecore and all antennas and one that reactivates them. This would allow you to set your time delay for some point in the future, click the wake up button to schedule a wake up call. Then clear the time delay and click the sleep button to put the probe into a super low power state.

> If that is your plan then yes that is exactly how I envision this working, might not be a bad idea to have a big warning, or have the sleep command pop up a window saying "make sure to schedule wake up command BEFORE putting probe to sleep" with confirm and cancel buttons lol.
