### ISSUE TITLE
KSP v1.3.1 compatibility

### ISSUE THREAD

**Issue by jeffb4** [RemoteTechnologiesGroup/RemoteTech#740]
The RT 1.8.8 release lists compatibility with KSP 1.3.0. A 1.3.1 patch has been released (I'm on Mac right now, don't know about PC) so now CKAN won't handle RT installs.

Could we get a patch release with the compatibility updated? Please and thanks

**Comment by DamnGoodDevill** [comment]
![image](https://user-images.githubusercontent.com/23260589/31514212-2a674388-af91-11e7-9fce-b159b9d0f532.png)

If something didn't work via CKAN just uninstall CKAN version and download release zip... sync gamedata folders and you are good to go until next CKAN version patch upgrade

As you can see it's yellow not green on the avc list (same as futureXYZ mods and couple others) but works fine

**Comment by KSP-TaxiService** [comment]
As DamnGoodDevill pointed out, RT 1.8.8 is working fine in KSP 1.3.1 as I tested last week. Plus, I want to tuck in two or three big things (I think you are going to love one or two) first before re-compiling for KSP 1.3.1.

As it is not an issue, I will close it.

**Comment by czubehead** [comment]
Could you update CKAN package to support KSP 1.3.1 ?

**Comment by KSP-TaxiService** [comment]
@czubehead, a KSP 1.3.1 recompilation will be deployed by the end of this week. I am finishing up the final touch of the last big thing and start to test RT soon. :)
