### ISSUE TITLE
Tweakable sliders of parts are sluggish in vessels with connected probe cores even with signal delay disabled

### ISSUE THREAD

**Issue by ChippedChap** [RemoteTechnologiesGroup/RemoteTech#748]
OS: Windows 10 x64 bit
KSP: 1.4.2 x64 bit Steam Version (Also observed in 1.3.1 x64 bit)

Problem: When flying craft with connected probe cores, tweakable sliders on parts appear be very sluggish when changing them. When flying craft with no probe cores and no connection, but with a manned pod, (such that the top left indicator shows 'N/A') there is no sluggishness in tweakable sliders. 
This happens with signal delay disabled. Moving the slider also does not update the slider for other symmetried parts. Here is a video showing reproduction setup and what I mean by sluggish sliders: [https://www.youtube.com/watch?v=ina7UxiR3PA](https://www.youtube.com/watch?v=ina7UxiR3PA)

Issue was replicated in a stock KSP 1.4.2 copy with no mods except RemoteTech and ModuleManager. Default settings were used except for the fullscreen option, which was enabled. Note that by probe core I mean command parts that do not have any crew capacity.

Sometimes, this sluggish tweakable behavior will manifest in the editor (VAB/SPH). However, I have not found a way to consistently reproduce this. I initially came across this issue while using RemoteTech in 64 bit KSP 1.3.1. While I could put up with the sluggishness during flight, sometimes after flying a craft for a first time (by either launching or switching to a vessel from the tracking station), the sluggishness and symmetry issues would also manifest in the VAB.

Output Log (Log is from after recording of the video):
[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1887941/output_log.txt)
Test Craft File:
[test.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1887942/test.zip)

Reproduction Steps:
1. Install completely fresh copy of 1.4.2 of Kerbal Space Program.
2. Download the latest version of RemoteTech and move all contents of the GameData folder inside the downloaded .zip to KSP GameData.
3. Launch KSP and start a new sandbox save with CommNet disabled. When the RemoteTech settings window appears, disable signal delay.
4. Go to the VAB and create a craft consisting of a Probodobodyne HECS (spelling that was tough), an FL-T400 Fuel Tank and two Mk-55 engines attached to the fuel tank with 2x symmetry. 
5. Launch the vehicle and try to change the thrust limiter value of the Mk-55s by right clicking on the part and moving the thrust limiter slider. A sluggishness in the slider should be observed. Any change in one Mk-55 also should not change the slider of the symmetried Mk-55.

It seems to me that this is the first time an issue like this has been reported, which is strange because I would think that such an annoying bug would be reported pretty much immediately. Because of this I have suspicions that this may be caused by something on my computer. I might try to reproduce this issue on another computer to see if this is the case.

**Comment by KSP-TaxiService** [comment]
Hi, 

Actually, it isn't your computer. This slider lag is known because we register our RemoteTech listener on the part action menu for all user actions in order to delay in signal context. This listener isn't registered when a manned pod is in control or signal delay is disabled. It takes about 0.5 seconds between KSP's broadcast of an user action to RemoteTech, long enough for the feedback to be "sluggish".

I am afraid this latency is unavoidable for the part action hook-up.

**Comment by ChippedChap** [comment]
Ah, I was thinking that this was the case. Thanks for responding.

I do still have occasional issues with the sluggishness manifesting in the editor, though I still haven't been able to consistently reproduce it in 1.4.1. The only way I've been able to consistently have this issue is by switching to an orbiting probe and switching back to the VAB in my 1.3.1 sandbox save. I'm thinking of making another video but I don't have the time right now.

I've tried reproducing it in 1.4.1 by hyper-editing a probe into orbit, switching to it, and switching back to the VAB, but the issue wasn't there. I have encountered the editor sluggishness once in 1.4.1 with the test craft I've used in the video, which is why I tried reproducing it. I suspect this may be caused by the listener not being unregistered on scene change to the VAB/SPH.

**Comment by KSP-TaxiService** [comment]
Hi, can I trouble you to try again with this new build with a fix? [Plugins.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/1934727/Plugins.zip)

I eliminate the input delay on Part Action listener.

**Comment by ChippedChap** [comment]
Hello. Sorry for the really late response.

Just commenting to say thank you for the fix. I haven’t gotten to testing your plugin or responding since I’ve been rather busy lately. I’ll try it the next time I can play KSP.

Just responding now since you closed the issue and felt really bad I haven’t thanked you.

**Comment by KSP-TaxiService** [comment]
No worries, I tested independently and it was good. I was not sure if it was responsive on your side since you had experience of reproducing the lag.

**Comment by JetSetMiner** [comment]
Unfortunately I have mixed results. The lag is completely gone, but after a while the symmetry gets broken again and interstage nodes and the shrouds of service modules stop working. But I have found putting down 2 fairings that are mirrored and then picking up the other one restores the nodes.  I'm sorry I can't make a comprehensive video like ChippedChap.
