### ISSUE TITLE
Connections not visible in map/tracking station view

### ISSUE THREAD

**Issue by kurgut** [RemoteTechnologiesGroup/RemoteTech#751]
I'm running KSP 1.3.1, modded, as sayed in the title, the connections are not visible in map/Tr station view, and the three (or four don't remember) little buttons to configure the visiblity of the connections are hidden (they're black and unclickable), it appears after I've installed some mods, but I ask the question, so if it is a knowned issue, it avoid me uninstalling all my mods one per one to find the culprit :) 

Oh yes, and the connection are visible only for the selected/active vessel, so you can basically see just one line of connection going from your active vessel to the mission control.

Thanks!

**Comment by KSP-TaxiService** [comment]
Hi, can you provide the output_log.txt from the folder KSP_x64_Data, and a screenshot of Tracking Station with vessel buttons at top and RT bar at bottom?

Also, what is your RT version on your KSP 1.3.1?

**Comment by kurgut** [comment]
Hi,thanks for reply,  yes here it is, it says steam folder for location, but that's just a clean copy then modded, it's not dependent on steam:
[output_log.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/2078126/output_log.txt)

I'm running RT 1.8.9, installed via CKAN.

And finally the screenshots, first default view, second with a selected vessel: 

![screenshot18](https://user-images.githubusercontent.com/39562611/41065261-64725b6e-69de-11e8-99c5-49835e360aae.png)

![screenshot19](https://user-images.githubusercontent.com/39562611/41065324-9eb7009a-69de-11e8-84ae-81b761f57ef2.png)

Thanks for help :)
