### ISSUE TITLE
Status near PAW buttons is not actually, is what happens when clicked

### ISSUE THREAD

**Issue by Gordon-Dry** [RemoteTechnologiesGroup/RemoteTech#752]
I mentioned this in the forum last year or even two years ago.
Still a bummer.
When it says "Start retracted" near a button I assume that it starts retracted and not that I have to click that button to have it start retracted (when it then says "Start deployed") ...

**Comment by KSP-TaxiService** [comment]
Oops, I must miss your post on this.

Anyway, they are now similar to Solar Panel's texts.
