### ISSUE TITLE
Creating materials from string no longer supported warning.

### ISSUE THREAD

**Issue by PiezPiedPy** [RemoteTechnologiesGroup/RemoteTech#755]
One thing I have noticed is when changing scenes into the Tracking Station I get warnings that materials can not be set with a string as that feature is no longer supported.

```
[ERR 11:25:56.229] Trying to create a material from string - this is no longer supported.
	UnityEngine.Material:.ctor(String)
	RemoteTech.UI.NetworkLine:Awake()
	UnityEngine.GameObject:.ctor(String, Type[])
	RemoteTech.UI.NetworkLine:Instantiate()
	RemoteTech.NetworkRenderer:UpdateNetworkEdges()
	RemoteTech.NetworkRenderer:OnPreCull()
```

**Comment by KSP-TaxiService** [comment]
Yup, this is a known issue due to KSP migration from Unity 4 to Unity 5 (See current #693). A fix requires a external shader file to be created and loaded into KSP.
