### ISSUE TITLE
Cannot add/edit maneuver nodes via local control of hibernate is set in flight computer 

### ISSUE THREAD

**Issue by MechBFP** [RemoteTechnologiesGroup/RemoteTech#756]
As per the title, if a probe is set to hibernation mode in the flight computer, and is then later manned, you are unable to add or edit nodes (“controls locked”) until you go into the flight computer and turn on the “wake” setting. 
Under local control you should have full control regardless of the probe settings on the vessel.

**Comment by KSP-TaxiService** [comment]
Good question. I interpret the stock hibernation function as the toggleable switch, where you have to explicitly flip. I figure it is not something to causally bypass, like this local-control scenario.

What do you think?

**Comment by MechBFP** [comment]
In this case, once a probe is manned the player can do anything else they want, turn the ship, burn engines, throttle, stage, etc. The only thing they can't do is create a maneuver node in the map view, which doesn't make much sense if they can do everything else under local control.
