### ISSUE TITLE
Contract Pack: RemoteTech No contracts in the "All" tab - even unmet ones

### ISSUE THREAD

**Issue by GrayTechGH** [RemoteTechnologiesGroup/RemoteTech#758]
At some point RemoteTech contracts stopped showing up.  I came back to KSP after a few weeks away and the contracts were gone from my career games.   Other contracts were still there.  Since I have many mods I recreated the problem on a new KSP with minimum mods.

KSP: 1.4.5 (Win64) - Unity: 2017.1.3p1 - 
OS: Windows 10  (10.0.0) 64bit

Mods
- Contract Configurator - 1.25
- Contract Pack: RemoteTech - 2.1.4
- KSP-AVC Plugin - 1.2.0.2
- RemoteTech - 1.8.13

Steps

1. Start KSP
2. Start new career
3. Go to Mission Control
4. GO to All contracts

Problem - no RemoteTech contracts

[KSP RemoteTech error logs Sept. 30 2018.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/2432531/KSP.RemoteTech.error.logs.Sept.30.2018.zip)

**Comment by GrayTechGH** [comment]
Able to restore contracts by regressing RemoteTech to 1.8.12.  Likely the issue be resolved in [Fix for RemoteTech v1.8.13 #668](https://github.com/jrossignol/ContractConfigurator/pull/668) pull request.

**Comment by PiezPiedPy** [comment]
Here's the latest dev build you need https://www.dropbox.com/s/3vhw8kteydjzwk2/CC_RemoteTech.dll?dl=0
