### ISSUE TITLE
Request: possibility to only set roll / pitch / heading - not all at once

### ISSUE THREAD

**Issue by Gordon-Dry** [RemoteTechnologiesGroup/RemoteTech#759]
Especially the feature to only set roll is highly requested ...

**Comment by KSP-TaxiService** [comment]
Hi,

Can you provide some scenarios that make sense to use exclusive rolling, pitching or heading? I think they are possibly niche.

**Comment by Gordon-Dry** [comment]
Well, for the game functionality not that much, but for the immersion.

Imagine an altimetry scanner, it would be oriented "downwards", so towards the surface of the celestial body.
While being in a nearly perfect circular orbit, the vessel is rotated offset to let's say 37° ...
If there is a spin, as small as it could be, the flight computer only makes sure the prograde orientation is preserved, the roll is untouched and the spinning continues - slowly but steady.

**Comment by Gordon-Dry** [comment]
I just add some:

MechJeb provides some attitude settings like "Sun - Down" which points the vessel towards the sun.
Or "Sun - Forward" - combined with "Roll: x°" where X gives a degree at which the solar panels have the best possible orientation towards the Sun.

Stuff like that ...

**Comment by dimitriye98** [comment]
To add to this, it would be very nice to be able to set the axes independently in general. E.g. set the pitch to track surface prograde, but have heading locked to whatever heading you're launching on. I'm usually able to make due with just designing my rockets to be aerodynamically stable enough that it doesn't matter, but frankly, real rockets often launch using gimbaled thrusters to offset aerodynamic instability e.g. when carrying a payload inside a large fairing, and in general, it'd be a nice quality of life feature when using the flight computer for gravity turns.
