### ISSUE TITLE
Set Assembly Version to same as ProductVersion

### ISSUE THREAD

**Issue by Gordon-Dry** [RemoteTechnologiesGroup/RemoteTech#760]
A Kerbalism check fails, because:
```
RemoteTech.dll
      ProductName    : RemoteTech
      ProductVersion    : 1.8.13
      Assembly Version    : 1.8.0.0
```

**Comment by PiezPiedPy** [comment]
Extra bit of info
Kerbalism checks the Assembly version is above 1.8.12 and since the RT dll Assembly version is 1.8.0 it gives a warning to the user that they are using a version earlier than 1.8.13 and should update.

**Comment by KSP-TaxiService** [comment]
This [comment](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/Properties/AssemblyInfo.cs#L36-L38) in the assembly file specifically says not to use revision numbers for Assembly Version. 

Do you know if it means for the current situation?
