### ISSUE TITLE
RCS is always counter-firing on opposing directions to hold attitude ...

### ISSUE THREAD

**Issue by Gordon-Dry** [RemoteTechnologiesGroup/RemoteTech#762]
No exceptions in the log.

**Comment by KSP-TaxiService** [comment]
Please help to provide the reproduction steps and RT & KSP versions per [guide](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports).

**Comment by Gordon-Dry** [comment]
O.S: Windows 10 Pro 64-bit (version 1803 build 17134.320)
KSP: 1.4.5 64 bits
Problem:
RCS is always counter-firing on opposing directions to hold attitude

Reproduction steps:
Launch KSP, use the "Sputnik 2.craft" file from the .7z linked below, launch it on Earth to 1865 km apogee using MechJeb 804, then create a maneuver to set the perigee to 165km and let RT do the maneuver, with enabled RCS (built in the upper stage).

Logs:
https://www.dropbox.com/s/bhrz3bhiyrcd9nd/2018-10-09_1%20KSP.log%20and%20stuff.7z?dl=1

Installed Mods:
https://pastebin.com/C2GAW70u

Persistent save:
see above link

Screenshot:
none

Additional notes:
This could be related: https://github.com/MuMech/MechJeb2/issues/1049

**Comment by Gordon-Dry** [comment]
At the end of that session I had a huge exception spam about planting a flag ...
https://forum.kerbalspaceprogram.com/index.php?/topic/178829-plant-flag-on-earth-explosion-sound-no-controls-log-spam/

**Comment by KSP-TaxiService** [comment]
There are too many mods to download and test your craft however.

I unsuccessfully attempted to reproduce the issue in a scaled-down KSP environment of RT, Kerbal Engineer and MechJeb2. MechJeb2 or RT FC is working fine on big upper stage's RCS and I do not see any abnormal behaviour.

Going through your mod list, PersistentRotation stands out because I received one or two unconfirmed reports about RCS not providing thrust or firing wildly.

Can you check this mod?

**Comment by Gordon-Dry** [comment]
> Going through your mod list, PersistentRotation stands out because I received one or two unconfirmed reports about RCS not providing thrust or firing wildly.
> 
> Can you check this mod?

Yeah, well, PersistentRotation is in my list of suspicious mods.

Could you give me links to these reports?

Thanks for the hint.

https://github.com/MarkusA380/PersistentRotation/issues/28

https://forum.kerbalspaceprogram.com/index.php?/topic/102277-14-persistentrotation-185/&do=findComment&comment=3466263

**Comment by KSP-TaxiService** [comment]
Here's the ancient report #499 and one KSP [post](https://forum.kerbalspaceprogram.com/index.php?/topic/139167-144-remotetech-v1812-2018-07-17/&page=61&tab=comments#comment-3452737).

But I may remember this differently. I never managed to replicate the specific RCS issue in isolated environment. MechJeb2 is cooperating well with RemoteTech now, when compared to some time ago (eg input fight)
