### ISSUE TITLE
Some RT issue with staging a stockish BDB fairing

### ISSUE THREAD

**Issue by Gordon-Dry** [RemoteTechnologiesGroup/RemoteTech#765]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/469

**Comment by KSP-TaxiService** [comment]
RT hooks Part Menu Action events to apply signal delay on an event triggered by any player action on the part's menu.

Apparently, the staging/deploy fairing event from your action was nullified by something and RT tried to invoke the event unsuccessfully.

I tested with Bluedog and RemoteTech without any issue.
![image](https://user-images.githubusercontent.com/22871614/47093453-ca23c980-d25b-11e8-8a6f-a8d9b1936514.png)
