### ISSUE TITLE
Cannot find RemoteTech Button and FlightManager

### ISSUE THREAD

**Issue by titanin** [RemoteTechnologiesGroup/RemoteTech#780]
I cannot find the RemoteTech Button in either Toolbar mod or Stock toolbar neither can I find The FlightManager.

Cannot control OctoSat craft and it will not use its RCS thrusters for translation/rotation.

**Comment by KSP-TaxiService** [comment]
Hi,

May I have your output log at `Kerbal Space Program\KSP_x64_Data` (before 1.3) or `C:\Users\%USERNAME%\AppData\LocalLow\Squad\Kerbal space Program` (1.3 onwards)? According to your description, RT is not installed.

**Comment by KSP-TaxiService** [comment]
Hi, I have not heard from you for while. Please let me know when you obtain the log requested and I will reopen this issue
