### ISSUE TITLE
Signal delay timer error when executing timed commands.

### ISSUE THREAD

**Issue by DrToonhattan** [RemoteTechnologiesGroup/RemoteTech#781]
Windows 10 pro 64 bit
KSP 1.4.5 64 bit

If I have a probe far enough away from Kerbin that there's a noticeable signal delay, a weird glitch happens when I set a command to execute after a certain amount of time. 
Example: 
Let's say I am orbiting a planet with a signal delay of 40 seconds. I setup a command to execute in 3 minutes using the flight computer, and it starts counting down, something like "40s + 2m20s". When the 40 second countdown gets to 0, instead of continuing the countdown from 2m20s, it suddenly jumps to about 1m40s, the same difference as the signal delay. This results in my command being executed 40 seconds too early in this example. I have played through KSP several times over the last few years using RemoteTech and various other mods and it has never behaved like this for me on previous games.

Note: the issue does not occur if the command delay is set for less time than twice the signal delay. In my above example, if I set the timer for 1 minute, after the initial 40 second signal delay countdown, the remaining 20 seconds would count down normally as that is less than the signal delay. I hope that makes sense.

I made a fresh install of KSP with just RemoteTech and no other mods, new save, and the issue persists.

**Comment by KSP-TaxiService** [comment]
Almost certain it is related to this recent fix to Commit 562887ff37bfef2a38b4c07b595d5b1cf89eb12d on delayed commands executed by FC too early

**Comment by KSP-TaxiService** [comment]
Sorry about the critical timing bug. You may use this [develop build](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/2611101/RemoteTech.zip) to replace the DLL in `\GameData\RemoteTech\Plugins` until a next official release is out,
