### ISSUE TITLE
Removing stock-like antennas

### ISSUE THREAD

**Issue by EoD** [RemoteTechnologiesGroup/RemoteTech#783]
I am not sure if this is in the interest of RemoteTech 1.x, but in my opinion it would allow an easier migration to RemoteTech 2.x and/or CommNet if all the duplicate antennas would be removed from RemoteTech and automatically replaced by its stock counterpart on a RemoteTech upgrade.

Similar to RemoteTechnologiesGroup/RemoteTech-Antennas@184b0fcb2f44ebd9f6cdef819107c75310a9f740, and keeping RemoteTechnologiesGroup/RemoteTech-Antennas#2 in mind.

**Comment by KSP-TaxiService** [comment]
Hi, it is not good idea to migrate to the stock antennas only as it would reduce the antenna diversity and hence usability. For example, Reflectron GX-128 is the ultimate antenna covering everything in the solar system while Reflectron KR-7 fills the gap between Communotron DTS-M1 and RA-2 Relay Antenna.

Besides, my on-going research on RemoteTech 2.x's realistic communication model indicates that a large and diverse number of antennas are required and the stock antennas are too few and inadequate to support the entire model. For example, a radar phased array is useful in this model.

**Comment by EoD** [comment]
@KSP-TaxiService I think you misunderstood the bug report here. What you are describing is neither done  RemoteTechnologiesGroup/RemoteTech-Antennas@184b0fc nor what the bug report says.

It is merely about removing stock-like antennas from RemoteTech which are merely a relic from the past, when stock didn't have these antennas.

**Comment by KSP-TaxiService** [comment]
Let's start with what you requested, given I seem not able to get your exact point.

Are you suggesting a custom antenna should be deprecated when a new stock antenna similar to the former antenna is added, and RemoteTech migrates to the new stock antenna?

Is it basically same as the other thread (https://github.com/RemoteTechnologiesGroup/RemoteTech-Antennas/issues/2)?

**Comment by KSP-TaxiService** [comment]
Hi, a gentle reminder on this.

**Comment by EoD** [comment]
@KSP-TaxiService yes, I would expect to deprecate a RT antenna if a stock equivalent has been released. How the deprecation can be done is a different topic of course.

While it is similar to the other report, this here is meant as a enhancement request, while the other one is a plain bug from my point of view.

**Comment by KSP-TaxiService** [comment]
I understood now. 

Per current procedure, we will disable the corresponding RT antenna's availability in Editor when a new stock equivalent is added to the game. This "deprecated" part will be still accessible to the game to avoid the automated vessel deletion, as you experienced in the other thread.

For the RT DP-01 antenna with the stock equivalent existing, we kinda leave it in as there isn't a strong reason for deprecation. 

This thread will be closed as there is no further action from us on this.

Thanks!
