### ISSUE TITLE
bug after reverting launch

### ISSUE THREAD

**Issue by cascinova** [RemoteTechnologiesGroup/RemoteTech#791]
After I revert a launch, and go back to VAB the game breaks, it opens up all parts in career mode, and won't let me exit the building or exit the game.  The problem only exists when i have this mod installed and using CKAN.

**Comment by KSP-TaxiService** [comment]
Hi, 

Kindly assist to provide steps and output_log.txt, per [bug report guideline](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports) for investigation.

Thanks.

**Comment by KSP-TaxiService** [comment]
No followup on the log and reproducible steps requested

**Comment by YukiTooru** [comment]
I also have the same problem with the version 1.9.2 
How can I solve this problem?

**Comment by YukiTooru** [comment]
OS: Windows10 1803 
KSP: 1.7.0
Problem: After I revert a launch, and go back to VAB the game breaks, it opens up all parts in career mode, and won't let me exit the building or exit the game.

Reproduction steps:
    First launch a ship from any building, then revert the launch or go back to the KSC 
I can't find the logs file but I take a screenshot to the debug toolbar 
![screenshot5](https://user-images.githubusercontent.com/50932212/58218017-60790b80-7cd3-11e9-8f2b-18f8a451ec6b.png)

**Comment by KSP-TaxiService** [comment]
@YukiTooru The log file is now in `C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program` since KSP 1.4.

I am aware of this mysterious issue reported for long time but I never am able to reproduce it on KSP with RT only. The common steps of launching from Editor and reverting to Editor never trigger the error at my side.

Do you have any other insight or idea?

**Comment by YukiTooru** [comment]
Now I played with the mod on the ksp 1.7.1 and the bug disappears, if come back i will notify you

**Comment by YukiTooru** [comment]
Well, I have the same problem again. When I revert the flight, the buttons don't work in the VAB.

Here is the log file.
[error.log](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/3364844/error.log)

**Comment by KSP-TaxiService** [comment]
@YukiTooru 

I am sorry but this is different from output_log.txt. The output log is at C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program
