### ISSUE TITLE
Request: Save Flight Computer window position across sessions

### ISSUE THREAD

**Issue by Galenmacil** [RemoteTechnologiesGroup/RemoteTech#792]
There was an "issue" open for that several years ago but it was closed... Still would be great to have at least a way via a config file to set the window position.

**Comment by KSP-TaxiService** [comment]
Hi, won't it be easier for RT to remember the last window position between play sessions? Like the window will be at that spot when playing next day?

**Comment by Galenmacil** [comment]
Ultimately, yes, that would be the way to go! I agree.
