### ISSUE TITLE
The new KSPAxisGroup controls are not suppported

### ISSUE THREAD

**Issue by ncanceill** [RemoteTechnologiesGroup/RemoteTech#794]
**Impact**
The custom axis groups Custom01-Custom04 cannot be used with an unmanned vessel using RemoteTech 1.9.2 and KSP 1.7.1.2539

**Fix**
I believe that [the code handling the custom action groups](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/master/src/RemoteTech/RTCore.cs#L314-L343) could be expanded to also work with custom axis groups
According to the docs, the key bindings are in [GameSettings.AXIS_CUSTOM](https://kerbalspaceprogram.com/api/class_game_settings.html#a64108f68779c23ec062925010d740870) and the actions are [KSPAxisGroup.Custom01](https://kerbalspaceprogram.com/api/_axis_field_8cs.html#ada6e3d1faf694c923defbd81207115ddac5d637f28638111e5831e6e66b85c9d3)-04
Notice that this does not affect the other (non-custom) axis groups, because they are already handled through the corresponding controls (pitch, yaw, throttle...)

**Comment by KSP-TaxiService** [comment]
Hi, I need more information about the custom axis groups C1 to C4. They don't seem to behave like custom action groups, and may be linked to the robotic controller. 

How are C1 to C4 utilized in flight? On a light part, I assigned R, G and B to C1 to C3 and nothing happened when I turned on the light and pressed any of C1, C2 and C3.

**Comment by ncanceill** [comment]
Thanks for you reply @KSP-TaxiService

Sorry I was not clearer: the C1-C4 are axis groups, so they correspond to two functions (increment/decrement) and I have no idea how they should be used in the code, sorry...

I will try to look for more info on this and get back to you

**Comment by ncanceill** [comment]
... and to answer you second question:

Since KSP 1.7.1, axis groups (including C1-C4) are used to control a [KSPAxisField](https://kerbalspaceprogram.com/api/class_k_s_p_axis_field.html) (which is an extension of [KSPField](https://kerbalspaceprogram.com/api/class_k_s_p_field.html))

For instance, you can use them with the robotics parts from Breaking Ground: if you set axis group C1 to the "Target Extension" of a Hydraulic Cylinder, incrementing/decrementing C1 will move the Hydraulic Cylinder up and down

For a more general view on axis groups and KSPAxisField, see [this](https://forum.kerbalspaceprogram.com/index.php?/topic/184884-tutorial-axis-group-binding-in-ksp-171-a-brief-modders-how-to/)

**Comment by KSP-TaxiService** [comment]
Do you have steps to utilize Custom Axis Groups in Editor? 

I seem not to able to invoke or interact with a custom axis group in flight. The other axis groups like Main Throttle are easy to utilize like Z = full extension and X = zero extension on specific hydraulics

**Comment by ncanceill** [comment]
To use custom axis groups in flight, you must first bind them to the keys of your choice in KSP Settings.

For instance, I have bound Custom01 to NumPad7 (increment) and NumPad1 (decrement)

Then, I can create a craft with a Mk1 Lander Can and a Hydraulic Cylinder, with the "Target Extension" of the Cylinder added to Custom01:
- If the Lander Can is manned, pressing NumPad7 will extend the Cylinder
- If the Lander Can is not manned (but has a RemoteTech connection working), pressing NumPad7 will have no effect

**Comment by KSP-TaxiService** [comment]
Hi, thanks for showing the location of the axis group keybindings.

Flight Computer ignored the new axis groups as it did not know how to handle them. It now knows to use them.

**Comment by KSP-TaxiService** [comment]
I found another issue of a manual player extension input on a hydraulic being ignored.

**Comment by ncanceill** [comment]
Thanks for looking into this!

I am not sure I understand your last comment, please let me know if I can do something to help

**Comment by KSP-TaxiService** [comment]
You can replicate it by launching remote-controller vessel with 3 hinge, hydraulic and servo parts and change its target value. Only hinge and servo follows your target inputs.

I think this issue may be a stock bug and I am waiting for 1.7.3 to see if it is fixed. If not, I will roll out the pending fix.

**Comment by ncanceill** [comment]
OK I understand, thank you

I am far from my KSP install right now but I will try to confirm the bug next week

Anyway, from your description, I agree: it sounds like a Stock bug
