### ISSUE TITLE
Missing science transmission options and information on antennae

### ISSUE THREAD

**Issue by mindset-tk** [RemoteTechnologiesGroup/RemoteTech#797]
When I try to transmit science via antenna, I don't see the option at all in the right click menu, no matter which antenna I use.  I can still transmit individual experiments and it *seems* like they follow RT rules for transmission (will test more to be sure), but that's a little annoying when transmitting a large number of items.  

Additionally, when in the VAB, none of the parts seem to have any information on science transmission in the context menu (bandwidth and energy use during transmission, etc).

If I disable RT I get the standard science transmission options on right-click, and it shows the stock transmission details in the VAB.

Is this intended behavior?  I didn't see anything in my module manager logs that suggests any of my other mods are applying anything to the antenna parts.  When I look at my persistent.sfs I see that there is no TRANSMITTER information on any of the ModuleRTAntenna items on any of my ships.  I'm wondering if I missed an important setting or if Module Manager isn't properly adding the TRANSMITTER info to the items for some reason.

Persistent.sfs: https://drive.google.com/open?id=1inOB9Dm5b09EDzvBLcRZS7a9vQlQwMGZ

MM Log: https://drive.google.com/open?id=1nHy34aC33FKQTVR9g6KOw3eScOOwCtE0

E: forgot to mention, this is on a fresh install of KSP with a collection of other freshly installed KSP mods.  But I don't see any other mods touching any of the antennas (for example, [HighGainAntenna5]) in that MM log. Remotetech is the only one.

**Comment by mindset-tk** [comment]
Quick Update: the issue persists after uninstalling all mods except for remotetech. Interestingly, if I transmit data it does route through the antenna and the antenna does go into a "transmitting" state per its right-click menu.  Please let me know if I can provide additional logs for this as well, screenshots, whatever you need. Thanks.

**Comment by mindset-tk** [comment]
Here's the player.log from the most recent run with only the remotetech mod installed. Note that although it mentions other folders at the top, I did verify that they were empty. I can run again with the folders deleted if necessary.  https://drive.google.com/open?id=1sM-ETQVIbWPmS_mRnFS7LMGLeVxblVbD

**Comment by KSP-TaxiService** [comment]
Hi @mindset-tk,

It appears that RemoteTech doesn't have the one-click transmit function and antenna science transmission details since the beginning.

I need to see if it is feasible to implement them first.

**Comment by mindset-tk** [comment]
No worries. I have a workaround for now but it would be quite a useful
feature for me :)

**Comment by KSP-TaxiService** [comment]
Hi @mindset-tk,

It is easier to implement than I thought. The underlying information is already there and I just needed to add few interface objects.
Is this information in this picture useful? Or should it be packet size, interval and cost?
![1](https://user-images.githubusercontent.com/22871614/70861138-f375dd80-1f64-11ea-859c-1cf178fda03c.PNG)

**Comment by mindset-tk** [comment]
Personally, I think that's good enough for me. Thank you!
