### ISSUE TITLE
Control indicator obscures in-flight action group editor

### ISSUE THREAD

**Issue by BTAxis** [RemoteTechnologiesGroup/RemoteTech#799]
![image](https://user-images.githubusercontent.com/119742/68898670-35c2b980-0730-11ea-8fdf-a6840768b9e4.png)

It's rather inconvenient. Ideally, it would hide along with the rest of the UI when the editor is opened.

**Comment by KSP-TaxiService** [comment]
Hi,

The flight UI, included this control dialog, is not running in Editor.

Does this show up in Editor every time?

Lastly, please provide your output_log.txt

**Comment by BTAxis** [comment]
This isn't in the editor, this is in flight. KSP 1.8 introduced action group editing in flight.

**Comment by BTAxis** [comment]
I ran KSP with only MM and RemoteTech enabled, and no output_log.txt is generated.

**Comment by KSP-TaxiService** [comment]
My bad, I overlooked the word 'in-flight' in the first place.

I will update the RemoteTech interface in alignment with the new feature.
