### ISSUE TITLE
On time-warp kill probes spin uncontrollably

### ISSUE THREAD

**Issue by AndresHdzArv** [RemoteTechnologiesGroup/RemoteTech#801]
When i time warp a probe to another planet and the timewarp stops it spins without control, even kill rotation doesn't work

**Comment by KSP-TaxiService** [comment]
Hi,

You possibly found the recently-fixed bug of wobbling when holding Kill Rotation or Maneuver Node (Commit fe6a08291248f113d0134913f7053baeddf3abf0).

Kindly assist to try out the latest build attached and replace the DLL at your end.
(temp upload)
