### ISSUE TITLE
All connections go out after loading

### ISSUE THREAD

**Issue by AndresHdzArv** [RemoteTechnologiesGroup/RemoteTech#803]
When I load my ship i have connection and the CommNet is working, but after a second all of the connections disappear

**Comment by KSP-TaxiService** [comment]
Hi, please provide the output_log.txt and minimal reproduction steps for further investigation.

Are you referring to the stock CommNet? It should not running at same time with RemoteTech.

**Comment by KSP-TaxiService** [comment]
Hi @AndresHdzArv, 

A gentle reminder on the log and reproduction step request.
