### ISSUE TITLE
Flight computer command queue gets wiped unexpectedly

### ISSUE THREAD

**Issue by Ernesto-Alvarez** [RemoteTechnologiesGroup/RemoteTech#806]
The flight computer data does not always persist on vessel changes or game restarts.

This happens whenever the game is restarted (might be expected, if properly documented), and sometimes during some (but not all) changes of active vessel. This second case is very dangerous during power save operations (put a delayed "enable comms/computer" on the queue and then shutdown antennas and hibernate computer).

Quitting to main menu and reloading appears to be enough to cause an all-craft wipe (flight computer queues empty and all computer modes are set to off). In-game wipe is not consistent but has been confirmed as well.

For now, that's all the data I can provide as I'm not doing a clean run. I'll try to do a remotetech-only run and provide more detailed data in a few days.

**Comment by Ernesto-Alvarez** [comment]
Forgot to add version data.
KSP version 1.8.1.2694 (Linux 64 bit).
RT version 1.9.4.0.
Module manager version 4.1.2.

**Comment by KSP-TaxiService** [comment]
Hi, I am also experiencing this problem, which occurs on KSP 1.8 and its upgraded Unity Engine.

The root cause is the FlightComputer ConfigNode is somehow corrupt between loading from the save and loading into FlightComputer.
