### ISSUE TITLE
Remote Tech / Near Future Exploration Compatibility...

### ISSUE THREAD

**Issue by HegemonyCricket** [RemoteTechnologiesGroup/RemoteTech#810]
I love both Remote Tech and the antennas provided by the Near Future Exploration, but they do not appear to be compatible. According to the NFE page, it would require and update from RT to fix it. Is this in the works?

**Comment by KSP-TaxiService** [comment]
Hi, 
I took a stab at this this week but the roadblock is NFE and RT have own data transmitter module, which is incompatible to each other.
I am poking around NFE codebase to see what I can do (maybe changes to both NFE and RT codebase at best guess).

**Comment by KSP-TaxiService** [comment]
[Pull request](https://github.com/ChrisAdderley/NearFutureExploration/pull/29) is submitted to NFE repository.

In follow-up, new configurations will be added here for all the NFE antennas and reflectors.

**Comment by KSP-TaxiService** [comment]
Commit 04509b0 pending KSP community feedback on config details

**Comment by KSP-TaxiService** [comment]
Closed with NFE support config in the codebase
