### ISSUE TITLE
Right clic on antenna

### ISSUE THREAD

**Issue by Azgad** [RemoteTechnologiesGroup/RemoteTech#812]
Hello everyone, when I play with RemoteTech I can't show the information of an antenna because the right clic doesn't work. Without RemoteTech, all is good. Do you know what is the problem ?

**Comment by KSP-TaxiService** [comment]
Hi, to further investigate this issue, kindly assist to provide the KSP log, per guideline below.

* In `Logs`, provide your KSP log file:
      * **Windows**: `KSP_win64\KSP_x64_Data\output_log.txt` (Up to KSP 1.3.1) or `C:\Users\%USERNAME%\AppData\LocalLow\Squad\Kerbal space Program\output_log.txt` (KSP 1.4 onwards)
      * **Mac OS**: Open Console, on the left side of the window there is a menu that says 'files'. Scroll down the list and find the Unity drop down, under Unity there will be `Player.log` ( Files>`~/Library/Logs>Unity>Player.log` )
      * **Linux**: `~/.config/unity3d/Squad/Kerbal Space Program/Player.log`

**Comment by KSP-TaxiService** [comment]
Hi, a gentle reminder on this log request.

**Comment by KSP-TaxiService** [comment]
Closed on no response to the clarification request
