### ISSUE TITLE
Mod compatible with latest version of ksp?

### ISSUE THREAD

**Issue by 94836615** [RemoteTechnologiesGroup/RemoteTech#813]
Is this mod compatible with the latest version of ksp? I had looked in CKAN and it said that its was not compatible with version 1.9.9

**Comment by KSP-TaxiService** [comment]
No, 1.9.9 is just possible max version of KSP, which is currently 1.9.1

I am unwilling to set RemoteTech's max KSP version to 1.9.9 as there no newer versions (1.9.2 - 1.9.9) yet.
