### ISSUE TITLE
RC-XS1 Remote Guidance Unit shows as "local control"

### ISSUE THREAD

**Issue by dmayan-ss** [RemoteTechnologiesGroup/RemoteTech#816]
As the title says,

Thanks

**Comment by KSP-TaxiService** [comment]
Hi, is RC-XS1 from a third-party mod?

All I can find in Stock KSP is RC-001S and RC-L01 parts.

**Comment by dmayan-ss** [comment]
I'm sorry.

It is from ReStock. I already uninstalled it as it is not compatible with
1.10

Thanks!!!!
Diego Mayán

**Comment by KSP-TaxiService** [comment]
Hi,

Thanks for your clarification. 

As noted, ReStock and RestockPlus are not compatible with 1.0.x yet.

For now, this issue will be closed and raised again once the mod is updated for 1.10.x

Thanks.
