### ISSUE TITLE
Severe disruption in simulation when parts disappear because they go out of simulation range

### ISSUE THREAD

**Issue by Ernesto-Alvarez** [RemoteTechnologiesGroup/RemoteTech#817]
Under certain circumstances, not yet fully determined, a ship being taken out of the simulation because it moves out of the 20Km magic range causes the KSP to be disrupted.
KSP runs for a fraction of a second, then pauses. After a few seconds, the cycle repeats. This goes on until the vessel being tracked is destroyed.
The log seems to point to remotetech, because for every pause, an entry like the following is generated.

[EXC 14:13:57.717] KeyNotFoundException: The given key was not present in the dictionary.
        System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
        RemoteTech.NetworkManager.FindNeighbors (RemoteTech.ISatellite s) (at <6e868a7f3b664c77a14865f907e2a9a5>:0)
        RemoteTech.NetworkPathfinder.Solve[T] (T start, T goal, System.Func`2[T,TResult] neighborsFunction, System.Func`3[T1,T2,TResult] costFunction, System.Func`3[T1,
T2,TResult] heuristicFunction) (at <6e868a7f3b664c77a14865f907e2a9a5>:0)
        RemoteTech.NetworkManager.FindPath (RemoteTech.ISatellite start, System.Collections.Generic.IEnumerable`1[T] commandStations) (at <6e868a7f3b664c77a14865f907e2a
9a5>:0)
        RemoteTech.NetworkManager.OnPhysicsUpdate () (at <6e868a7f3b664c77a14865f907e2a9a5>:0)
        RemoteTech.RTCore.FixedUpdate () (at <6e868a7f3b664c77a14865f907e2a9a5>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

It looks like RT is banging its head on a wall, looking for something that is no longer there. This probably has to do with the fact that I switched tracking to a part that does not have any radios or computer at all, and the disruption starts as soon as the main mission (which has the computer and radios) is removed when it gets past 20km range from the dumb part. This does not appear to happen on all occasions, but I think that I've got it to happen consistently on this save.

(Note: It makes sense to observe the dumb part, as I'm testing a new rocket and I need to see if first stage recovery goes well).

I had seen something like this at other opportunities, mainly when a vessel undergoes rapid unplanned disassembly. I suspect it happened because certain parts also moved out of range (or were destroyed).

I'm using KSP 1.10 (but I've seen it happen on other versions, 1.8 or 1.7 I think), making history and breaking ground (they were not present when this issue was originally seen in earlier versions).

Mods in use are:
Clickthrough blocker
Toolbarcontrol
Community Category Kit
Community Resource pack
Contract configurator
Contract packs
Dangit
Easy vessel switch
FMRS
KIS
KAS
Kerbal engineer redux
kOS
Mechjeb 2
ModuleManager 4.1.3
NavBall docking alignment CE
Persistent Rotation
RemoteTech
Reposofttech
SCANSat
StageRecovery
TAC life support
KAC

[R4-A.craft.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/5058444/R4-A.craft.txt)
[KSP.log](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/5058422/KSP.log)
[RT disruption.sfs.txt](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/5058425/RT.disruption.sfs.txt

**Comment by KSP-TaxiService** [comment]
Hi,

Thanks for reporting this issue. 

Please try the new build [RemoteTech_Dev15Aug2020.zip](https://github.com/RemoteTechnologiesGroup/RemoteTech/files/5078931/RemoteTech_Dev15Aug2020.zip) with a fix on KeyNotFoundException. It should not generate so many logs in this situation.

Please let me know if you still experience the disruption with this new build.

Thanks.
