### ISSUE TITLE
Mod is missing from CKAN, and does not contain a .ckan meta file.

### ISSUE THREAD

**Issue by MaverickMartyn** [RemoteTechnologiesGroup/RemoteTech#819]
What the title says.

**Comment by 7ranceaddic7** [comment]
It's there.  Make sure you are not filtering.

Failing that, quit CKAN, delete CKAN/registry.json, and launch again.

![image](https://user-images.githubusercontent.com/4062616/91647436-a14fec00-ea0f-11ea-9d5f-7d0829723dc1.png)

**Comment by MaverickMartyn** [comment]
Yeah, sorry about this. I misunderstood how the filtering worked.
Closing this issue now. Again, sorry. :)
