### ISSUE TITLE
Flight UI not visible in KSP 1.11

### ISSUE THREAD

**Issue by gjulianm** [RemoteTechnologiesGroup/RemoteTech#821]
Hello,

I don't know if you've already tested RT in KSP 1.11. It seems to be working well, except for the fact that the flight computer button and delay textbox are not visible in the flight UI. I suspect it has something to do with the "Warp to sunrise" button and the timewarp control being changed. I checked the logs but didn't see anything related to RT. 

I don't know if that's already on your radar, if not I think this evening or tomorrow I could give it some time and see if I can send you a PR with a fix.

**Comment by KSP-TaxiService** [comment]
Hi, thanks for helping to confirm there is only the UI issue in KSP 1.11.

It is indeed due to the new sunrise button.
