### ISSUE TITLE
Balance: Deployable/Relay Antennas

### ISSUE THREAD

**Issue by dbackstr** [RemoteTechnologiesGroup/RemoteTech#827]
Hi all. I've noticed that with RemoteTech there is a change to the way the stock antennas are balanced. Since all antennas now behave the same-- i.e. are capable of acting as relays-- The balance between the stock deployable and relay antennas is strange. It seems like there is no reason to use the stock relay antennas (R5, R50, R100) versus their deployable counterparts, which are cheaper, lighter, and, in some cases, higher range. I've edited my version of RT so that the (R50) relay dish has 25Gm of range instead of 10, and the deployable version (HighGainAntenna) has 10Gm instead of 25, and plan to play for a bit to see if that's a good balance; I'll report back later. My apologies If I've missed a balancing feature that addresses this already-- feel free to close the issue in that case.

**Comment by KSP-TaxiService** [comment]
Hi, sorry for late response. You are right that RA-15 and RA-100 are less attractive than their counterparts, with the only advantage of higher cone angle.

How about these RA-15 and RA-100 changes below to be more comparable to the counterparts in range and better in cone angle and drain rate? I want to avoid break players' existing comm networks i.e. better range and/or lower cost without having to rebuild.

Antenna | Cost | Mass<br/>(tons) | Atmosphere<br/>safe | Cone&nbsp;angle<br/>(degree) | Range (Mm) | Power&nbsp;Drain<br/>(charge/s)
--- | ---: | ---: | ---: | ---: | ---: | ---:
HG-5 High Gain Antenna| 600 | 0.070 | No | 90.000 | 20.00 | 0.55 
Communotron DTS-M1| 900 | 0.050 | No | 45.000 | 50.00 | 0.82 
Reflectron KR-7| 800 | 0.050 | Yes | 25.000 | 90.00 | 0.82 
RA-2 Relay Antenna| 1,800 | 0.150 | Yes | 12.500 | 200.00 | 1.15 
RA-15 Relay Antenna| 2,400 | 0.300 | Yes | 0.250 | ~~10,000.00~~<br/>**20,000.00** | ~~1.10~~<br/>**0.95**
Communotron HG-55 | 1,200 | 0.075 | No | 0.120 | 25,000.00 | 1.04 
Communotron 88-88 | 1,500 | 0.100 | No | 0.060 | 40,000.00 | 0.93 
Reflectron KR-14 | 2,000 | 0.200 | Yes | 0.040 | 60,000.00 | 0.93  
RA-100 Relay Antenna| 3,000 | 0.650 | Yes | 0.025 | ~~100,000.00~~<br/>**200,000.00** | 1.10 
CommTech-1 | 9,500 | 0.300 | Yes | 0.006 | 350,000.00 | 2.60 
Reflectron GX-128| 11,000 | 0.240 | No | 0.005 | 400,000.00 | 2.80
