### ISSUE TITLE
Remote tech broken in 1.12

### ISSUE THREAD

**Issue by genehwung** [RemoteTechnologiesGroup/RemoteTech#829]
Just tried out 1.12.1. All the RT connections disappeared. I don’t seem to be able to find the processing computer symbol either.

**Comment by KSP-TaxiService** [comment]
Hi, I tested RT 1.9.11 on KSP 1.12.1 and it is works fine, apart from interface update to offset-positioned signal delay window.

Please provide your log, per [`Logs` sub-section](https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/CONTRIBUTING.md#bug-reports) for further investigation.

**Comment by genehwung** [comment]
I did a little testing, with most of the mods removed, It is working!
Sorry for the false alarm. With other mods throwing exception, I think what I have is not a remote tech issue. Closing the bug now. Thanks!
