### ISSUE TITLE
Flight computer should hold attitude after a burn

### ISSUE THREAD

**Issue by Starstrider42** [RemoteTechnologiesGroup/RemoteTech#83]
The current behavior is that, when the flight computer is done with a burn, it switches itself off. Since at the end of a burn your ship will be slewing to follow the residual maneuver node, turning the flight computer off will let it freely rotate along a random axis. Issuing an attitude control command to prevent this is, at best, annoying, and if you have signal delay requires you to know the exact length of the burn ahead of time.

I propose that the default post-burn mode be changed from "off" to "kill rotation". It's a more natural alternative, and doesn't require any guesswork to pinpoint when the burn ends. Naturally, if #73 gets implemented this change would only apply to the last maneuver node in a series.

**Comment by Peppie23** [comment]
I changed the off mode to killrot with version v1.6.2.
