### ISSUE TITLE
Change Timescale

### ISSUE THREAD

**Issue by Mitokandria** [RemoteTechnologiesGroup/RemoteTech#850]
I can't seem to find a way to change the timescale in the flight computer. I'm playing 1:1 scale (10x) which uses a 24-hour clock, but the flight computer remains a 6-hour clock.

Is it possible to add an option for timescale? 6 hours (default), 12 hours, and 24 hours?

**Comment by Aebestach** [comment]
In-game event settings should be available in the initial menu.

**Comment by Mitokandria** [comment]
> In-game event settings should be available in the initial menu.

The world-scale settings in the initial menu are only focused on antenna ranges and KSP antenna range. The options available in there do not effect the time scale of the Flight Computer which always assumes a 6 hour day.

Unless I'm missing something obvious? (this is not sarcasm) I also don't see anything in the default_settings.cfg related to time scale.

**Comment by Aebestach** [comment]
You can use RT in the RSS environment and see if it changes. If it changes you can look into the configuration under RSS.

**Comment by Mitokandria** [comment]
> You can use RT in the RSS environment and see if it changes. If it changes you can look into the configuration under RSS.

I'll give that a try and report back shortly.

**Comment by Mitokandria** [comment]
Accidental closure

**Comment by Mitokandria** [comment]
Well RemoteTech does seem to read the time properly, but I'm not sure what RSS does. Looking at the Remote Tech patch in RSS it doesn't show anything other than stations. I think they may be doing it through Kopernicus? I'll reach out to the RSS devs about it and see if the same method can be incorporated into JNSQ.

Thank you.
